### ISSUE TITLE
Errors with Leaflet 1.7.1

### ISSUE THREAD

**Issue by nekromoff** [Leaflet/Leaflet.markercluster#1003]
- [x ] I'm reporting a bug, not asking for help
- [x ] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.7.1
- Leaflet.MarkerCluster version I'm using: 1.4.1
- Browser (with version) I'm using: FF latest
- OS/Platform (with version) I'm using: n/a

## What behaviour I'm expecting and which behaviour I'm seeing
Map does not load

## Minimal example reproducing the issue
Download Leaflet 1.7.1, change links in your header to include this version, run your code.

- [x ] this example is as simple as possible
- [ x] this example does not rely on any third party code

![image](https://user-images.githubusercontent.com/8550349/92331988-b3b6cf00-f07a-11ea-9344-d2c40578cb58.png)

**Comment by IvanSanchez** [comment]
Cannot reproduce. https://plnkr.co/edit/u0YQ6wA0yV6diwqF
