### ISSUE TITLE
Улучшение подключения скрипта к основному

### ISSUE THREAD

**Issue by BuslikDrev** [Leaflet/Leaflet.markercluster#1007]
//this is needed so people can lazy load these scripts
//https://github.com/Leaflet/Leaflet.markercluster/blob/v1.4.1/dist/leaflet.markercluster-src.js

/*
 * Leaflet.markercluster 1.4.1+master.94f9815,
 * Provides Beautiful Animated Marker Clustering functionality for Leaflet, a JS library for interactive maps.
 * https://github.com/Leaflet/Leaflet.markercluster
 * (c) 2012-2017, Dave Leaver, smartrak
 */

(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
	typeof define === 'function' && define.amd ? define(['exports'], factory) :
	(factory((global.Leaflet = global.Leaflet || {}, global.Leaflet.markercluster = global.Leaflet.markercluster || {})));
}(this, (function (exports) { 'use strict';

/*
 * L.MarkerClusterGroup extends L.FeatureGroup by clustering the markers contained within
 */

function javascript_abort()
{
   throw new Error('This is not an error. This is just to abort javascript');
}

fixLStartModule();
function fixLStartModule() {
	if (typeof L === 'object') {
		fixLStartModuleScript();
	} else {
		setTimeout(fixLStartModule, 50);
	}
}

function fixLStartModuleScript() {
/* code */
}})));

//# sourceMappingURL=leaflet.markercluster-src.js.map

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
