### ISSUE TITLE
 Namespace '"C:/Data/Solutions/.../node_modules/@types/leaflet/index"' has no exported member 'MarkerClusterGroup'.

### ISSUE THREAD

**Issue by msbhb5** [Leaflet/Leaflet.markercluster#1009]
Got leaflet and leaflet.markercluster installed
![image](https://user-images.githubusercontent.com/5077690/94221022-65407600-ff3e-11ea-9583-f4a691ec6277.png)
![image](https://user-images.githubusercontent.com/5077690/94221127-9620ab00-ff3e-11ea-860c-b54d2272ac77.png)
Imported them as such:
![image](https://user-images.githubusercontent.com/5077690/94221224-c36d5900-ff3e-11ea-9a55-150aa3dd1742.png)
but when using:
![image](https://user-images.githubusercontent.com/5077690/94221280-e5ff7200-ff3e-11ea-8b9f-74193375d06c.png)
reports: has no exported member 'MarkerClusterGroup'.
Can I get some help please?

**Comment by IvanSanchez** [comment]
We don't handle typescript in this repo.
