### ISSUE TITLE
Feature Request - Cluster by type.

### ISSUE THREAD

**Issue by rwjam** [Leaflet/Leaflet.markercluster#1010]
More just posting out of curiosity.  Is it possible to cluster points by a 'type' or 'id' value?  

Ex: say I had a a point map with 1k sites, each site is assigned a type value of 'a', 'b', 'c', etc, and I wanted the option to cluster all sites with the same type together (e.g., all type 'a' together, all type 'b' together, etc).

**Comment by IvanSanchez** [comment]
No; the approach is to create one instance of `MarkerCluster` per category/type/whatever.
