### ISSUE TITLE
Transform clusterRadius from meters to pixels 

### ISSUE THREAD

**Issue by HunterJS-bit** [Leaflet/Leaflet.markercluster#1012]
Hi, I'm using your plugin 'markercluster' and it works great
But I have a question regarding the **maxClusterRadius** option
Is there any way it can be converted to meters,
Or can I just pass meters and convert it to pixels,
I have read somewhere that I would need to make, inverse of map.distance() - get the map width from map.getSize(), calculate the length (in meters) of a horizontal line crossing the map center and do a bit of math to get the meter-to-pixel ratio for the current zoom level 

Could someone help out a bit? 

## How to reproduce

- Leaflet version I'm using: 1.3.4
- Leaflet.MarkerCluster version I'm using: latest

**Comment by IvanSanchez** [comment]
Seriously, pal?

https://gis.stackexchange.com/questions/377033/leaflet-geodata-marker-clustering-and-intersection

**Comment by HunterJS-bit** [comment]
Sorry, I was searching for this urgently so thats why I posted it multiple times :/
