### ISSUE TITLE
Version 1.4.1 is incompatible with Leaflet versions older than 1.3

### ISSUE THREAD

**Issue by NuriSanv** [Leaflet/Leaflet.markercluster#1020]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: ^1.4.0
- Leaflet.MarkerCluster version I'm using: ^1.4.1
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Linux

## What behaviour I'm expecting and which behaviour I'm seeing
The latest version of Leaflet.markercluster is incompatible with Leaflet versions older than 1.3
![image](https://user-images.githubusercontent.com/47540535/102074861-4c3cb800-3dfd-11eb-9658-4fb2d05f1317.png)

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by ykzeng** [comment]
this should have been resolved by >=1.5.0 versions, let me know if the problem persists.
