### ISSUE TITLE
Create new Github release for version `1.5.0`

### ISSUE THREAD

**Issue by kentr** [Leaflet/Leaflet.markercluster#1025]
Awesome that there's a new maintainer!

- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: n/a
- Leaflet.MarkerCluster version I'm using: n/a
- Browser (with version) I'm using: Safari 13.1.2
- OS/Platform (with version) I'm using: MacOs 10.13.6

1. Go to the [Leaflet.markercluster releases page](https://github.com/Leaflet/Leaflet.markercluster/releases).
2. Look at the latest release number

### Expecting

Latest release is `v1.5.0`, corresponding to commit 871d92f

### Seeing

Latest release is `v1.4.1`

**Comment by ykzeng** [comment]
hi @kentr thanks for pointing out. I am working on several other PRs and will bump the github version once I have them merged.
