### ISSUE TITLE
Same coordinates are grouped differently based on order

### ISSUE THREAD

**Issue by MelvV** [Leaflet/Leaflet.markercluster#1029]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.7.0
- Leaflet.MarkerCluster version I'm using: 1.4.4
- Browser (with version) I'm using: Google Chrome, Version 91.0.4472.77 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Ubuntu 20.04

- Add multiple coordinates to a marker cluster group and check how they are grouped on the map.
- Add the same coordinates to a marker cluster group and they will be grouped differently.

## What behaviour I'm expecting and which behaviour I'm seeing

I'm expecting the same list of coordinates to be grouped into the same size of cluster groups, order of the coordinates should not matter.

## Minimal example reproducing the issue

- Add the following coordinates to a marker cluster group:
`{latitude: 52.315723, longitude: 5.6257133},
      {latitude: 52.366257, longitude: 5.60395 },
      {latitude: 52.361248, longitude: 5.7662344},
      {latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.291832, longitude: 6.0124245}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.236458, longitude: 5.243757}
      ,{latitude: 52.61065, longitude: 5.642131}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.23491, longitude: 5.4617057}
      ,{latitude: 52.68234, longitude: 6.2220535}
      ,{latitude: 52.274784, longitude: 5.727014}
      ,{latitude: 52.211212, longitude: 5.4441237}`

- Add the following coordinates to a marker cluster group (same coordinates but different order):
`  {latitude: 52.366257, longitude: 5.60395 },
      {latitude: 52.315723, longitude: 5.6257133},
      {latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.291832, longitude: 6.0124245}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.236458, longitude: 5.243757}
      ,{latitude: 52.61065, longitude: 5.642131}
      ,{latitude: 52.553196, longitude: 5.883366}
      ,{latitude: 52.23491, longitude: 5.4617057}
      ,{latitude: 52.68234, longitude: 6.2220535}
      ,{latitude: 52.361248, longitude: 5.7662344}
      ,{latitude: 52.274784, longitude: 5.727014}
      ,{latitude: 52.211212, longitude: 5.4441237}`

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
> I'm expecting the same list of coordinates to be grouped into the same size of cluster groups, order of the coordinates should not matter.

While that's a reasonable assumption, that would mean changing the *whole* clustering algorithm, and that would imply a full recalculation every time a new marker is added (most likely deferred, but still full).

The current algorithm uses an existing data point as the center of a cluster. The extreme case is switchting the center to the end and expecting the algorithm to recalculate then.

e.g. having a set of close points ABCDEF....XYZ will create a cluster centered on A. Having a group BCEDF....XYZ and *then* adding A at some later time to have BCDEF....XYZA should recalculate *everything* (because nearby clusters) so that A gets to be the center.

So, this is a "performance vs determinism" issue, and the path chosen shall be performance.
