### ISSUE TITLE
Sample of clustering with smart cluster icon selection

### ISSUE THREAD

**Issue by kfuntak** [Leaflet/Leaflet.markercluster#1030]
Hi all,

I am opening issue here because I was not able to contact some of larger contributors to project.

When I explored possibilities of Leaflet.markercluster, I was not able to find some sample where cluster on map is presented with some of marker icons from cluster child markers.
Showing only number of icons in cluster is usual use case, but sometimes, some logic should be used to pull out some child marker icon.

With not lot of customizations, I was able to implement smart cluster visualization for Croatian weather map, pulling most present weather sign in group and to show temperature of place with such weather in group which is closest to average temperature in cluster group. Using this logic, user at any zoom level is able to have perception of weather in some area.

You can check that behavior at this link:
http://hrvrijeme.com/
and I am willing to help anyone who wants to implement similar functionality.

Talking about some framework support for this kind of behavior, it would be nice to have ability to just turn on option to show most frequent marker icon in cluster group as cluster icon, with small circle in corner showing number of markers in cluster.

Please be free to contact me at kfuntak@gmail.com with any question.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
