### ISSUE TITLE
Allow `unspiderfy` to not close opened popups

### ISSUE THREAD

**Issue by azmeuk** [Leaflet/Leaflet.markercluster#1033]
## My configuration

- Leaflet version I'm using: 1.7.1
- Leaflet.MarkerCluster version I'm using: 1.5.0
- Browser (with version) I'm using: Firefox 92
- OS/Platform (with version) I'm using: Archlinux

## How to reproduce

- Load a lot of markers in a cluster group
- Use an external event to spiderfy some markers
- Click on a marker, open a popup
- Use an external event to spiderfy some other markers

## What behaviour I'm expecting and which behaviour I'm seeing

Now in this situation, the second `spiderfy` call automatically closes the previous opened popup. I would like to be able to keep it open. I believe this is not possible yet due to this line:

https://github.com/Leaflet/Leaflet.markercluster/blob/499f71caa1fe8a4efcf91b85e42553f9a90306f1/src/MarkerCluster.Spiderfier.js#L313

I suggest adding an option to the `spiderfy` and `unspiderfy` functions, to let the previous popups opened.

## Minimal example reproducing the issue

Click on a button, it will spiderfies a group.
Click on a marker, open a popup.
Click on another button, it will spiderfies another group, but this will **close the previous popup**

https://jsfiddle.net/azmeuk/x7e8vc5p/2/

**Comment by IvanSanchez** [comment]
Won't do, because https://gis.stackexchange.com/a/412110/53755

**Comment by azmeuk** [comment]
Thank you for your answer.
Do you say you would refuse a pull request with a `closePopup` option for `spiderfy` and `unspiderfy` methods?
As the stackexchange answer says, there is no clean way to achieve this today, and the *just fork it* option is not practical at all in the long term.

Anyway, if this is OK with you, I volunteer to provide a patch.

What do you think?
