### ISSUE TITLE
 Cannot read property ...... of undefined

### ISSUE THREAD

**Issue by ju76** [Leaflet/Leaflet.markercluster#105]
Hello,

i have a class, that reloads markers and make a reposition of my friends. In the Cluster i have the following errors:

code:
if (typeof(dataArray[friendid]['marker']) == 'undefined') {
dataArray[friendid]['marker'] = new L.Marker(new L.LatLng(dataArray[friendid]['latitude'], dataArray[friendid]['longitude']), {icon: dataArray[friendid]['icon']});
markers.addLayer(dataArray[friendid]['marker']);
} else {
dataArray[friendid]['marker'].setLatLng(new L.LatLng(dataArray[friendid]['latitude'], dataArray[friendid]['longitude']));
dataArray[friendid]['marker'].setIcon(dataArray[friendid]['icon']);
}

TypeError: Cannot read property 'x' of undefined
at Object.L.DistanceGrid._sqDist (friendid/js/leaflet.markercluster-src.js:1338:20)
at Object.L.DistanceGrid.getNearObject (friendid/js/leaflet.markercluster-src.js:1320:20)
at L.MarkerClusterGroup.L.FeatureGroup.extend._addLayer (friendid/js/leaflet.markercluster-src.js:616:36)

and

Code:
markers.removeLayer(dataArray[friendID]['marker']);

after a while i got:

delete old marker error
TypeError: Cannot read property '__parent' of undefined
at L.MarkerClusterGroup.L.FeatureGroup.extend.removeLayer (friendid/js/leaflet.markercluster-src.js:106:13)

did anyone have a idea where the problem?

i thing it occurse if a marker moves out of a cluster or will delete from a cluster. Then the problem starts ...

kind regards

ju

**Comment by pedrokost** [comment]
I've stumbled upon the same issue. Has there been any progress by anyone on this?

**Comment by pedrokost** [comment]
It is reproducible (survives reboots/reinstall library/etc), but it is weird :)

In my case I have a leaflet map (using ember-leaflet) that displays an image with markers on top. When I drag a marker and click save, ember-leaflet takes care of updating the icons on the map if necessary.

However, I can only move the markers in certain locations without resulting in an error (object holding 'x' or '_zoom' property are undefined) (reproducible). I have drawn on the below image the "safe" areas where I can move the markers. Note that the Yellow marker can not be moved without producing an error.

There are also 2 areas, marked in red, where I can't put the marker (these seem anomalies in the pattern). Note that the left one is very reproducible, the one on the right -- sometimes works sometimes not.

![bugymap](https://cloud.githubusercontent.com/assets/725286/6287376/4fd8df10-b911-11e4-9b66-eb1a6cb852af.png)

**Comment by danzel** [comment]
So you are moving markers within a marker cluster? That isn't supported.

It is supported in the leaflet-master branch using the master version of leaflet

**Comment by jeancaffou** [comment]
See #635 comment [#271186191](https://github.com/Leaflet/Leaflet.markercluster/issues/635#issuecomment-271186191)

**Comment by nthbr** [comment]
Hi 
I had these errors using webpack optimized builds, not in dev mode.

I ended up with this fix :
`
(function fixMarkerCluster( Leaflet ) {
    let ollb = Leaflet.latLngBounds;
    let olb  = Leaflet.bounds;

    // hardcore dirty hack WTF fix for leaflet/markercluster fail in prod builds

    // Marker cluster seems to think Leaflet.latLngBounds clone the bounds if bounds param is a leaflet llbound
    // it does not and return unitialized llbounds in prod build
    Leaflet.latLngBounds                 = function ( bounds ) {
        var r = ollb(...arguments) || ollb();
        if ( (!r._northEast || !r._southWest) ) {
            Object.keys(bounds).map(k => (r[k] = bounds[k]));//should clone
        }
        return r;
    };
    // same for screen bounds
    Leaflet.bounds                       = function ( bounds ) {
        var r = olb(...arguments) || olb();
        if ( (!r.min || !r.max) ) {
            Object.keys(bounds).map(k => (r[k] = bounds[k]));
        }
        return r;
    };
    // Void some marker cluster redraw issues in react .. 
    // let ormi                             = Leaflet.Marker.prototype._removeIcon;
    // Leaflet.Marker.prototype._removeIcon = function () {
    //     return this._icon && ormi.apply(this, arguments);
    // }
})(Leaflet);`

**Comment by khazri-mamedov** [comment]
Hi. This works for me

<html>
<head>
    <link rel="stylesheet" href="leaflet.css" />
    <link rel="stylesheet" href="leaflet-routing-machine.css" />
    <link rel="stylesheet" href="leaflet.awesome-markers.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="vue.min.js"></script>
    <script src="leaflet.js"></script>
    <script src="leaflet-routing-machine.js"></script>
    <script src="leaflet.awesome-markers.js"></script>
</head>
<body style="margin:0;padding:0;">
<div id="app">
    <div :id="mapId" style="height: 100%"></div>
</div>
<script>
        var app = new Vue({
            el: '#app',
            data: {
                leafletMap: null,
                courierLocation: null
            },
            mounted() {
                this.initializeMap();
            },
            methods: {
                initializeMap() {
                    let leafletMapOptions = {
                        center: [40.4093, 49.8671],
                        zoom: 13,
                        zoomControl: false,
                        renderer: L.canvas(),
                        maxZoom: 18,
                        minZoom: 10,
                        maxBounds: [[40.1878, 49.5614], [40.6551, 50.6394]]
                    };
                    this.leafletMap = L.map(this.mapId, leafletMapOptions);
                    let tileUrl = 'https://osm.atl.az:10443/tiles/{z}/{x}/{y}.png';
                    let tileLayerOptions = {
                        attribution: '&copy; ATL ',
                    };
                    L.tileLayer(tileUrl, tileLayerOptions).addTo(this.leafletMap);
                },
                setCourierLocation(marker) {
                    courierLocation = L.marker({}, {
                        icon: L.AwesomeMarkers.icon({
                            icon: 'user',
                            prefix: 'fa',
                            markerColor: 'green'
                        })
                    }).setLatLng(L.latLng(marker.lat, marker.lng)).addTo(this.leafletMap);
                }
            },
            computed: {
                mapId() {
                    return `leafletMap_`;
                }
            }
        });

    </script>
</body>
</html>

**Comment by Mahender-224** [comment]
Why Worldmap panel is showing the error "cannot read properties of x of undefined " when I tried to plot the points from myself database
