### ISSUE TITLE
Testing new leaflet 1.8.0-beta.0 with markerCluster

### ISSUE THREAD

**Issue by tomik23** [Leaflet/Leaflet.markercluster#1053]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----
I'm testing a new leaflet version.

## How to reproduce

- Leaflet version I'm using: 1.8.0-beta.0
- Leaflet.MarkerCluster version I'm using: 1.5.4
- Browser (with version) I'm using: All ;)
- OS/Platform (with version) I'm using: Windows 10

## Minimal example reproducing the issue
```
let markers = L.markerClusterGroup();

for (let i = 0; i < points.length; i++) {
  const [lat, lng, title] = points[i];
  let marker = L.marker(new L.LatLng(lat, lng));
  marker.bindPopup(title);
  markers.addLayer(marker);
}

map.addLayer(markers);
```
The error that appears is:

```
Point.js:67 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at p._subtract (Point.js:67:19)
    at p.subtract (Point.js:63:23)
    at i._panOnFocus (Marker.js:397:29)
    at HTMLDivElement.o (DomEvent.js:108:13)
```

**Comment by indigoxela** [comment]
This seems to be related: https://github.com/Leaflet/Leaflet/discussions/8044#discussioncomment-2426002

Fix got merged into Leaflet:main https://github.com/Leaflet/Leaflet/pull/8084

**Comment by tomik23** [comment]
Thanks for the information, in this case I am closing the issue
