### ISSUE TITLE
Clusters do not spiderfy on click under Leaflet 1.9.0

### ISSUE THREAD

**Issue by lucaswerkmeister** [Leaflet/Leaflet.markercluster#1074]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.9.0
- Leaflet.MarkerCluster version I'm using: 1.5.3
- Browser (with version) I'm using: Firefox Developer Edition 104
- OS/Platform (with version) I'm using: Ubuntu 22.04 Jammy Jellyfish
- create a marker cluster group with several closely adjacent markers and add it to a map
- click the group

## What behaviour I'm expecting and which behaviour I'm seeing
I expect the group to “spiderfy”, showing the individual markers. But nothing actually happens.

## Minimal example reproducing the issue
https://plnkr.co/edit/UJsTp5X6jabP8v0L

Working 1.8.0 version for comparison: https://plnkr.co/edit/ZxyGxSnT6Ke1EvdG

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by indigoxela** [comment]
See also: https://github.com/Leaflet/Leaflet/issues/8450

**Comment by Falke-Design** [comment]
Will be fixed in Leaflet core

**Comment by lucaswerkmeister** [comment]
Fixed in 1.9.1: https://plnkr.co/edit/j1UtvZzuYo8PYSfW

Thanks @Falke-Design!
