### ISSUE TITLE
how to remove duplicate maps after realtime update latitude from firestore 

### ISSUE THREAD

**Issue by bobwatcherx** [Leaflet/Leaflet.markercluster#1080]
i have a problem , even though it has nothing to do with the quasar . i made a realtime geolocation track with quasar and firestore . when there is a change latitude and longitude in the firestore, the marker on the leaflet will automatically change position, all of that works, but when I zoom out. there are two maps. how not to happen like that
how to replace and replace it with the latest marker position and delete the previous map
![image](https://user-images.githubusercontent.com/52072811/205421323-93fb8308-88e0-4371-93e9-e00d73e2957f.png)

code :
```
onMounted(async () => {
  // REALTIME MAPBOX DARI FIRESTORE
  const unsub = onSnapshot(doc(db, "transaksi", myid.value), (doc) => {
    console.log("Current data: ", doc.data());
    datakurir.value = doc.data();
    // console.log(datakurir.value.kurir.latitude)
    let latitude = datakurir.value.kurir.latitude;
    let longitude = datakurir.value.kurir.longitude;
    if (datakurir.value.kurir != undefined) {
      var container = L.DomUtil.get("mapContainer");
      mymap = L.map("mapContainer").setView([latitude, longitude], 5);
      var osm = L.tileLayer("http://{s}.tile.osm.org/{z}/{x}/{y}.png", {
        attribution:
          '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
      });
      if (container != null) {
        container._leaflet_id = null;
        console.log("jalananan");
        if (marker != undefined) {
          mymap.removeLayer(marker);
        }
        // mymap.removeL2ayer(marker)
        // marker = L.marker([latitude, longitude]).bindPopup("Kurir ada di sini").openPopup().addTo(mymap);
        marker = L.marker(new L.LatLng(latitude, longitude))
          .bindPopup("Kurir ada di sini")
          .openPopup()
          .addTo(mymap);
        osm.addTo(mymap);
        // var newLatLng = new L.LatLng(latitude, longitude);
        // marker.setLatLng(newLatLng);
        // document.getElementById("mainmap").outerHTML = "";
        // marker.addTo(mymap);
        // mymap.addLayer(osm);
      }
      console.log("Dda" + latitude + longitude);
    }
  });
});
```

template:
<div id="mapContainer" style="height:400px"></div>

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
