### ISSUE TITLE
Support for ES version of the module

### ISSUE THREAD

**Issue by FiabioProjects** [Leaflet/Leaflet.markercluster#1081]
Hi, I'd like to include this plugin in my project, however I cannot make it work as it is, but the ECMASCRIPT version module is required in order to be imported correctly.
Is it on your mind to release the esm version of leaflet.markercluster? (Like leafet did for its leaflet-src.esm).
Thanks in advance

**Comment by feeva** [comment]
You can just `import`. 

```
import 'leaflet';
import 'leaflet.markercluster'
```

Btw, I have also added the package `@types/leaflet` for type support.
