### ISSUE TITLE
Examples don't work leaflet.markercluster-src.js missing in dist folder

### ISSUE THREAD

**Issue by Japhys** [Leaflet/Leaflet.markercluster#1090]
I just downloaded the zip and wanted to try the examples. There was a reference to /dist/leaflet.markercluster-src.js but the file is missing in the dist folder.

See:

https://github.com/Leaflet/Leaflet.markercluster/blob/master/example/marker-clustering-realworld-mobile.388.html

https://github.com/Leaflet/Leaflet.markercluster/tree/master/dist

**Comment by ykzeng** [comment]
you would need to build first with ```npm install``` which will generate these target files in ```dist```
