### ISSUE TITLE
New release/tag with dist JavaScript files?

### ISSUE THREAD

**Issue by he-hesce** [Leaflet/Leaflet.markercluster#1097]
Is 1.4.1 the latest official release with dist directory JavaScript files? I downloaded the 1.5.3 zip file and the dist directory JavaScript files are missing. Is there a plan to make an official new/recent official release with the dist directory JavaScript files?

**Comment by divadsn** [comment]
Download them from there: https://unpkg.com/leaflet.markercluster/dist/

**Comment by he-hesce** [comment]
@divadsn : Thanks :-)
