### ISSUE TITLE
Popup on ClusterGroup

### ISSUE THREAD

**Issue by littleiffel** [Leaflet/Leaflet.markercluster#123]
Is ti possible to get a popup over a clustergroup so that on click on an item list, the clustergroup becomes visible and a popup is indicating the clustergroup where the element marker is in) 

I know that I can use ZoomToShowLayer, however it is not the exact behaviour that I am looking for as this should happen on mouse over. And zooming in and out for hovering over different elements is not very nice for the user.

Thanks for your work (by the way)

**Comment by jdaudier** [comment]
Does this feature come built-in now?

**Comment by danzel** [comment]
Yeah, use get visible parent or whatever the function is called and open a popup there :)

**Comment by jdaudier** [comment]
What's the best way to customize the cluster popup like this one?  Thanks!
![1](https://cloud.githubusercontent.com/assets/1666031/6312735/2d884b6c-b952-11e4-98a3-3c3565f9ae23.png)

**Comment by danzel** [comment]
That would be a leaflet question, I'm actually not sure!

**Comment by jdaudier** [comment]
@danzel 

noob question... I keep getting a `getVisibleParent` is not defined error.  Any idea why I might be seeing that?

I'm trying convert this block of code to use that function:
```
			a.target.eachLayer(function(layer) {

					var m = layer;
					var content = region;
					while (!m._icon) {
						m = m.__parent;
					}

					m.on("mouseover", function () {
						m.bindPopup(content).openPopup();
					});
					m.on("mouseout", function () {
						m.closePopup();
					});
				});

**Comment by danzel** [comment]
```myMarkerClusterGroup.getVisibleParent(myCluster);```

**Comment by jdaudier** [comment]
was there supposed to be something in your msg above?  it's showing up blank

**Comment by danzel** [comment]
lol weird, fixed.

**Comment by jdaudier** [comment]
Sorry to bug ya again @danzel 

So I got it work by doing this, but is there a way to pick just one marker instead of having the popup show up for each marker in that cluster?

```
markers.on('clustermouseover', function (a) {
				var allLayers = a.target.getLayers();
				var lastLayer = allLayers.pop();
				var region = lastLayer.feature.properties.region;
				
				a.target.eachLayer(function(layer) {
				
					var m = markers.getVisibleParent(layer);
				
					m.on("mouseover", function () {
						m.bindPopup(region).openPopup();
					});
					m.on("mouseout", function () {
						m.closePopup();
					});
				});
			});
```

![2015-02-23_1622](https://cloud.githubusercontent.com/assets/1666031/6337513/2c48699e-bb78-11e4-9f12-60a4cdd8da17.png)

**Comment by danzel** [comment]
```
markers.on('clusterclick', function (a) {
//your code here that eventually opens a popup
});
```

**Comment by jdaudier** [comment]
I tried using `markers.on('clustermouseover', function (a) {` because I want the pop-up to show up on hover. However, the pop-up shows up for each marker that's in the cluster like this: http://recordit.co/xXgSg2uDBo

Is there a way I can target just 1 marker in the cluster somehow?

**Comment by danzel** [comment]
Don't loop over your markers doing the popups, just create one and show it?
http://leafletjs.com/reference.html#popup
The second example

**Comment by jdaudier** [comment]
Thanks @danzel that worked!  Is there Gitter channel for this plugin in case I have further questions?

**Comment by jdaudier** [comment]
Is there a method for getting the lat & lng for the visible parent? @danzel

So far I've been using the internal methods...
```
				var lat = markers.getVisibleParent(a.layer)._cLatLng.lat;
				var lng = markers.getVisibleParent(a.layer)._cLatLng.lng;

```

**Comment by danzel** [comment]
it is a marker iirc, so ```getLatLng() should work.
No gitter

**Comment by kylemartin87** [comment]
Hi all
I was able to get a popup to show on a cluster group using the following code based on comments from @littleiffel and @jdaudier (note that I am using AngularJS and the https://github.com/tombatossals/angular-leaflet-directive):
```javascript
leafletData.getMap().then(function(map) {
	var layers = map._layers;
	angular.forEach(layers, function (layer, key) {
		// Find the cluster layers
		if ('_gridClusters' in layer)
		{
			layer.on('clusterclick', function(a) {
				var marker = a.layer.getAllChildMarkers()[0];
				var content = marker._popup._content;
				var cluster = a.target.getVisibleParent(marker);
				cluster.bindPopup(content).openPopup();
			});
		}
	});
});
```

**Comment by Gabrielatb** [comment]
Does anyone know if this feature is also available in react-leaflet-markercluster?

**Comment by two3d** [comment]
To open the hidden popup, simply modify the openPopup function of leaflet.js:

`openPopup:function(t,i){if(!this._map&&this.__parent){this.__parent.spiderfy()}return this._popup&&this._map&(i=this._popup._prepareOpen(this,t,i),this._map.openPopup(this._popup,i)),this}`

I simply added this:

`if(!this._map&&this.__parent){this.__parent.spiderfy()}`
