### ISSUE TITLE
Utilize leaflet layering

### ISSUE THREAD

**Issue by Adventsparky** [Leaflet/Leaflet.markercluster#13]
It would be fantastic if the marker clusterer supported layers like the stock leaflet layer functionality so users can enable/disable layers of markers and have the clusters update accordingly.

**Comment by danzel** [comment]
This is implemented in a plugin now
https://github.com/Leaflet/Leaflet.markercluster#sub-plugins

**Comment by blandofgod** [comment]
Not sure if anyone is still on this, however I have fixed the fiddle example from above using multiple layers for marker cluster.  I am now looking into using the sub-plugins.
http://jsfiddle.net/pvwKJ/39/
