### ISSUE TITLE
Separate out computationally intense bits to make it compatible with web workers

### ISSUE THREAD

**Issue by calvinmetcalf** [Leaflet/Leaflet.markercluster#131]
If the clustering parts of this library were separated from the leaflet parts of this library then it would be easy to run that part in another process.  The main issue it seems to have is that quickhull assumes it's working with a leaflet point object and there seems to be some recursion in the main files which I'm not sure has to be tied to the dom. 

This seems like something that might not be hard per-say but might require a considerable re-factoring of the entire code base.

**Comment by Etienne-M** [comment]
Could we re-open this issue? I'm in a case where all-in-all, it takes 700ms to create the markers and cluster all of them. You might say it's fast, but pretty much anything above 33ms is slow *on the main thread* (33ms here is just for 30fps). So to clarify, I'm not looking to speed it up, although if it's an option that would be even better. I only want to get that work out of the main thread.
