### ISSUE TITLE
zoom in and zoom out immediately -> clusters will disappear

### ISSUE THREAD

**Issue by paulovieira** [Leaflet/Leaflet.markercluster#140]
Title says it all: if you zoom in and zoom out immediately (before the zoom in animation has ended), then the marker clusters will disappear from the map. 

This looks like a minor bug. If you do a simple pan, they will be visible again and everything will work fine. But I'm afraid this might be an indication of some other hidden bugs.

I only tested with the live examples. Maybe the recent refactoring in L.Tilelayer has solved this bug...

**Comment by DevScyu** [comment]
![image](https://user-images.githubusercontent.com/15234414/40317622-f32b9b12-5d19-11e8-8778-745191177d1b.png)
Still Exists...
