### ISSUE TITLE
MarkerCluster hangs when using circles instead of markers

### ISSUE THREAD

**Issue by Zverik** [Leaflet/Leaflet.markercluster#148]
See [the example map](http://textual.ru/circlecluster/). It uses `L.Circle(latlng, radius)` instead of `L.Marker(latlng)` for markers. The idea is to show feature ranges. I'd understand if the markercluster threw exceptions for unsupported layer type, but it hangs, and I consider this a serious bug.

**Comment by gregvenech** [comment]
I know this is old but I just noticed a small bug when using L.CircleMarker with this plugin. If the array of circle markers you pass to the cluster group only contains one marker an error is thrown:

    Uncaught TypeError: r.setOpacity is not a function(anonymous function) @         
      index.bundle.js:71683L.MarkerClusterGroup.L.FeatureGroup.extend._processQueue @ 
      index.bundle.js:71683L.MarkerClusterGroup.L.FeatureGroup.extend._mergeSplitClusters @ 
      index.bundle.js:71683L.MarkerClusterGroup.L.FeatureGroup.extend._zoomEnd @ 
      index.bundle.js:71683L.Mixin.Events.fireEvent @ 
      index.bundle.js:61685L.Map.L.Class.extend._resetView @ index.bundle.js:63299(anonymous function) @ 
      index.bundle.js:70158(anonymous function) @ index.bundle.js:61266

At first glance it looks like the plugin assumes the `setOpacity` method which does exist for regular `L.marker`s but not for `L.circleMarker`s... When I jumped to the line in the minified source it brought me here (formatted for convenience):

    this._enqueue(function() {
      if (1 === t._childCount) {
        var r = t._markers[0];
        r.setLatLng(r.getLatLng()), 
        r.setOpacity(1) // The line causing issues
      } else ...

I can create a new issue if you'd like @danzel

**Comment by danzel** [comment]
Grab a newer version of markercluster, it's been fixed since then.

**Comment by gregvenech** [comment]
Hey thanks for the quick response, I'm seeing 0.4.0 as the latest release in your [npm package](https://www.npmjs.com/package/leaflet.markercluster). Should I be grabbing it straight from github?

**Comment by danzel** [comment]
See #590
