### ISSUE TITLE
Integration with a server-side clustering implementation

### ISSUE THREAD

**Issue by dasjo** [Leaflet/Leaflet.markercluster#151]
hi,

this is just a rough idea and i'm not sure if i will have the resources for implementing this. so please take it mainly as a collection of ideas rather than an actual request to make this happen :)

i have developed Geocluster, a server-side clustering implementation for Drupal that integrates with Leaflet: http://drupal.org/project/geocluster

the clustering works quite well and scales up to 100,000 using mysql and beyond 1,000,000 items using a apache solr implementation of the Geohash-based clustering algorithm.

obviously, the visualization part of my implementation is very rough and leaves a lot of room for improvements :) i think, Leaflet.markercluster has implemented this quite nicely. i'm wondering, if one could extend markercluster to support a hybrid approach: the server provides a clustered result as geojson and the js clustering library would visualize it the same way as markercluster does. the only difference is that sub-requests to the server are issued, if necessary for expanding clusters.

let me know if you are interested adding capabilities of integrating a server-side clustering implementation / your thoughts on implementation-details. here's a link to some discussion on that topic we had in the geocluster issue queue on drupal.org http://drupal.org/node/1914704

regards,
dasjo

**Comment by dewdad** [comment]
Any progress on this?

**Comment by SimonEast** [comment]
Yes, I've also been looking into solutions for this but not really found any.

This site ([ddproperty.com/en/property-map-search](http://www.ddproperty.com/en/property-map-search)) appears to perform server-side clustering of 100,000+ markers, and it appears to use something similar to Leaflet, or maybe a forked version of it or something. Hoping to find out how they achieved it.

**Comment by vivekmtuity** [comment]
You can use [supercluster](https://github.com/mapbox/supercluster), which can load in server side, same functionality as [ddproperty.com/en/property-map-search](http://www.ddproperty.com/en/property-map-search), I am using with node js :)
