### ISSUE TITLE
Use requestAnimFrame instead of setTimeout

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet.markercluster#16]
In Leaflet source, `L.Util.requestAnimFrame(fn, context)` is used everywhere in place of `setTimeout`. It does practically the same but executes much faster. Try it!

Also, if you need to request the same update in several different places, you can do `cancelAnimFrame` before the request, so that multiple actions only trigger one reflow/repaint and update call. E.g. this is used on Leaflet `move` while panning, because browser can't update the screen as fast as the mouse moves.

I'll probably write a post about this trick in a future Leaflet blog.

**Comment by shanyuk** [comment]
how to use requestAnimFrame?
