### ISSUE TITLE
Spiderfy at all zoom levels

### ISSUE THREAD

**Issue by justinruess** [Leaflet/Leaflet.markercluster#173]
Is there a way to not cluster the pins, but to have the pins spider and zoom to the max zoom level when clicked? I like having all of the pins visible, but can't click on all of them since there are a few that overlap. Thanks!

**Comment by jadus** [comment]
I'd like to be able to programmatically disable clustering to fall to spiderfying like in the spiderfier plugin.
Would be great to be able to do this with only your plugin.

**Comment by rarkins** [comment]
Same here. Unfortunately that plugin hasn't been maintained in more than 2.5 years now too.
