### ISSUE TITLE
how to use polygonOptions

### ISSUE THREAD

**Issue by arnoldbird** [Leaflet/Leaflet.markercluster#175]
How can I disable polygons?  The docs say...

`polygonOptions: Options to pass when creating the L.Polygon to show the bounds of a cluster`

What are these options?  Example?

Thanks.

**Comment by ptrsz** [comment]
Is it possible to cluster the markers according to a geoJSON polygon - not only by pixels?

**Comment by emmjk** [comment]
guys is it possible to create a cluster according to geoJson polygon object??
