### ISSUE TITLE
Marker popup doesn't opens when It's inside group

### ISSUE THREAD

**Issue by kiselev-dv** [Leaflet/Leaflet.markercluster#180]
Hi here is my case.
1. Create 2 markers m1, m2 with same coordinates and bind popup to each other.
2. Create two links, with m1.openPopup(); and m2.openPopup();
3. Add them to marker cluster, they are olways in one group.

Popups will not shown on map, until group will be spiderfied, because marker not shown and this._map for marker are undefined.

So I use hack: 

```
if(m1._map === undefined ) {
       m1.__parent.spiderfy();
} 
```

How to make it as default behaviour, to spiderfy marker group, for marker which openPopup() was called?

**Comment by two3d** [comment]
To open the hidden popup, simply modify the openPopup function of leaflet.js:

`openPopup:function(t,i){if(!this._map&&this.__parent){this.__parent.spiderfy()}return this._popup&&this._map&(i=this._popup._prepareOpen(this,t,i),this._map.openPopup(this._popup,i)),this}`

I simply added this:

`if(!this._map&&this.__parent){this.__parent.spiderfy()}`
