### ISSUE TITLE
Markers cut off when using zoomToBoundsOnClick

### ISSUE THREAD

**Issue by adamyonk** [Leaflet/Leaflet.markercluster#185]
![screen shot 2013-06-06 at 11 30 27 am](https://f.cloud.github.com/assets/33258/619166/904aadb2-cec6-11e2-9da5-e580baf4c5d8.png)

![screen shot 2013-06-06 at 11 32 07 am](https://f.cloud.github.com/assets/33258/619171/acefc1f0-cec6-11e2-9fcf-5d3880bd5ee3.png)

In the second image, you can see that after the zoom, the markers are partially outside the bounds. Is this an issue with the `zoomToBoundsOnClick` function not calculating the size of the markers, or something that I'm doing wrong? It does include the exact lat/lng point of the marker, but it seems like it should account for the markers so that you can actually click on them after the zoom.

**Comment by int-ua** [comment]
In my case @arnoldbird 's code was sometimes not zooming at all so I've added zooming in indefinitely if it failed to zoom in on cluster click:

```
markers.on('clusterclick', function (a) {
	previous_bounds = MAP.getBounds();
	bounds = a.layer.getBounds().pad(0.16);
	MAP.fitBounds(bounds);
	if (previous_bounds.equals(MAP.getBounds())) {
		MAP.zoomIn();
	}
});
```
