### ISSUE TITLE
ZoomToShowLayer sometimes not openPopup()

### ISSUE THREAD

**Issue by absemetov** [Leaflet/Leaflet.markercluster#203]
When the marker is overseas map.
I can not understand what is the reason.
ZoomToShowLayer work fine console.log show this, but popup dont open sometimes

**Comment by absemetov** [comment]
Problem in 1.0.0-beta.2.0 when click Gunsan link.
Marker 'Gunsan' dont show or popup not open, I think this is due to  cluster animate (zoom level = 4).
https://jsfiddle.net/3Lf6kqmu/13/

**Comment by ghybs** [comment]
Hi,

Panning before calling `zoomToShowLayer()` initiates a `"movestart"` event whereas MCG did not attach the event listener yet. Therefore, it will think it did not move, and call the callback right away, whereas the parent cluster is still on map. Hence it thinks it has to spiderfy it => popup opens on spiderfied marker. But when the `zoomToBounds` in `zoomToShowLayer` completes, the cluster is split, unspiderfies, which closes back your popup and shows the marker on its correct position.

Now it looks like you still show some bug in your exact configuration, even when the panning before zooming is removed. Not sure exactly what could be the reason...

https://jsfiddle.net/3Lf6kqmu/14/

**Comment by absemetov** [comment]
@ghybs Thanks!
