### ISSUE TITLE
Defining custom marker for a specific map

### ISSUE THREAD

**Issue by rubaff** [Leaflet/Leaflet.markercluster#264]
Hi leaflet-fans,

I would like to change all markers for one specific map. I'm using leaflet with markercluster and the marker-positions are saved in an array like here: http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

```
var addressPoints = [
    [-37.8210922667, 175.2209316333, "2"],
    [-37.8210819833, 175.2213903167, "3"],
    [-37.8210881833, 175.2215004833, "3A"],
    [-37.8211946833, 175.2213655333, "1"],
....
```

Since the data is coming from the array, I can't (or at least I don't know how to) use this technique: http://leafletjs.com/examples/custom-icons.html

So you have an idea, how I can just change the marker-graphic for this one map.
My ideal solution would be something like:

```
var addressPoints = [
    [-37.8210922667, 175.2209316333, "2", "marker2.png"],
    [-37.8210819833, 175.2213903167, "3", "marker2.png"],
    [-37.8210881833, 175.2215004833, "3A", "marker2.png"],
    [-37.8211946833, 175.2213655333, "1", "marker2.png"],
....
```

Thanks!

**Comment by landkarten** [comment]
Hmm! I test the idea with realword.388 and somthing is wrong? The complet map does not load. The problem is the icons code.

```javascript

var markers = L.markerClusterGroup();
			for (var i = 0; i < addressPoints.length; i++) {
			var a = addressPoints[i];
			var title = a[2];

    if (!icons[a[3]) {
        icons[a[3]] = new L.Icon(iconUrl: a[3]);
    }

//		var marker = L.marker(new L.LatLng(a[0], a[1]), { title: title });
    		var marker = L.marker(new L.LatLng(a[0], a[1]), { title: title, icon: icons[a[3]] }));

    marker.bindPopup(title);
    markers.addLayer(marker);
}
		}

		map.addLayer(markers, icons);

	</script>

```
