### ISSUE TITLE
Slow performance with many markers

### ISSUE THREAD

**Issue by atombender** [Leaflet/Leaflet.markercluster#278]
I have a dataset of about 10,000 markers. I am seeing unacceptable performance in all browsers.

Adding all the markers to the `MarkerClusterGroup` layer only takes about 100-200ms in all browsers, but adding the layer to the map itself takes about 7 seconds in Firefox 25. In Chrome, about 2 seconds. In Safari, about 4 seconds. I suspect IE would be much worse.

Also, it’s fairly slow when navigating. Very fast when zoomed way out, but closer to the city level, zooming and having the map repaint takes 1-2 seconds. Chrome is a bit smoother than FF/Safari.

I am seeing the same loading issue with the `marker-clustering-realworld.10000.html` example. The page takes several seconds to load. That demo seems to be a bit smoother to navigate, however, most likely because the data is less spread out.

[Here](https://gist.github.com/atombender/d666faf97c0211197b2e) is my marker data.

**Comment by acartas** [comment]
I have about 250 markers and am experiencing this as well, using the standard marker icon. Does anyone have any other suggestions?

**Comment by atombender** [comment]
I recommend pre-computing and cache server side. To speed up rendering of individual markers we also went for a canvas-based layer, since rendering tens of thousands of individual divs is slow.
