### ISSUE TITLE
zooming out when popup is open

### ISSUE THREAD

**Issue by jbhatab** [Leaflet/Leaflet.markercluster#320]
whenever I click a marker and keep the popup open and then zoom out, marker clustering glitches.
It generally responds like this:

*click marker when zoomed in to activate it. This switches the divIcon and leaves the popup open
- zoom back to where the cluster would reform
- Now normal hovering and clicking of markers doesn't work properly
- Clicking the cluster with the opened popup is sometimes unresponsive
- When it does zoom in on cluster click, the markers within that cluster disappear
- Even after clicking the map, which removes the active markers, it still doesn't work properly if I have opened a popup in a cluster.

I'm not sure if it's because I am changing the icon or it's because the popup remains open, any ideas?

UPDATE: After more testing it seems that simply changing the icon of any marker then moving until that marker is out of the map causes the problem.

**Comment by MelloDredd** [comment]
I have a similar issue. When i zoom out while a selected marker with popup opened, the marker gets inside the cluster, then i zoom in and clicked that marker but popup is opening a little top and left of the marker.

![github 01](https://cloud.githubusercontent.com/assets/8975327/6941257/13e9c81c-d8a0-11e4-8e6b-ce41e634565e.PNG)

**Comment by MelloDredd** [comment]
@danzel does the plugin have any "markerAddedToCluster" kind of event ??

**Comment by danzel** [comment]
I think the popup location error is probably your custom icon.
And no, you could listen to zoom change and check visible parent

**Comment by MelloDredd** [comment]
@danzel are you saying that setting custom icon might causing this problem ? How so ? can you give me some clue ? popups are opening just fine when clicked but not opening in proper position when i zoomed out while keeping the popup open and then zoom in, clicked that marker.

**Comment by MelloDredd** [comment]
and by the way i found an alternative to  "markerAddedToCluster" event in your plugin by looking your answers in issue#138, 'zoomend' wasn't working out properly, what i had to use is 'animatioend'. So thanks.

**Comment by danzel** [comment]
Yeah. Check the attributes. Try it outside of marker cluster and you'll see
the same error.  Check the icon docs
