### ISSUE TITLE
Clustering by area

### ISSUE THREAD

**Issue by peterb-2795** [Leaflet/Leaflet.markercluster#323]
Hi there,

First off, what a fantastic plugin contribution to the leaflet eco-system.  I have been watching this plugin for some time and have always felt that it is a solution waiting for the right problem... :o)

The plugin performs really well in terms of generalised aggregation of point data and obviously does its job as designed to do.  However, there are many use-cases where one might want to constrain the node aggregation in order to control which parent node has which children attached.  This could then create an ordered hierarchical structure within the aggregation methods.

Taking the demo realworld example which is based on LINZ address data; address location and display is a pervasive problem domain.  However, addressing is not concerned with only locating a single property location.  Very commonly, there are strata addresses (horizontal and vertical), super-block addresses and many other types of address reference/location within a given parcel or parcel aggregate (eg. hospital sites, university sites, large utility installations etc).  These use-cases are often referred to as "complex address sites".

This plugin could potentially tackle all sorts of display problems in this domain (and other generalised geo-hierarchical problems) by being able to constrain node aggregations to be based upon containment polygons.  For example in the above, all address locations in a strata would combine up into the common property polygon,  and further upwards based upon other indexed polygon constraints.  Property nodes aggregated into ->suburb->postcode->administration area etc.

Sure, the use case described is address focused, but that is simply because I am logically extending the realworld address demo that is provided.  Rather than address, you could work the same logic for sales location, distributor area, regional area, etc etc.

Clearly, this would imply a performance hit by requiring point-in-polygon tests when initialising or adding new nodes, but, once cached the display solution would provide a more accurate presentation of the problem domain (i.e. geo-hierarchical aggregation).

As I captioned, this is not an issue, more of a feature consideration but I thought that I would like to get the idea out in the open to potentially create some discussion on the subject area.

Once again,  thank you for providing the community with an excellent and useful plugin.  It is always a pleasure to watch peoples faces the first time it is demonstrated to them - priceless!!

Cheers ...

**Comment by ghybs** [comment]
Hi,

I know this thread is rather old, but I think it is the one @danzel was referring to in #521.

I may be wrong, but it seems that dbkbali's solution seems similar to the one from nerik in #521: different layerGroups (even a MCG in the case of dbkbali's) that add/reveal new data (new MCG) on user click.

Then if my understanding is correct, these 2 threads are referring to the same feature request of clustering based on something else than pixel vicinity. But rather based on externally determined data structure (e.g. a hierarchy or geographical area).

**Comment by danzel** [comment]
Yep, closing this for #521
