### ISSUE TITLE
hasLayer does not detect if non-marker features are there

### ISSUE THREAD

**Issue by erf** [Leaflet/Leaflet.markercluster#325]
Hi, i'm using Leaflet.markercluster to store a set of geojson Point features which are turned into markers (using the pointToLayer function), but they are not found when calling the hasLayer method. I have an html example to demonstrate this if you want. Is this a possible fix or are you just supporting pure L.marker's ? 

For simplicity i've now stored all my geojson features in the markerClusterGroup, but that might be a bad idea for the non-markers ?

**Comment by danzel** [comment]
Closing, no repro.
