### ISSUE TITLE
Reloading markers on iPhone/iPad eventually causes the cluster to stop spiderfying

### ISSUE THREAD

**Issue by sshopov** [Leaflet/Leaflet.markercluster#327]
Hi, I am using markercluster for a small project and loving it. Thank you. 

We've come across a problem on iPhone and iPad devices: if the markers are reloaded multiple times (e.g. markers.clearLayers(); markers.addLayer(someGeoJson); ) eventually the cluster refuses to expand when it reaches the highest zoom level. Everything else still works, but it just won't spiderfy. 

To recreate the issue:
*on an iPhone or an iPad go to: http://dl.dropboxusercontent.com/u/4240950/markercluster_test.html 
*press the clusters until you reach the lowest zoom level 
*press the Reload button a few times
*press the clusters a bit more and zoom around
*eventually the cluster will refuse to spiderfy (pressing Reload won't fix it) 

I'll have a better dig through the source and see if I can find a fix. Any pointers or solutions will be greately appreciated. 

Thanks, 
Stoyan.

**Comment by danzel** [comment]
Example doesn't exist any more.
