### ISSUE TITLE
removeOutsideVisibleBounds error

### ISSUE THREAD

**Issue by jowan** [Leaflet/Leaflet.markercluster#328]
I'm using Leaflet.markercluster as a plugin with Mapbox, so this might be a problem with Mapbox as opposed to Leaflet.js but ..
When I try to use removeOutsideVisibleBounds: false I get an error in mapbox realting to lat/lng.

Perhaps line 867 in leaflet.markercluster-src.js:

if (!this.options.removeOutsideVisibleBounds) {
     return this.getBounds();
}

should be 

if (!this.options.removeOutsideVisibleBounds) {
     return this._map.getBounds();
}

it seems to stop the error. Not sure if it works actually does what is intended though

**Comment by ghybs** [comment]
Hi,

This issue might have been the reason for [commit "Return the whole map bounds instead of our size"](https://github.com/Leaflet/Leaflet.markercluster/commit/ba0c2146cac507a7592a7ddc827e18b662514bda).

Hopefully #573 and PR #575 address this issue.

**Comment by danzel** [comment]
Yeah, closing this one.
