### ISSUE TITLE
Clusters do not stay clustered when marker is on top of eachother.

### ISSUE THREAD

**Issue by webdobe** [Leaflet/Leaflet.markercluster#329]
I cannot reproduce in the examples in the library.  However:
http://wisconsindashboard.org/console/broadband_map

If you Drop some pins specifically the Residential Adequate and Inadequate.  Then zoom all the way in to markers and start zooming out.  You will notice some markers do not collapse back into a cluster.  The issue also seems to be causing a problem where the spiderfy will not work because the stacked markers are no longer clustered. 

I am not receiving any errors from the javascript anytime during the interaction with the map. 

Is there any possible way you can help me debug this issue?  I am not necessarily convinced either way of it being a bug or not with Leaflet.markercluster but maybe you can enlighten me where an issue could be taking place.

Thank you,
-Jesse

**Comment by danzel** [comment]
Example doesn't exist any more. Probably fixed anyway.
