### ISSUE TITLE
Moving markers fails since movement sets marker.latlng to undefined because Leaflet's L.Handler.Drag._onDrag does not provide oldLatLng.

### ISSUE THREAD

**Issue by ane** [Leaflet/Leaflet.markercluster#335]
I am working with Leaflet.markercluster@db142ea6714e45e7dbe8badb7cfa321044c59419 and Leaflet@29678e4f30a98ca0370ee1c8b1b8291a50c8a40d  -- it's the _supposedly_ compabitle branches).

As mentioned here: https://github.com/Leaflet/Leaflet/pull/2412#issuecomment-33549754

The _onDrag does not add the oldLatLng parameter, so it's set as `undefined` when _childMarkerMoved is called and the marker just disappears when marker.update() is called.

If one adds `oldLatLng` to _onDrag, then the marker drag movement doesn't cause errors, but the markers move nowhere.

I changed it so that the oldLatLng parameter is passed as a parmeter in **both** `_onDrag` and `_onDragEnd`, and movement works fine. I will try submitting a PR but I seemed to have done something silly, so it might take a while.

**Comment by BartCorremans** [comment]
Did you ever get around to submitting a PR for this? If not, do you have any working code that fixes this?

**Comment by ane** [comment]
Nope. Never got anything to work. Had to use hacky layer stuff to get around things. I don't do stuff with Leaflet anymore sorry :(

**Comment by danzel** [comment]
Dragging works correctly with the latest releases
