### ISSUE TITLE
Leaflet 0.8-dev

### ISSUE THREAD

**Issue by GilJ** [Leaflet/Leaflet.markercluster#338]
The leaflet master branch is currently at version 0.8-dev. I was wondering if there's any plans for supporting this master branch?

I'm getting the following error currently:

``` javascript
> L.version
"0.8-dev"
> var markers = new L.markerClusterGroup()
TypeError: Cannot read property 'trim' of undefined
```

The used leaflet 0.8-dev version is from commit 3ded683.
I tried both with the master branch, and leaflet-master branch from Leaflet.markercluster

Thanks in advance

**Comment by meliborn** [comment]
Same error, even after ```jake```

**Comment by zzhouag** [comment]
I also got this error, I am using master version of leaflet 0.8-dev and leaflet-master version of cluster.

**Comment by Eschon** [comment]
I use markercluster with leaflet 0.8-dev and it works fine.

Are you sure you used the leaflet-master branch?
Did jake complete successful or did it throw errors?
Are you sure you copied the built files into your project after running jake?

**Comment by zzhouag** [comment]
I only build leaflet 0.8-dev myself, and I use 'leaflet.markercluster.js' directly from the download package.
I succeed build leaflet-src.js and leaflet.js in dist folder and I'm sure copy these two files to my project...
Need I also build leaflet-master version of markercluster by myself? But there are already build files inside the dist folder of download package.

**Comment by Eschon** [comment]
Those files do not work you have to build markercluster too.

**Comment by zzhouag** [comment]
Hi, I build leaflet-master version of markercluster myself and it skip this error, but when I drag the marker, new error appear as the attachment pictures
![screen shot 2015-05-20 at 4 16 06 pm](https://cloud.githubusercontent.com/assets/3379761/7721606/9381c71e-ff0b-11e4-91cd-3f24b95d177d.png)
![screen shot 2015-05-20 at 4 15 57 pm](https://cloud.githubusercontent.com/assets/3379761/7721607/9389a5ce-ff0b-11e4-8ea7-a5dc56cad1dd.png)
