### ISSUE TITLE
Adding a single marker, with a custom count

### ISSUE THREAD

**Issue by rrooij** [Leaflet/Leaflet.markercluster#351]
Markers below a certain zoom level are clustered by the server in my case, and markers above a certain zoom by the client. I already saw this issue and implemented Danielku15's method, but it didn't work out.

https://github.com/Leaflet/Leaflet.markercluster/issues/217

It works fine, except that it displays a single marker when there are no nearby clusters. I tried to fix this issue by myself, but I'm having a hard time doing so. Any plans on adding the ability to make a custom cluster count? So that the MarkerClusterer doesn't display a single marker instead?

There are other cases when this can be of use. Also for client side purposes e.g. having a own client side clustering implementation, or other scenarios where the clusters are known before adding them to the MarkerGroup.

Thanks in advance!

**Comment by dewdad** [comment]
Currently my team and I are also facing the exact same issue. Wherein we need to render server clusters that are computed by density on a grid and then sent to the client with a count field of >0. However the clustering on the server does not concern itself with rendering on the viewport as far as overlaying clusters and markers, so we need to upgrade that view with clustering on the client. Has anyone found a streamlined implementation for this. Has this feature been added somewhere.
