### ISSUE TITLE
Clustering a large number of points

### ISSUE THREAD

**Issue by vadvv** [Leaflet/Leaflet.markercluster#356]
I'm having a problem clustering a large number of points (my current set is 40K+ points, but I've even gone down to about 15K points). It takes very long to cluster, and then when zooming in/out it takes similar time for the layer to render. Most of the time the browser (in my case Chrome) asks to kill the tab.

I should add that to overcome this, I had decided to show the data as a heat map until a zoom level is reached, after which I thought I could show the cluster with the flag removeOutsideVisibleBounds set to true, but that didn't seem to help either and resulted in the same delay.

Is anyone else experiencing this issue?

**Comment by dud3** [comment]
@danzel I have the same issue, using the angular directive for Leaflet, just like @vadvv and it takes a lot of time to in zoom/in-out.

Example: http://dev.yachtingsbest.com/
Code: http://dev.yachtingsbest.com/src/app/controllers/spotsCtrl.js

@vadvv did you find any solution to this one ?

**Comment by vadvv** [comment]
Sorry dud3. No luck yet. I ended up violating DI and using the original library since the number of points I was working with in the worst case scenario was in the 50K to 200K range.
