### ISSUE TITLE
Add chunkedLoading documentation

### ISSUE THREAD

**Issue by danzel** [Leaflet/Leaflet.markercluster#357]
As used in http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.50000.html

**Comment by ErwanLent** [comment]
"... markers are processed for a maximum of ~200 milliseconds and at the end of each interval, a 50 milliseconds delay is given back to the browser. This results in more responsive maps especially on older browsers like IE8."

https://www.mapsmarker.com/2014/01/30/pro-v1-5-5-with-loading-progress-bar-for-markerclusters-is-available/
