### ISSUE TITLE
Removing cluster layer from map during zoom crashes

### ISSUE THREAD

**Issue by grantlucas** [Leaflet/Leaflet.markercluster#36]
Calling removeLayer() on the map to remove the cluster marker layer causes the crash when the cluster tries to merge split clusters.

Right now, due to the way we have our data setup and the amount of markers being dealt with, on every zoom end or drag end, the markers are re-retrieved and the clusterGroup is recreated. This works fine zooming in and out _until_ the cluster group is removed during a zoom animation. 

On my map, I don't show the cluster group when the map is below zoom level 5. When I go from 4, showing clusters, to 5, now showing none, the map crashes when it tries merge split clusters.

Error shown for line 252 of the -src file

```
Uncaught TypeError: Cannot read property '_zoom' of null
```

**Comment by kayoshi** [comment]
Hi! Getting error when removing unused layers:
``` this._map._mapPane.className=this._map._mapPane.className.replace(" leaflet-cluster-anim","") ```

My code:
```
if (map.hasLayer(layer))
    map.removeLayer(layer);
```

**Comment by weslleymart16** [comment]
Good afternoon, I would like to know if it is possible to do the opposite, I want the cluster to appear only when it is at maximum zoom, less than that, only the marking points appear.
