### ISSUE TITLE
Sum of  values of a point in a cluster 

### ISSUE THREAD

**Issue by mironk** [Leaflet/Leaflet.markercluster#363]
Hi
is there a way to count and show in the icon the Sum of the values per point instead of count of child's
ex:
for the data -
[-37.8211946833, 175.2213655333, "1"],
[-37.8209458667, 175.2214051333, "5"],
[-37.8208292333, 175.2214374833, "7"],
[-37.8325816, 175.2238798667, "537"]

=> the values on cluster icon for those points will show 550 (instead of 4)

**Comment by pitKay** [comment]
Hello danzel,

I don't have any experience with JS. Can you please help me how do I implement the above function in R using leaflet?

Specifically I'm struggling to understand how to record a value against the marker in the cluster.

**Comment by IvanSanchez** [comment]
@pitKay  Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
