### ISSUE TITLE
layeradd events not fired anymore

### ISSUE THREAD

**Issue by brunob** [Leaflet/Leaflet.markercluster#368]
Hi, i was using layeradd event like this (markerCluster is an instance of L.MarkerClusterGroup) and layeradd event is never called anymore when i had markers to my cluster : 

``` js
me.markerCluster.on('layeradd', function (e) {
 // never called
});

me.markerCluster.on('clusterlayeradd', function (e) {
 // never called
});

me.markerCluster._featureGroup.on('layeradd', function (e) {
 // this one is called
});
```

So basically, i have to listen to the event fired on markerCluster._featureGroup instead of markerCluster, i think this change d47a3140ca370361264e66397911cd2d982c4b67 is the origin of the "bug".

Is there a better way to lister to layeradd event like it was possible before ?

**Comment by danzel** [comment]
Closing as a dupe of #647
