### ISSUE TITLE
Turn off zoom animation 

### ISSUE THREAD

**Issue by mmichelli** [Leaflet/Leaflet.markercluster#382]
I would like to turn off the zoom animation, as it's slow in mobile devices.

**Comment by FractalizeR** [comment]
Adding such a feature would be awesome. I am also looking for a convenient way to disable zoom animation as I perform ajax request and re-add markers to map anyway.

**Comment by neffritt** [comment]
L.DomUtil.TRANSITION disables also panTo() and fitBounds() animation of Leaflet. Is there a way to disable exactly only Markercluster animations?

**Comment by ghybs** [comment]
Hi,

You could force non-animated MarkerClusterGroups by changing the condition there:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L923

If this is an option for you, you could also check this different clustering library, which does not animate: [PruneCluster](https://github.com/SINTEF-9012/PruneCluster)

**Comment by FractalizeR** [comment]
@ghybs Modifying library source code should be reserved as a last solution when all else fails ;)

**Comment by ghybs** [comment]
It actually looks like @PikachuEXE tried to implement this functionality as an option (issue #348, PR #352, which has not been merged).

Instead of checking which function to use at call time, it should be quite easy to reference the appropriate ones at group initialization time?

**Comment by Kambyses** [comment]
Animate option is cool and everything, but i needed to disable animations temporarly (when calling map.fitBounds for example, the animation made markers to slide on the map, which i didn't like).
So this is what i did:
```
enableMarkerClusterAnimation: function () {
  this._animationStart = this._withAnimation._animationStart;
  this._animationZoomIn = this._withAnimation._animationZoomIn;
  this._animationZoomOut = this._withAnimation._animationZoomOut;
  this._animationAddLayer = this._withAnimation._animationAddLayer;
},

disableMarkerClusterAnimation: function () {
  this._animationStart = this._noAnimation._animationStart;
  this._animationZoomIn = this._noAnimation._animationZoomIn;
  this._animationZoomOut = this._noAnimation._animationZoomOut;
  this._animationAddLayer = this._noAnimation._animationAddLayer;
}

```
Note: `zoomToBounds` is my implematation of `fitBounds` that returns a promise
```
layer.disableMarkerClusterAnimation();
map.zoomToBounds(bounds).then(function () {
  layer.enableMarkerClusterAnimation();
});
```
