### ISSUE TITLE
Dynamic maxClusterRadius

### ISSUE THREAD

**Issue by rwwagner90** [Leaflet/Leaflet.markercluster#392]
I have a slider that I have successfully hooked up and as I slide it I set layer.options.maxClusterRadius = sliderValue, which seems to work okay, but then the cluster layer does not seem to change at all. Is there a way to have it recognize this new value without removing the entire layer, changing maxClusterRadius, and adding a new layer with the updated value? It would be great if I could just update this on the fly like I am trying to do.

**Comment by namezero** [comment]
how to re-cluster amm tue markers? what method i have to call ? i 'am using master brunch

**Comment by rwwagner90** [comment]
@namezero you have to remove the layer, create a new layer, and add all the markers again. There is no way to recluster on the fly. Right @danzel?

**Comment by danzel** [comment]
Correct.

**Comment by guyzi** [comment]
It says in the docs
>maxClusterRadius: The maximum radius that a cluster will cover from the central marker (in pixels). Default 80. Decreasing will make more, smaller clusters. You can also use a function that accepts the current map zoom and returns the maximum cluster radius in pixels.

but looking at the source it doesn't seem to work when provided with a function. So I guess @rwwagner90 is the way to go?

**Comment by rwwagner90** [comment]
@guyzi yes, I would just calculate the cluster radius yourself, delete everything, change the number, and add it all back.

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L749-L754
This doesn't make it dynamic however

**Comment by thadk** [comment]
This "pregenerate clusters for each zoom level with a function" feature is one of things added in 0.4.0-hotfix -- make sure you are not using vanilla 0.4.0 on a place like https://cdnjs.com/#q=leaflet.markercluster New release?

**Comment by DarkForceOne** [comment]
I think it can be done this way:

    //This function will be assigned as radiusFn(zoom) in the function _generateInitialClusters 
    var GetRadius = function (zoom) { 
        //do something with the passed zoom level, for example:
        return 250 - zoom * 10;
    }

    //pass GetRadius to maxClusterRadius
    var myClusterGroup = new L.MarkerClusterGroup({maxClusterRadius: GetRadius});

**Comment by joshting** [comment]
I am investigating whether to rebuild an existing application (using OpenLayers) with leaflet.  The markers or features in the application are actually moving in real time.  In OpenLayers, clustering can occur in real time because it is dynamically styled using CSS and javascript.  So a marker can move in or out of a cluster and the cluster updates.  It would be great if leaflet or any of its plugins can support this.

**Comment by danzel** [comment]
leaflet.markercluster supports moving markers when used with leaflet 1.0.0-beta2.

Dynamic maxClusterRadius is unlikely to ever happen in this plugin sorry.
It is supported in PruneCluster however: https://github.com/SINTEF-9012/PruneCluster

**Comment by Tim-mhn** [comment]
> 
> 
> I think it can be done this way:
> 
> ```
> //This function will be set as radiusFn(zoom) in the function _generateInitialClusters 
> var GetRadius = function (zoom) { 
>     //do something with the passed zoom level, for example:
>     return 250 - zoom * 10;
> }
> 
> //pass GetRadius to maxClusterRadius. 
> var myClusterGroup = new L.MarkerClusterGroup({maxClusterRadius: GetRadius});
> ```

Works perfectly, thanks
