### ISSUE TITLE
add main assets in bower.json (for rails-assets.org support)

### ISSUE THREAD

**Issue by mikeatlas** [Leaflet/Leaflet.markercluster#394]
I pull in bower assets into my rails app using [rails-assets.org](rails-assets.org). This takes bower packages and transforms them into gems that set appropriate vendor asset paths while keeping your own application's vendor directory nice and clean.

With markercluster, I get this error after running `bundle install` and this in my Gemfile:

```
gem 'rails-assets-leaflet.markercluster'
```

```
Post-install message from rails-assets-leaflet.markercluster:
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/Leaflet/Leaflet.markercluster
```

An example of another bower package taking care of this is here:
https://github.com/winmarkltd/BootstrapFormHelpers/issues/218

Thanks!

**Comment by stephan-nordnes-eriksen** [comment]
Having this issue as well. I added this to my local copy:

    "main": [
     "dist/leaflet.markercluster.js",
     "dist/leaflet.markercluster-src.js",
     "dist/MarkerCluster.css",
     "dist/MarkerCluster.Default.css"
    ],

Which seems to work. Any update on when a fix is out?

**Comment by mikeatlas** [comment]
@stephan-nordnes-eriksen The original plugin author seems pretty reluctant on making any serious changes to this plugin... if you see all the PRs and open bugs... the accepted ones are minor and functionality improvement PRs are often left around for long awhile. I have a simple [PR open for at least 6 months now](https://github.com/Leaflet/Leaflet.markercluster/pull/395). In my case I got tired of waiting and am using a forked+rawgit version of my PR within my app in the "indefinite interim" (le sigh).

If I had to guess, a new build with a fix for the `bower.json` main assets might come out around the same time as [Leaflet-1.0-beta1](https://github.com/Leaflet/Leaflet/milestones/1.0-beta1). It's a shame this is a "core" Leaflet plugin but the original author is sleepy about making any new serious improvements/changes.

**Comment by danzel** [comment]
Sick burn

**Comment by mikeatlas** [comment]
io.js vs Node.js?

You either don't have bandwidth or interest to focus on it anymore from the crowd's perspect. I'm calling a spade a spade. 353 forks to 1049 Stars tells that story objectively. You're the 99% contributor besides Vladimir, and a few PRs over the years. 

It's an endemic problem with GitHub model and popular repos and open source in general that gets neglected or partially neglected by their original author. 

I don't blame you @danzel, at some point other forks with a new name will take the load off your back for you and give it a new name and new life.

**Comment by danzel** [comment]
For many PRs that get sent the author of them doesn't care enough about them to get them merged.
I've bumped yours now, I think I missed it. Fix that up and I'll merge it. Thanks!

**Comment by mikeatlas** [comment]
Nice blog post :smirk: - this is a good read too lol

http://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar#Lessons_for_creating_good_open_source_software 

* When you lose interest in a program, your last duty to it is to hand it off to a competent successor.
* Treating your users as co-developers is your least-hassle route to rapid code improvement and effective debugging.
* Release early. Release often. And listen to your customers.

**Comment by danzel** [comment]
lol stalker ;)

**Comment by mikeatlas** [comment]
Amusing :) I don't know how I can send a PR for including `bower.json` in your next tagged release, so I'll just hope this distraction serves as a gentle prodding.

**Comment by danzel** [comment]
It is already in master, so when the next release happens (I've been waiting for the leaflet version) it'll be included.

**Comment by stephan-nordnes-eriksen** [comment]
I'm curious. Is it not possible to release a hotfix to the already released code, and do the more major update when the next leaflet is out? This is a breaking bug for people now. However easy to fix for the users, it is bad to have broken versions as the current release.

**Comment by danzel** [comment]
Does rails-asset just build automatically from tags?
I have no idea how it works.

As it is something I haven't set up or support, I don't really consider it a breaking bug. It has never worked through there AFAICT.

**Comment by mikeatlas** [comment]
@danzel So long as you're sticking to semantic versioning, you don't need to worry if downstream tools can't handle your pre-release-tagged release. It would be *their* problem for not handling pre-release semver packages incorrectly. Dooo itt. Make a tagged **v0.4.0-hotfix.1** build. All of us that reference version numbers for your plugin will still move to 0.4.1 safely when you release it, provided we are specify that we are not locking ourselves in at ~> 0.4.0-beta.1.

References or evidence that you can [Trust Me](http://aviationhumor.net/wp-content/uploads/2014/10/trust-me-im-an-engineer.jpg):
* Bower does not automatically treat prerelease-tagged versions as automatic-compatible newer versions https://github.com/bower/bower/issues/782 
* Npm supports prerelease tags: https://github.com/npm/node-semver#prerelease-tags
* Rails-Assets supports prereleases: https://github.com/rails-assets/rails-assets/issues/201

**Comment by danzel** [comment]
Ok, tagging now.... *hold breath*

**Comment by danzel** [comment]
Tagged:
https://github.com/Leaflet/Leaflet.markercluster/tree/v0.4.0-hotfix.1

**Comment by mikeatlas** [comment]
Woo. Almost... bower is stating: `Version declared in the json (0.4.0) is different than the resolved one (0.4.0-hotfix.1)

```
$ bower info leaflet.markercluster\#0.4.0-hotfix.1
bower leaflet.markercluster#0.4.0-hotfix.1       not-cached git://github.com/Leaflet/Leaflet.markercluster.git#0.4.0-hotfix.1
bower leaflet.markercluster#0.4.0-hotfix.1          resolve git://github.com/Leaflet/Leaflet.markercluster.git#0.4.0-hotfix.1
bower leaflet.markercluster#0.4.0-hotfix.1         download https://github.com/Leaflet/Leaflet.markercluster/archive/v0.4.0-hotfix.1.tar.gz
bower leaflet.markercluster#0.4.0-hotfix.1          extract archive.tar.gz
bower leaflet.markercluster#0.4.0-hotfix.1         mismatch Version declared in the json (0.4.0) is different than the resolved one (0.4.0-hotfix.1)
bower leaflet.markercluster#0.4.0-hotfix.1         resolved git://github.com/Leaflet/Leaflet.markercluster.git#0.4.0-hotfix.1

{
  name: 'leaflet.markercluster',
  version: '0.4.0-hotfix.1',
  homepage: 'https://github.com/Leaflet/Leaflet.markercluster',
  authors: [
    'Dave Leaver <danzel@localhost.geek.nz>'
  ],
  description: 'Marker Clustering plugin for Leaflet.',
  main: [
    'dist/leaflet.markercluster-src.js',
    'dist/MarkerCluster.css',
    'dist/MarkerCluster.Default.css'
  ],
  license: 'MIT',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'example',
    'spec',
    'test',
    'tests'
  ],
  dependencies: {
    leaflet: '>= 0.7.0'
  }
}
```

**Comment by mikeatlas** [comment]
Well, it seems Rails-Assets doesn't like the pre-release tagged number, but that's not your problem. I'll go knocking on their door for now. Perhaps they only expect X.Y.Z.qqqq for pre-release tags. Will re-open if there's something I missed.

```
rake aborted!
There was a ArgumentError while loading rails-assets-leaflet.markercluster.gemspec: 
Malformed version number string ~> 0.4.0.hotfix.1 from
  /tmp/d20150327-7368-ighaep/rails-assets-leaflet.markercluster.gemspec:8:in `block in <main>'
```

**Comment by danzel** [comment]
Updated the version in bower.json too which might help.

**Comment by mikeatlas** [comment]
@danzel just FYI, downstream Rails-Assets DID break and it was THEIR fault :+1: and it's now fixed to support correct semver. Check it out. https://github.com/rails-assets/rails-assets/issues/246#issuecomment-86817600

Thanks for pulling the trigger on the hotfix build.

**Comment by danzel** [comment]
:+1:
