### ISSUE TITLE
clusteradd and clusterremove events

### ISSUE THREAD

**Issue by RobbieTheWagner** [Leaflet/Leaflet.markercluster#402]
I am trying to execute some logic when a few markers are sucked into a cluster, and then I want to do the inverse of that, when the markers become unclustered and just separate markers again. I assumed I would be able to use clusteradd and clusterremove, since plain markers have an add and remove event, but it doesn't seem to work. Should it be working or is there another way to do this that you can think of?

To elaborate, I have some markers that are in the center of geoJson shapes. So whenever those markers become part of a cluster, I also want the shape to get sucked into the cluster, then when unclustered, I need the geoJson shape to come back.

I've been poking around in the source code, trying to figure out how to do this, and I came across this:

``` js
//Don't cluster non point data
        if (!layer.getLatLng) {
            this._nonPointGroup.addLayer(layer);
            return this;
        }
```

Is it possible to have other layers clustered? This looks by the comment like it is keeping anything other than markers from being clustered?

Alternatively, if you could point me to which section of the code is executed when points are sucked into a cluster, and which section of code executes when the cluster is unclustered, I'd be glad to fork and do a PR with another two parameters allowing the user to pass in functions that will be called when points are sucked into a cluster, and when points are separated back out of a cluster.

**Comment by bre7** [comment]
Workaround to cluster Polygons (https://stackoverflow.com/a/45813585/2124535) using [Turf.js' centroid](http://turfjs.org/docs/#centroid)

```js
import centroid from "@turf/centroid"

L.Polygon.addInitHook(function() {
    const auxCentroid = centroid(this.toGeoJSON())
    // FIXME Not sure why but coords are mixed up
    this._latlng = L.latLng([auxCentroid.geometry.coordinates[1], auxCentroid.geometry.coordinates[0]])
})

// Provide getLatLng and setLatLng methods for
// Leaflet.markercluster to be able to cluster polygons.
L.Polygon.include({
    getLatLng: function() {
        return this._latlng
    },
    setLatLng: function() {} // Dummy method.
})
```
