### ISSUE TITLE
Changing Icon Titles

### ISSUE THREAD

**Issue by slauyama** [Leaflet/Leaflet.markercluster#404]
Hi 

I made a custom icon function that would display different text based on a dropdown value. The problem is that once an icon was created it would not show new text when the dropdown value changed. So once I was in a certain view the icon would be set and it would not update.

I ended up going through the markercluster code and got it to work by commenting out "this._iconNeedsUpdate = false" in the createIcon function
```
createIcon: function() {
            if (this._iconNeedsUpdate) {
                this._iconObj = this._group.options.iconCreateFunction(this);
                // this._iconNeedsUpdate = false;
            }
            return this._iconObj.createIcon();
        },
```

This works fine for me but I thought it might be nice to have a property that you pass into MarkerCluster that would allow for always updating. Or maybe adding a function that updates all the icons when needed?

**Comment by ghybs** [comment]
Hi,

Old issue, but I think is also in the use case of PR #564.
