### ISSUE TITLE
Bower package is very old and missing many features

### ISSUE THREAD

**Issue by tom-james-watson** [Leaflet/Leaflet.markercluster#416]
If you install through bower you are provided with an extremely out of date version of the package. I'm specifically missing the chunkedLoading stuff.

Can you please release an update version of the package by incrementing the bower version number and creating an appropriate tag?

Thanks and keep up the good work!

**Comment by slopen** [comment]
what version of leaflet we are waiting for? currently it's 7.3, but still bower package is lacking chunkedLoading.

**Comment by danzel** [comment]
A newer version than 0.7.3, it's been ages coming.... soon (tm)
