### ISSUE TITLE
Markercluster doesn't appear in order in the Layers control as an Overlay

### ISSUE THREAD

**Issue by DaveF63** [Leaflet/Leaflet.markercluster#422]
Hi
I have various layer groups, but only 'PubsGroup' is created with markercluster. As you can see in the overlays list it's at the bottom, but when I run the code it puts it at the top of the Layer control. If I create Pubsgroup as a standard LayerGroup it remains in its place at the bottom.

Is there solution for this? 

Here's snips> of my code:

```javascript
		var PubsGroup = L.markerClusterGroup({ disableClusteringAtZoom: 18, maxClusterRadius: 40});
		
		L.geoJson(Pubs,{
			fillColor: "Lightblue ", // style for cafe mapped as polygons
			color: "lightblue",
			weight: 3,
			opacity: 1,
			fillOpacity: 0.2,			
			
			pointToLayer: function (feature, latlng) {
				if (feature.properties.website !== undefined) {			
					popupContent = '<a href=' + feature.properties.website + ' target="_blank">' + feature.properties.name + '</a>'
					} else {popupContent = feature.properties.name}			
				return L.marker(latlng, { // Co-ordinates
					icon: PubIcon,
					title: feature.properties.name // Hover over text
					} 
				).bindPopup(popupContent)
			}, // pointToLayer
		}).addTo(PubsGroup);
snip>
		//List of all the Overlays layergroups
		var overlays = {
			"Two Tunnels NCN 244": TwoTunnelsGroup,
			"Two Tunnels Circuit": TTCircuitGroup,
			"BikeShops": BikeShopGroup,
			"Cafes":CafesGroup,
			"Parks":ParksGroup,
			"Pubs":PubsGroup,
		};
		
		// Loads the different base layer maps & overlays 
		L.control.layers(baseLayers,overlays,{autoZIndex:true}).addTo(map);		
			
		map.addLayer(PubsGroup);	
		map.addLayer(BikeShopGroup);	
		map.addLayer(TTCircuitGroup); // displays two groups (ways & arrows)...
         map.removeLayer(TTCircuitArrowGroup); // but removes arrows as initial zoom is ~17  
```

**Comment by ghybs** [comment]
Hi,

Apologies again for commenting an old thread...

Here is the reason for this behaviour:
- Layers Control uses layers' stamp (https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L118-L120).
- It re-builds the overlays list each time you add a new one, order is based on id (stamp) (https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L135-L140).
- Groups' stamp can be set any time before:
  - LayerGroup has no stamp until Layers Control sets it.
  - FeatureGroup gets stamped on first added marker (https://github.com/Leaflet/Leaflet/blob/master/src/layer/FeatureGroup.js#L13 which ends up in https://github.com/Leaflet/Leaflet/blob/master/src/core/Events.js#L55, it is somehow similar in Leaflet 0.7).
  - MarkerClusterGroup gets stamped at initialization (https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L49)

Fork of DaveF63's last fiddle to highlight the above behaviour: http://jsfiddle.net/Louh70wa/1/

Forcing a predefined list order in Layers Control could be done by stamping the groups in advance on purpose: http://jsfiddle.net/Louh70wa/2/

**Comment by ghybs** [comment]
Well, I actually overlooked bullet 2: this ordering still depends on the JavaScript engine good will rather than a spec, so even stamping in advance to try forcing the order may not give the expected result.

Looks like there is no other choice than customizing the Layers Control implementation if we really want to ensure a given order.

**Comment by danzel** [comment]
Thanks for looking in to this @ghybs

**Comment by kirantpatil** [comment]
Hi, how to order the markers, even though I added them serially it is not getting displayed in order.

The markers are not arranged like 1,2,4,5,6,7 but 1,2,7,6,5,4. Please find the below screenshot.

How to resolve it ? 

![screenshot-2017-12-6 containermon](https://user-images.githubusercontent.com/1178055/33659699-3218b3f0-daa7-11e7-93b7-caeb8c59ba04.png)

```

 L.marker(cont_ll_1, {
                    icon: new L.AwesomeNumberMarkers({
                      number: position2,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + device.name).openTooltip();

                       L.marker(cont_ll_2, {
                    icon: new L.AwesomeNumberMarkers({
                      number: position1,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + name1).openTooltip();

                       L.marker(cont_ll_4, {
                    icon: new L.AwesomeNumberMarkers({
                      number: position4,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + name4).openTooltip();

                       L.marker(cont_ll_5, {
                    icon: new L.AwesomeNumberMarkers({
                      number: position5,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + name5).openTooltip();


                       L.marker(cont_ll_6, {
                    icon: new L.AwesomeNumberMarkers({
                      number: position6,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + name6).openTooltip();

```
