### ISSUE TITLE
GeoJSON markers do not cluster if geometry is Multipoint

### ISSUE THREAD

**Issue by tomchadwin** [Leaflet/Leaflet.markercluster#425]
When trying to cluster a GeoJSON layer, it works if the features have the geometry type "Point", but not if they are "Multipoint". Is this intentional?

I've come across this issue because QGIS 2.4's function QgsVectorFileWriter.writeAsVectorFormat() wrote points out in GeoJSON as geometry type "Point", but 2.6 seems to write out as type "Multipoint". I don't know why this has changed, and have asked on qgis-developer.

This issue relates to the qgis2leaf plugin.

**Comment by sajanojha** [comment]
I know this issue is closed.
But is there any Workaround. 
I am also stuck with this problem.
Thanks

**Comment by cosme-benito** [comment]
Probably a bit late but I bumped into this issue today.

Instead of using the addLayer(geojsonLayer) function I extracted the array of Markers from the geojsonLayer and then used the addLayers(markersArray) function instead. Works alright, but runs very slowly for 100k points :(

**Comment by danzel** [comment]
Try the chunked loading option, I can't remember if it is in master or
leaflet-master branch. It won't speed up the loading, but it won't lock the
browser when it happens
