### ISSUE TITLE
Double click on cluster performs additional map zooming on IE8/9

### ISSUE THREAD

**Issue by hupf** [Leaflet/Leaflet.markercluster#428]
This issue is reproducable using IE8 or IE9 and the [realworld example](http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html) online.

Initially the map looks like this:

![ie8-initial](https://cloud.githubusercontent.com/assets/66047/5297359/70dbba3e-7bae-11e4-8e53-a670e7e409f2.png)

When single clicking on the orange cluster, it does a `zoomToBounds` as expected:

![ie8-singleclick](https://cloud.githubusercontent.com/assets/66047/5297378/a4d37638-7bae-11e4-9244-222740ff9ce1.png)

But, when double clicking the cluster, it does an additional zooming, as if one double clicked on the map:

![ie8-doubleclick](https://cloud.githubusercontent.com/assets/66047/5297389/bf1f5f2a-7bae-11e4-8e68-60839e6887bc.png)

This behavior does not happen with IE10, IE11, Chrome or Firefox.

**Comment by danzel** [comment]
I don't care about IE version that microsoft no longer supports any more.
