### ISSUE TITLE
makercluster, geojson and control.layers

### ISSUE THREAD

**Issue by bsuttor** [Leaflet/Leaflet.markercluster#432]
Hello,
First, thank you for plugin, I already use it and it works fine.

But not in this case : 
I use geojson and control layers on my website, and I try to add markercluster plugin.

But it seems you can not 'link' control layers with a "markercluster geojson". The overlays are not checked on load, when I click on overlays, markers are added, but they are not "marckercluster"...

An example :
http://jsfiddle.net/cbwue7ga/5/

Did you have an idea how I can control some markercluster geojson ?

Regards,

**Comment by danzel** [comment]
Manually. If you search through the issues there should be one about using layers control with markercluster.

**Comment by reyemtm** [comment]
http://jsfiddle.net/cbwue7ga/7/

**Comment by danzel** [comment]
Lol, yeah, that'd do it. :)
