### ISSUE TITLE
leaflet MarkerCluster plug in documentation

### ISSUE THREAD

**Issue by 10mirkuzz** [Leaflet/Leaflet.markercluster#434]
Hi,
could you kindly provide me the intuitively description of the marker cluster algorithm? does it rely on a well-known algorithm? I am trying to describe it in my thesis work. Thank you

**Comment by danzel** [comment]
It uses naive greedy clustering.
Whenever a marker, started at the bottom zoom level and going up we look for an existing marker or cluster that is within the cluster distance.
If one is found the marker is added to that cluster (or forms a new cluster with that marker) and inherits the parent clusters of the already existing clusters above.

Probably reading the _addLayer code is the right place to look, it is called to add every marker to the ClusterGroup.
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L770

Hope that helps!
