### ISSUE TITLE
Not working correctly in Joomla site

### ISSUE THREAD

**Issue by ramblerswebs** [Leaflet/Leaflet.markercluster#439]
I have used this great facility in two sites. One is stand alone and works great.
The other is a joomla site and while cluster works there is one feature that does not. When I hover over a cluster it does not show the bounds of the cluster.
I assume that there is some interaction with Joomla. How does the hover work? Is it in the JS code?
The map is at
http://www33.theramblers.org.uk/index.php?option=com_content&view=article&id=9:map-with-markers-for-each-walk&catid=12&Itemid=191
Any help gratefully received.

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L652-L657 GLHF

**Comment by ramblerswebs** [comment]
Thanks for that , very helpful.
The code is going into  _showCoverage: to display the bounds. The var this._shownPolygon looks fine but nothing is displayed. Not sure where to go from here. The page in question is
http://new.derbyramblers.org.uk/future-walks/map-of-walk-locations.html
PS great extension ot Leaflet. Also love leaflet
