### ISSUE TITLE
CommonJS support?

### ISSUE THREAD

**Issue by MandarinConLaBarba** [Leaflet/Leaflet.markercluster#441]
I didn't see anything in the issue list about this - are there plans/hopes/aspirations for support for CommonJS-style module definition? It seems odd to me that Leaflet core supports CommonJS but this plugin doesn't.

**Comment by danzel** [comment]
That would be part of updating for the next leaflet release I believe?

**Comment by MandarinConLaBarba** [comment]
OK, well I'd be happy to assist in converting stuff to UMD-style definition...where can I go to see what efforts are in progress on that front?

**Comment by danzel** [comment]
There is a branch up here
https://github.com/Leaflet/Leaflet.markercluster/tree/leaflet-master
Send a PR against that branch and I'll take a look :)

**Comment by MandarinConLaBarba** [comment]
OK sweet

**Comment by MandarinConLaBarba** [comment]
So I'm getting an exception: `TypeError: undefined is not a function` here:

https://github.com/Leaflet/Leaflet.markercluster/blob/leaflet-master/src/MarkerClusterGroup.js#L46

I checked the `leaflet` version that came down w/ `npm install` and it indeed doesn't appear to have that function in the `L.FeatureGroup` class. What am I doing wrong?

Also, should I open a separate issue?

**Comment by danzel** [comment]
You'll need to use the master version of leaflet, the npm one will be the current stable.

**Comment by MandarinConLaBarba** [comment]
k thanks

**Comment by MandarinConLaBarba** [comment]
Should there be a single exports (the `MarkerClusterGroup` class) or do we want to expose all the dependencies as well?

Basically:

```
var MarkerClusterGroup = require('leaflet.markercluster');
```

or

```
var MarkerClusterGroup = require('leaflet.markercluster').MarkerClusterGroup;
var MarkerCluster = require('leaflet.markercluster').MarkerCluster;
//...
```

**Comment by danzel** [comment]
We probably need to expose both so the user can see if a marker is a MarkerCluster?

**Comment by MandarinConLaBarba** [comment]
ok

**Comment by MandarinConLaBarba** [comment]
I'm showing 21 failing tests on `leaflet-master` is that 'normal' ?

PhantomJS 1.9 (Mac): Executed 91 of 91 (21 FAILED) (0.358 secs / NaN secs)

**Comment by danzel** [comment]
Hrm, didn't know that, they will definitely need fixing!

**Comment by MandarinConLaBarba** [comment]
OK, wasn't sure if I had some environmental issue..

**Comment by rhewitt22** [comment]
@MandarinConLaBarba were you able to make any progress on this?  I'm using browserify to put together a project and I'm stumped as to how to integrate this plugin.

@danzel

**Comment by rhewitt22** [comment]
Workaround:
```
global.L = require('leaflet');
require('leaflet.markercluster');
```

**Comment by rhewitt22** [comment]
This seems to work:

`npm i --save https://github.com/Leaflet/Leaflet.markercluster.git#v1.0.0-beta.2.0`

```
var L = require('leaflet');
require('leaflet.markercluster');
```

**Comment by crudbetter** [comment]
Looking at the source `require('leaflet')` sets both `module.exports = L` and `window.L = L`. Which is why `require('leaflet.markercluster')` works (it uses `window.L`).

Ideally I would prefer to use `require('leaflet').noConflict()` to get rid of setting `window.L`. 

At the moment I cannot then find a way of "passing" `L` to `leaflet.markercluster`. Have tried `browserify-shim` so far without success.

**Comment by crudbetter** [comment]
In the end I pragmatically decided to stop fighting against the tide.

I uninstalled both `leaflet` and `leaflet.markercluster` from my `package.json` and hence `node_modules` folder.

I download the libraries from unkpg.com and saved them to a `vendor` folder.

I added the following to my `index.html`:

```
<script src="vendor/leaflet_1.0.2/leaflet.js"></script>
<script src="vendor/leaflet.markercluster_1.0.0/leaflet.markercluster.js"></script>
<link href="vendor/leaflet_1.0.2/leaflet.css" rel="stylesheet" />
```

I still used `browserify-shim`, but only to make the global `L` set on `window` require-able. In my `package.json`:

```
"browserify-shim": {
   "leaflet": "global:L"
 }
```

Then in source files `var L = require('leaflet')`. Note no `require('leaflet.markercluster')`.

This way, if Leaflet and this awesome Marker Cluster plugin migrate to CJS, I don't have to go round amending multiple source files.

**Comment by PikachuEXE** [comment]
I change the source to be like:
```js
(function(root, factory){
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['leaflet', window.document], factory);
  }
  else if (typeof module === 'object' && module.exports) {
    // Node/CommonJS
    var L = require('leaflet');
    module.exports = factory(L, window.document);
  }
  else {
    // Browser globals
    factory(root.L, root.document);
  }
}(this, function(L, document){

  L.MarkerClusterGroup = L.FeatureGroup.extend({
    // stuff
  });

  // more stuff

}));
```

**Comment by helllamer** [comment]
Js~ code snipped to avoid the problem using webpack [exports-loader](https://github.com/webpack-contrib/exports-loader) and [imports-loader](https://github.com/webpack-contrib/imports-loader) shims:
```
import Leaflet from 'leaflet'
import MarkerClusterGroup from 'imports-loader?L=leaflet!exports-loader?L.MarkerClusterGroup!./node_modules/leaflet.markercluster/dist/leaflet.markercluster.js'

// Purge window.L early
Leaflet.noConflict();

// Create cluster:
val mcg = new MarkerClusterGroup(...);
Leaflet.addLayer(mcg);
```

**Comment by danzel** [comment]
This should be better with the 1.3.0 release now I think.

**Comment by matt-wallis** [comment]
> This should be better with the 1.3.0 release now I think.

I just installed 1.3.0, and I'm back into the world of `ReferenceError: L is not defined`, which I thought I had finally sorted out (before installing 1.3.0). I have the following:
```
requirejs.config({
    paths: {
		leaflet: "leaflet-1.3.1",
		leafletAwesomeMarkers: "leaflet.awesome-markers.min",
		leafletMarkerCluster: "leaflet.markercluster-1.3.0",
    },
	shim: {
		// leaflet must be loaded before leafletAwesomeMarkers.
		// See http://requirejs.org/docs/api.html#config-shim
		// Note that this assumes that leafletAwesomeMarkers is NOT an AMD module.

		// Following: https://github.com/lvoogdt/Leaflet.awesome-markers/issues/57:
        'leaflet': {
            exports : 'L'
        },
		'leafletAwesomeMarkers': {
			deps: ['leaflet']
        },
		'leafletMarkerCluster': {
			deps: ['leaflet']
		}
	}
});
```
And in the application:
```
var leaflet = require("leaflet");
var markerCluster = require("leafletMarkerCluster");
group = leaflet.markerClusterGroup();
```
This worked before I installed 1.3.0, and it also works when I run the app locally on my dev machine, but not when I deploy it to a server (classic!).

Any help with this would be very gratefully received.

**Comment by matt-wallis** [comment]
Correction: Reverting to the previous version of leaflet.markercluster didn't fix the problem:
```
		//leafletMarkerCluster: "leaflet.markercluster-1.3.0",
		leafletMarkerCluster: "leaflet.markercluster-old",
```
:-(
Previously, the problem was always intermittent. Now it is guaranteed to occur when I run the app when it's deployed to the web, and never to occur when I run the all locally.

**Comment by pjdevries** [comment]
> import {MarkerClusterGroup} from "leaflet.markercluster" error. ReferenceError: L is not defined

@novakand Have you ever found a solution for this?
