### ISSUE TITLE
Override Cluster Marker latlng

### ISSUE THREAD

**Issue by pelmorexbuddy** [Leaflet/Leaflet.markercluster#442]
Hey.  Love the plugin, use it all over yadda yadda.....

What I am hoping to do it override the latlng or layer point where the marker will be placed.  Ideally I'd like to tell the cluster to choose the latlng from a random marker within the clustered array, but directly supplying the latlng or point could be an option.  I realize that this could result in overlap on clustered layers and am willing to deal with that

**Comment by danzel** [comment]
I think you will just need to change this calculation here:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.js#L143-L149
