### ISSUE TITLE
How to set maxClusterRadius based on Zoomlevel ? 

### ISSUE THREAD

**Issue by MagdaN** [Leaflet/Leaflet.markercluster#443]
Hi, 

I am trying to set the maxClusterRadius based on the zoomlevel of the map, but can't figure out how to do this, as the function that I added to maxClusterRadius is only called once when the markerClusterGroup is created. Is there a way to do that?

Thanks in advance
Magda

**Comment by danzel** [comment]
It should get called for every zoom level at the start. Code looks right to me.
Can you jsfiddle a reproduction?

**Comment by RWpolyakov** [comment]
@danzel , how can I set maxClusterRadius based on ZoomLevel?
I need to set it to ~10, when the map zoom level is 16 or higher (to split logically different marks).
Could you help me?

**Comment by dmofot** [comment]
@RWpolyakov - Have you taken a look at Leaflet's [zoomend event](http://leafletjs.com/reference.html#map-zoomend)?  There's a good example of displaying specific layers at specific zoom levels [here](http://gis.stackexchange.com/a/41988) and maybe that could be used to modify the maxClusterRadius on your clusterlayer.

**Comment by RWpolyakov** [comment]
@dmofot I'm afraid I don't actually understand, how I'll do it. I should override _generateInitialClusters function?

**Comment by danzel** [comment]
Set maxClusterRadius to  a function.
It will be passed a parameter which is the zoom level.
Return the maxClusterRadius you want at that zoom level.

It does all these calls when it is constructed.

**Comment by meggers** [comment]
@danzel, when I pass the variable `radius` defined by 

```javascript
    var radius = function(zoom) {
      return 80;
    };
```

markerCluster fails to initial at all (markers are not clustered). Is my syntax wrong? This also occurs when I do:

```javascript
new L.MarkerClusterGroup({
        spiderfyDistanceMultiplier: 1.5,
        maxClusterRadius: function(zoom) { return 80; }
      });
```

**Comment by jessertaylor** [comment]
This is an excellent feature, thanks :+1:

**Comment by yog3sha** [comment]
I use marker cluster as a component in my app and I change options as given below:
`<v-marker-cluster :options="{maxClusterRadius:20, showCoverageOnHover: true}>`

**Comment by Karan9615-off** [comment]
@yog3sha How can we use v-marker-cluster as an HTML tag? I couldn't find any HTML tag or component provided by this library. Additionally, is it possible to wrap l-marker inside v-marker-cluster? If so, how can we achieve this?
