### ISSUE TITLE
Can I setup max number of elements inside a cluster?

### ISSUE THREAD

**Issue by FranDelaCasa** [Leaflet/Leaflet.markercluster#446]
Hi, I'm working with leaflet.markercluster and it's great!!! But I need an option to specify the max number of elements inside a cluster... is it possible to achieve this with the current version or is a missing feature?

Thanks in advance.
Fran.

**Comment by danzel** [comment]
Not possible. Not sure how that would even work?

**Comment by FranDelaCasa** [comment]
It would be nice... but, if it's not possible... thanks anyway :)
