### ISSUE TITLE
Exclude a marker from clustering

### ISSUE THREAD

**Issue by Altaisoft** [Leaflet/Leaflet.markercluster#451]
Is it possible to prevent a single marker from being grouped, leaving all other markers as before?

I have a large map with lots of markers, and most of them are clustered, which is okay. But, there is one non-clustered marker (let's call it A) near the edge of the map. I'm clicking it, and my program `setView()`'s the map to A's coordinates, so that it's now in the center.

But there is another marker B near A, which was previously hidden and now comes visible. They are quite near each other and markercluster immediately creates a cluster to group them, which is undesirable.

So the question: is it possible to prevent clustering behaviour for a single marker?

**Comment by danzel** [comment]
Move that marker out of the MarkerClusterGroup?

**Comment by stathis1998** [comment]
> Move that marker out of the MarkerClusterGroup?

8 years later, made me chuckle. And I consider my self a senior developer. I think I will give that title back. Have a nice day.
