### ISSUE TITLE
Which method is used when marker of cluster added to map (When marker's HTML inserted into DOM)

### ISSUE THREAD

**Issue by marslan390** [Leaflet/Leaflet.markercluster#453]
Hi,
Could you please let me know which method fire when marker get out of cluster and actually added on map?

Actually i am using my custom context menu on marker. and i am binding this context menu using marker's DOM Id. when marker go into the cluster then it is removing from DOM as well. and i have to re-bind context menu when it again added to DOM.

I am waiting for your reply.
thanks.

**Comment by danzel** [comment]
Go check out this section of the code:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L913-L1092
