### ISSUE TITLE
unbindPopup appears to clear click event listener

### ISSUE THREAD

**Issue by rickhall** [Leaflet/Leaflet.markercluster#455]
This issue is a copy of the following Leaflet issue:

    https://github.com/Leaflet/Leaflet/issues/3177

It is not clear if this issue is in Leaflet or markercluster...

--

I am using Leaflet marker cluster since I'm dealing with lots of data. I do something like this to listen for clicks on markers:

    this._cluster = new L.MarkerClusterGroup();
    this._cluster.on(
        "click",
        bind(this._onMarkerClick, this)
    );

And something like this to listen for popup close events:

    this._map = new L.Map($map[0], {})
        .on(
            "popupclose",
            bind(this._onPopupClose, this)
        );

To avoid creating excessive popups, I am trying to dynamically bind/unbind popups to the markers, like this:

    _onMarkerClick: function(event) {
        var $content = this._createPopupContent(event.layer._myObject);
        event.layer.bindPopup($content[0], { }).openPopup();
    },
    _onPopupClose: function(event) {
        if (event.popup._source) {
                event.popup._source.unbindPopup();
        }
    },

This works the initial time a marker is clicked, but subsequent clicks on the marker do not trigger the event and thus the popup is not displayed. This only affects the clicked marker, but any time I click another marker and dismiss its popup, then it will no longer receive click events as well. If I do not unbind in the close event, but instead just close the popup then I continue to receive click events and my popup is displayed.

From my poking around, it appears that invoking unbindPopup() in this scenario is the equivalent to doing an "off click" for that specific marker. Perhaps I am missing something, but this doesn't really seem to be an intuitive behavior. I am simply trying to reduce memory consumption by disposing of unwanted popups.

Perhaps I am missing the more obvious way to do this, but I couldn't find anything.

**Comment by rickhall** [comment]
I created this fiddle to demonstrate:

    http://jsfiddle.net/fphonku5/1/

It is entirely possible I am doing something incorrectly, but to see the issue simply run and click on the marker to see the popup, click off of the popup to make it go away, then click on the marker again and you will see the popup doesn't appear again.

**Comment by janatjak** [comment]
I try fix it.

**Comment by rickhall** [comment]
Were you able to fix this?

**Comment by janatjak** [comment]
I have not found a solution at this moment. I will be work on this issue at weekend.

**Comment by rickhall** [comment]
Great, let me know and I can test it. Thanks!

**Comment by janatjak** [comment]
Maybe I don't understand your problem, but if remove "popupclose" handler it works for me.
I understand correctly, do you want close popups when you click on map?
http://test.ifire.cz/leaflet/

**Comment by rickhall** [comment]
Yes, that is pretty much what I say at the end of the third from last paragraph in the original description.

The issue is, I don't want to bind a popup to every marker. I was trying to be efficient and only bind a popup to a marker when it was clicked and then unbind the popup from the marker when the popup is closed. My fiddle demonstrates that this isn't possible since I no longer get click events for that marker after unbinding the popup in the close handler.

**Comment by rickhall** [comment]
I will close this issue here, since I was about to recreate my issue on using just a FeatureGroup, so I think this should be tracked on my original issue in Leaflet core.
