### ISSUE TITLE
Cluster does not "fresh" when markers are moving

### ISSUE THREAD

**Issue by namezero** [Leaflet/Leaflet.markercluster#456]
in my realtime map, markers are moving, cluster is good at the first when i add markers, but when markers change locations, cluster still have the original position
also when i change marker's icon, it doesnt change when marker is under cluster

**Comment by EikeLueders** [comment]
You can try https://github.com/SINTEF-9012/PruneCluster if you need this feature immediately. There you will find it.

**Comment by namezero** [comment]
i tried it, he dont extend L.Marker, we have to cunstruct new PruneCluster.Marker we loose all functions available in L.Marker such as openPopup, bindLabel... and also all events on marker...

**Comment by danzel** [comment]
This feature works in the leaflet-master branch, which you must use the master version of leaflet with.

**Comment by sloba88** [comment]
What about spiderfied markers? Once I move one marker and click away it always go back to marker cluster original position. Is this another issue?

**Comment by danzel** [comment]
That could be a bug. make a jsfiddle to reproduce it and open a new issue if so.
