### ISSUE TITLE
Cluster markers are not removed on mobile devices (iOS) after touch

### ISSUE THREAD

**Issue by EikeLueders** [Leaflet/Leaflet.markercluster#457]
I've tested the awesome Leaflet.markercluster plugin on iOS 8 devices and the simulator. 

This is my workflow:
 - `zoomToBoundsOnClick` is set to `true`
 - I touch a cluster-marker and it zooms correctly to it's bounds. The marker spiderfies correctly.
 - The cluster-marker from the previous zoom-level (the one I just touched) is still visible on the map. Even if I zoom in again it stays on the map.
 - The cluster-marker is removed when I zoom out beyond the zoom level it was originally created.

I haven't noticed any issues with this on a normal desktop webbrowser with click-events.

**Comment by danzel** [comment]
Weird. Make a jsfiddle and check you are on the latest (git) version

**Comment by EikeLueders** [comment]
Thank's for your response danzel. I've tested around a bit more and notices that the issue is resolved in the current master branch. Since I'm using bower and installed it via bower.io I had an older release in my application (0.4.0).
