### ISSUE TITLE
Enabling moving the markers out of spiderfied cluster

### ISSUE THREAD

**Issue by sloba88** [Leaflet/Leaflet.markercluster#461]
Currently there is no way to remove a marker out of final "spiderfied" cluster when dragging or manually changing marker location.

Expected behaviour is that once you move a marker out of this group it would stay there and the group count will decrease. 

Eventually there should be option to move the marker back into the group by dragging it on top of marker cluster.

**Comment by danzel** [comment]
Ooohhh, this is what you mean. Yeah this is probably too hard to implement.
When a marker is spiderfied we override its location... hrrm, yeah maybe possible but probably hard.

**Comment by hypergreatthing** [comment]
Yeah I'm having the same sort of issue.  My use case is tracking vehicles out in the field.  They update every 30 seconds or so.  The initial cluster is great and works as expected.  As time progresses however the bubble with the count stays the same no matter how far apart they move from each other.  The underlying polygon from the space the clustering occupies increases in size, but the numbered circle always remains the same even if they're way past the cluster radius.
Someone suggested a refresh method to recalculate the distance between the points and allow the bubbles to release markers as well as capture new ones that have moved too close to each other.  I'll take a crack at diving into the code and seeing if i can make a modified version of the init that goes on, but i'm not exactly confident of my abilities.

**Comment by danzel** [comment]
Pretty certain this is support sorta now.

You can click on a cluster to spiderfy it, then drag one of those markers out. This will reduce the cluster size - assuming you move it far enough.
