### ISSUE TITLE
Make compatible with Leaflet 0.8-dev

### ISSUE THREAD

**Issue by chegga** [Leaflet/Leaflet.markercluster#465]
I tried out Leaflet 0.8-dev (2015-03-18) with markercluster. It does not work.
If you are calling
```javascript
new L.MarkerClusterGroup();
```
You get following error:
>leaflet-src.js (Row 136)
>TypeError: str is undefined
>return str.trim ? str.trim() : str.replace(/^\s+|\s+$/g, '');

Using stable 0.7.3 with same code works.

Any ideas what could it be?!

**Comment by danzel** [comment]
Use the leaflet-master branch:
https://github.com/Leaflet/Leaflet.markercluster/tree/leaflet-master

**Comment by pufanalexandru** [comment]
I have the same issue, I downloaded the master branch, version, but it doesn't work. I get the following error: 

TypeError: t is undefined        leaflet.js:5:1150

Any ideas?
