### ISSUE TITLE
Unable to change spiderLegPolylineOptions

### ISSUE THREAD

**Issue by korynorthrop** [Leaflet/Leaflet.markercluster#468]
I am trying to change the spiderLegPolylineOptions, but can't seem to get it working. I am able to add the marker cluster to my map just fine and the functionality works as expected, but I just cannot change the spider leg options.

```javascript
var markers = L.markerClusterGroup({ 
    showCoverageOnHover: false,
    zoomToBoundsOnClick: false,
    spiderfyDistanceMultiplier: 3,
    maxClusterRadius: 30,
    spiderLegPolylineOptions: {
        color: '#ffc40c'
    }
});
```

**Comment by mikeatlas** [comment]
@danzel what do you say, should I take this one :smirk: ?

**Comment by mikeatlas** [comment]
The changes are in the master branch and the latest 0.4.0-hotfix.1 build, and I'm partially to blame for a build that was off the main README.md branch.

**Comment by danzel** [comment]
lol :P Thanks @mikeatlas 

@korynorthrop You probably need to rebuild markercluster? We haven't build it since merging this feature.
Or grab this branch, which has a build
https://github.com/Leaflet/Leaflet.markercluster/tree/v0.4.0-hotfix.1

**Comment by mikeatlas** [comment]
At least I can feel some immediate satisfaction that my changes were desirable by someone else.

**Comment by danzel** [comment]
:+1:

**Comment by korynorthrop** [comment]
Thank you all for the quick response! I grabbed the v0.4.0-hotfix.1 build and everything worked. Thanks @mikeatlas for incorporating those changes!

**Comment by dbanka** [comment]
@mikeatlas is  v0.4.0-hotfix.1 a stable build? I want to use this feature but I have been asked to use this build, only if it is stable.So please help.

**Comment by mikeatlas** [comment]
We've been using it ever since I made that tiny change almost a year ago in production. Look the code over yourself, it is a very minor hotfix and if you are like me, the spider legs were then the same color as my stylized mapbox base layer. 

Why not try a build yourself and see? All semver rules dictate you'll still have the feature as you upgrade build and minor visions as well.

**Comment by mikeatlas** [comment]
(I should say I used a fork of the change for a long while before making a PR of it) 

Thanks @danzel for accepting it.
