### ISSUE TITLE
Problems with fractional zoom levels on leaflet-master branch

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet.markercluster#470]
When using fractional zoom levels markerclusters are not visible on the map for me. I couldn't manage to reproduce the same error that I had but a very similar one.

As you can see in this jsfiddle http://jsfiddle.net/Eschon/m1cemf5c/3/ the cluster does not appear at first. If you zoom in until the markers appear and zoom out again the cluster shows up, but the markers don't disappear.
If you change back to integer values for the zoom everything works as usual.

**Comment by danzel** [comment]
Yeah that'll probably be broken with fractional zoom.
Should be able to fix it if we round the zoom level

**Comment by Eschon** [comment]
Ok I quickly looked over the code and was able to fix it. I'll create a pull request so that you can check it out.

**Comment by danzel** [comment]
:+1:
