### ISSUE TITLE
No bower.json if installed with bower

### ISSUE THREAD

**Issue by obstschale** [Leaflet/Leaflet.markercluster#473]
I use leaflet.markercluster and installed it with bower. However the version 0.4.0 does not contain the `bower.json` file and therefore the css and js files are not linked automatically in index.html.

**Comment by danzel** [comment]
How did you install it with bower?

Check #394 I did a special newer tag with a bower.json in it

**Comment by obstschale** [comment]
I installed it with `bower install leaflet.markercluster --save`. Here is the content of [`bower_components/leaflet.markercluster/`](https://gist.github.com/obstschale/8f14e1b6bebbc8a7e627). As you can see there is no `bower.json` only `.bower.json` (dot-file) is present.

**Comment by danzel** [comment]
I don't know how bower works. Did someone upload something somewhere or do they pull from github or what?

**Comment by obstschale** [comment]
Sry. I cannot answer that question. This is my first project using bower, npm, grunt, etc. I know how to use it so far but don't know how it works. I just figured out that the bower.json file is missing. I thought you have to submit a package somewhere.

**Comment by danzel** [comment]
Dumb. Oh well if you find out how bower works we can try fix it :-)

**Comment by obstschale** [comment]
sound good. :+1: 

FYI: [Creating Packages > Register](http://bower.io/docs/creating-packages/#register)

**Comment by danzel** [comment]
Looks like it should just work. Maybe it doesn't like the name of our new version.

**Comment by obstschale** [comment]
I think I found the problem. I try to wrap it up. :wrench: 

1. Bower explains at [Register](http://bower.io/docs/creating-packages/#register) that the `bower.json` has to adhere to the [bower.json spec](https://github.com/bower/bower.json-spec#version).

2. Bower checks the GitHub tags as versions and the tags **0.4** and **v0.4.0** (currently the latest stable releases) both link to commit #20cf8ed. However this commit is from *2013-12-19* and did not contain a `bower.json`.

3. `bower.json` is added on *2014-01-19*
  - [History for `bower.json`](https://github.com/Leaflet/Leaflet.markercluster/commits/master/bower.json)
  - [Commit #3ad6e75](https://github.com/Leaflet/Leaflet.markercluster/commit/3ad6e759266e5bb5c768f83da569537cd2ebb140#diff-0a08a7565aba4405282251491979bb6b)

4. Tag *v0.4.0-hotfix.1* is not considered as stable release and bower does not pull it only if explicitly stated

```
$ bower info leaflet.markercluster

bower leaflet.markercluster#*   cached git://github.com/Leaflet/Leaflet.markercluster.git#0.4.0
bower leaflet.markercluster#* validate 0.4.0 against git://github.com/Leaflet/Leaflet.markercluster.git#*

{
  name: 'leaflet.markercluster',
  homepage: 'https://github.com/Leaflet/Leaflet.markercluster',
  version: '0.4.0'
}

Available versions:
  - 0.4.0
  - 0.4.0-hotfix.1
You can request info for a specific version with 'bower info leaflet.markercluster#<version>'

```

I just installed leaflet.markercluster with `bower install leaflet.markercluster#0.4.0-hotfix.1` and now `bower.json` is available :)

:arrow_right: Release a new version, like *0.4.1* that should fix the problem.

**Comment by danzel** [comment]
Thanks heaps!
Will close this off for now, when the next official version is released this will be fixed :)
