### ISSUE TITLE
How to call the marker popup when the marker is clusterized

### ISSUE THREAD

**Issue by nebadom** [Leaflet/Leaflet.markercluster#474]
I've been trying to get this to work, but it's like if the events inside the cluster disables the events on the marker. I have an event listener that calls the markers popup from outside the map. What I want is that it also calls the popup even if the marker is clusterized.

Any ideas?

**Comment by IvanSanchez** [comment]
The cluster removes markers from the DOM when they are clustered, and they lose the reference to `this._map`.

But:
```
var popup = hiddenMarker.getPopup();
map.openPopup(popup);
```

**Comment by nebadom** [comment]
Ivan, thanks for the response.

I tried your approach and now I'm getting this error:

    TypeError: Argument 1 of Node.appendChild does not implement interface Node.

This could be because I'm calling the popup from outside the map (a selectable button). Still, I sort of worked out an alternative solution: calling a custom popup.

    content = 'html code that goes inside the popup';

			customPopup = L.popup({offset: new L.Point(0, 0)})
				.setLatLng( location[latitude],locations[longitude])
				.setContent( content )
				.openOn(map);

and to close the popup I use:

    customPopup._close;

And it works. Perhaps the custom popup could be helpfull for others too.
