### ISSUE TITLE
Google Maps Port

### ISSUE THREAD

**Issue by karamfil** [Leaflet/Leaflet.markercluster#475]
Hello, 

This is an amazing project. Works extremely well, even with huge amount of data (I have loaded 500 000 pins on my local machine).

However we are stuck with google maps and I was curious is there a port for google maps or planning to port it? 

Thanks! Keep up the good work!

**Comment by danzel** [comment]
Nope!
There is a google maps layer for leaflet though.

**Comment by karamfil** [comment]
Yes I am aware of this. Thanks for the fast response.
Are there any objections if I try to port this for google maps and of course reference to this project.

**Comment by danzel** [comment]
Please have a go if you want to :)

**Comment by karamfil** [comment]
Hi @danzel, Here is a very first working version of "the thing". You can play with it if you like :)
http://avalith.github.io/MarkerClusterGroup/examples/marker-clustering-realworld.388.html

Cheers

**Comment by danzel** [comment]
wow. I'm impressed!
