### ISSUE TITLE
Filter the clustering, grouped markers

### ISSUE THREAD

**Issue by Sinusite** [Leaflet/Leaflet.markercluster#476]
Hi !
Is there a way to group markers only by categories (i.e. each cluster accept only a certain category) OR a way to fit clustering to boundaries (create one cluster by country (polygon or .KML), geographic area...) ?

Nice work.
Thanks.

**Comment by IvanSanchez** [comment]
Easy: create one MarkerCluster layer per category.

**Comment by Sinusite** [comment]
hum, yeah... noob question :)
i will try that.
Thank you for the quick answer.
