### ISSUE TITLE
Dynamic options

### ISSUE THREAD

**Issue by Volox** [Leaflet/Leaflet.markercluster#478]
Hi,
it is possible to change the options after the creation of the object?
Like the following:
```js
var clusters = new L.MarkerClusterGroup();
clusters.setOption( 'showCoverageOnHover', false );
```

Until now i tried changing valued in `clusters.options` with any luck.

**Comment by danzel** [comment]
Not with the way this option is set up:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L655-L660

You could add functions which replicate that to toggle it

**Comment by Volox** [comment]
Ok i try to write a pull request for that. What obout the other options?

**Comment by danzel** [comment]
I'm not sure. I think most of them will be hard to vhange

**Comment by danzel** [comment]
Closing, PR will be accepted if provided, but not keeping an issue open for it.
