### ISSUE TITLE
Checking markers in clusters for a particular attribute

### ISSUE THREAD

**Issue by Adventsparky** [Leaflet/Leaflet.markercluster#48]
The example here is, I have 100 markers on the page, with a priority attrtibute, which I am using to define which pin image/style they have. I now want to do something similar with the clusters.

For example, if there are 2 attributes in the currently viewed clustered pins, normal and high, I want to colour the cluster based on the priority, so if any of the markers in a cluster have the 'high' attribute, I want to apply a certain class to the cluster, and another if not.

Is there a way currently to access the markers in a cluster at the point the styles are applied to that cluster?

**Comment by karasalaravikumar** [comment]
can we know the child cluster count and marker count ? 

for example if i had 30 pins in a cluster, if i click it will split into 3 child clusters of 9pins each and 3 pins. So childClusters will give 3 . and where to get the marker count ?
