### ISSUE TITLE
Provide an option to update maxZoom of L.MarkerClusterGroup when L.map maxZoom changes. 

### ISSUE THREAD

**Issue by auoiuiouio** [Leaflet/Leaflet.markercluster#481]
I am using L.MarkerClusterGroup to render marker on map. Based on some conditions I am changing maxZoom of the map. But maxzoom at which spiderfiy occurs does not get update due to spiderification is broken. Please provide an option to update maxZoom of L.MarkerClusterGroup when L.map maxZoom changes.

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L644-L681

It looks like this should work?

**Comment by goldpbear** [comment]
This is an old issue, but I've run into a situation where I have a map with clusters whose `maxZoom` changes based on user behavior. Similar to the post above I've been trying to find a way to reset the `MarkerClusterGroup`'s `maxZoom` when the map's `maxZoom` changes.

If I'm understanding the suggestion above correctly it seems like I should call `_bindEvents()` on the `MarkerClusterGroup` instance after the `maxZoom` change? This doesn't seem to work though. I've also tried manually setting the internal `_maxZoom` property on the `MarkerClusterGroup` instance, but this produces buggy behavior on map `zoomend`.

Any thoughts are appreciated! We're using version `0.5.0` of the plugin.
