### ISSUE TITLE
How can we get all makers of cluster

### ISSUE THREAD

**Issue by marslan390** [Leaflet/Leaflet.markercluster#483]
Hi,
I want to get all markers which are in cluster whether it is showing on map or not. is it possible? if yes then how?

Thanks

**Comment by Eschon** [comment]
.getLayers() might be what you are looking for. It returns an array with all markers inside the cluster.

**Comment by marslan390** [comment]
thanks. this is what i am looking for :-)

**Comment by spostad7** [comment]
hi @Eschon, tanx for the hint,
As I read the Leaflet doc, the .getLayers() only works with layerGroups. so how can I use this method for getting markers in clusters?

**Comment by Eschon** [comment]
Hi @spostad7, the L.MarkerClusterGroup extends FeatureGroup which extends LayerGroup.
Also it overrides getLayers(), so using it on your MarkerClusterGroup should just work.
