### ISSUE TITLE
Is there any method that can let me know which markers are going to come out from cluster on zoom in

### ISSUE THREAD

**Issue by marslan390** [Leaflet/Leaflet.markercluster#485]
Hi!
I just want to know that is there any method that can return list of markers which are going to come out from cluster on cluster click and map zoom in event?

Thanks

**Comment by danzel** [comment]
When you have a cluster you can call ```getAllChildMarkers()`` on it to get all of its children.
If you want to know what ones are going to be visible at a zoom level, that gets a bit more difficult.
Use the ```_zoom``` property on Clusters to work out when they are visible, then ```_childClusters``` and ```_markers``` to see their children.
Markers in ```_markers``` are visible at the next level down.
