### ISSUE TITLE
Is there any way to have custom marker open a url instead of a popup?

### ISSUE THREAD

**Issue by chuckzezo** [Leaflet/Leaflet.markercluster#486]
Hey, 

Im using your markercluster for my project and was wondering if it was possible to have the custom icon I've added open a URL link instead of a popup... I've search and search but cannot find a solution.

below is my code..

Great plugin by the way!

		var map = L.map('map', {center: latlng, zoom: 8, layers: [tiles]});

		var markers = L.markerClusterGroup();
		 myIcon = L.icon( {
           iconUrl : 'images/marker.png',
           iconSize : [43, 65],
         iconAnchor: [22,60],         
      });    
		var markerList = [];

		function populate() {
			for (var i = 0; i < addressPoints.length; i++) {
        var a = addressPoints[i];
        var title = a[2];
				var marker = L.marker(L.latLng(a[0], a[1]), {icon: myIcon});
				icon:'images/marker.png'
				marker.bindPopup(a[2]);
				markers.addLayer(marker);
				markerList.push(marker);
			}
		}

		populate();

		map.addLayer(markers);
		map.scrollWheelZoom.disable();
		document.getElementById('doit').onclick = function () {
			var m = markerList[Math.floor(Math.random() * markerList.length)];
			markers.zoomToShowLayer(m, function () {
				m.openPopup();
			});
		};
		
		
		jQuery.extend(jQuery.easing, {
    easeOutQuint: function(x, t, b, c, d) {
        return c * ((t = t / d - 1) * t * t * t * t + 1) + b;
    }
});

**Comment by marslan390** [comment]
Hi chuckzezo,

Yes you can do it by just binding click event to marker and set url property of it. And on click event handle just navigation it to given url.

var marker = L.marker([52, 12], {});
marker.url = 'www.google.com'

marker.on('click', function(){
window.location = (this.url);
});

**Comment by chuckzezo** [comment]
Works like a charm.. thanks!
