### ISSUE TITLE
Zoom to show layer by marker id

### ISSUE THREAD

**Issue by kingstakh** [Leaflet/Leaflet.markercluster#492]
Hi, try get no randomly open popup marker by id. But my example not work, can help?
	
	<button id="doit_01">Zoom to marker 1</button>
	<button id="doit_02">Zoom to marker 2</button>
	<button id="doit_03">Zoom to marker 3</button>
	<button id="doit_04">Zoom to marker 4</button>
	<button id="doit_05">Zoom to marker 5</button>            

<code>
var addressPoints = [ [53.132276706224935, 26.017212867736816, "Marker_1", '01'],
            [53.132431193368994, 26.016418933868408, "Marker_2", '02'],
            [53.132328202001325, 26.01626873016357, "Marker_3", '03'],
            [53.1324891259048, 26.016783714294434, "Marker_4", '04'],						
            [53.33492213249116, 26.358261108398434, "Marker_5", '05']	 ]
</code>

**Comment by Eschon** [comment]
I have no Idea what your trying to do. All I see are 5 HTML buttons and a JavaScript array.
Could you give us more of the code you have so far and maybe even put it into a [jsFiddle](http://jsfiddle.net) to make it easier for us to help you?

**Comment by kingstakh** [comment]
Please look this https://jsfiddle.net/kingstakh/8uzm4r7y/

**Comment by danzel** [comment]
When you create the markers remember the marker objects against the IDs.
