### ISSUE TITLE
cant remove layer with marker cluster group

### ISSUE THREAD

**Issue by cesarGimenez** [Leaflet/Leaflet.markercluster#494]
I want to toggle between 2 layers (food and shop) when the user clicks a radio button but I cant remove the markers of the cluster group. Can you help me to figure out what I'm missing?, I'm not a JS expert, may be this is not the correct approach. Thanks

working example: http://jsfiddle.net/5mm1o3d5/

**Comment by danzel** [comment]
I'm not here to give back JS help sorry.
From the MarkerCluster side, just remove the MarkerClusterGroup layer from the map.
http://leafletjs.com/reference.html#map-removelayer

**Comment by danzel** [comment]
OIC.
Change myLayerFood/Shops to be MCG layers instead of making one in your methods.

**Comment by cesarGimenez** [comment]
Thank you so much for your help, this fix my problem!

update code: http://jsfiddle.net/5mm1o3d5/3/
