### ISSUE TITLE
remove marker from cluster then add back to cluster in 'dragend' event cause an error

### ISSUE THREAD

**Issue by zzhouag** [Leaflet/Leaflet.markercluster#496]
Hi,

I need to drag marker on the map, so I want to re-cluster the marker with new position. Here is what I did:

I remove the marker from cluster in 'dragent' event and then re-add the marker to the cluster again, this is the only way I know to re-cluster the marker. But the error as the figures will appear randomly when I drag the yellow marker close or far away from the green marker, seems like the parent is null.

![screen shot 2015-04-27 at 10 33 37 am](https://cloud.githubusercontent.com/assets/3379761/7340844/ea95fa3e-ecc8-11e4-9527-14b48f958e18.png)

![screen shot 2015-04-27 at 10 32 18 am](https://cloud.githubusercontent.com/assets/3379761/7340834/c17b7dc2-ecc8-11e4-91a3-6beb0e243e69.png)

![screen shot 2015-04-27 at 10 40 52 am](https://cloud.githubusercontent.com/assets/3379761/7340892/399023d4-ecca-11e4-9913-bdc13a83cf41.png)

Could u help to fix this issue or give me some work around ways to achieve re-cluster?

Thank you very much!

**Comment by danzel** [comment]
If you use the master version of leaflet and the leaflet-master branch of MCG this should work.
You don't need to add any event handling, the marker drag events in leaflet will do it all.

Reopen if you try that and it doesn't work.

**Comment by zzhouag** [comment]
Thank you. I download the master version of leaflet from github, but I can't find the leaflet.js file, but the 0.7.3 version from leaflet offical website has. Need I build the leaflet.js myself?

**Comment by danzel** [comment]
yep

**Comment by zzhouag** [comment]
Hi, I build the master version of leaflet, I got en error same as #338.
