### ISSUE TITLE
Add method to redraw cluster icons

### ISSUE THREAD

**Issue by azatoth** [Leaflet/Leaflet.markercluster#498]
Currently we have a situation where we have a number of fixed placed nodes (around 5500) which over time change flags and data, and the cluster icon reflects an aggregation of this data as it's icon.
As I've not been able to figure out any good way to do this properly, I've resorted to clearLayers() on the markercluster and readd them all when any data on a node is update.

I would really suggest a way to force redraw of the cluster icon when needed.

**Comment by kylebradshaw** [comment]
Is this the best approach you've found? 

I'm trying to basically do the same thing - I know the total count, I know the childCount in a marker and I'm showing the %age contained in the whole group of markers in the cluster. I want to adjust the 'size' of the cluster (I was going to do this w/ CSS) when the clusters coalesce or break apart but it seems that the cluster only L.DivIcon is only drawn once. So basically yes a way to redraw the icons.

**Comment by danzel** [comment]
Use https://github.com/Leaflet/Leaflet.markercluster#getting-the-visible-parent-of-a-marker and update the icon of the found cluster?

**Comment by oliwel** [comment]
+1 for this
I have a similar setup - icons representing a dynamic state that changes quite often. It would be helpfull to mark an icon or layer as "dirty" and call a redraw method that takes care of recreating the icons. I solved that now by using removeLayer/addLayer as suggested but I consider this an expensive solution.

**Comment by danzel** [comment]
#564 has been merged which implements this
