### ISSUE TITLE
Spiderfy on any zoom level

### ISSUE THREAD

**Issue by george-silva** [Leaflet/Leaflet.markercluster#502]
Hello! Great plugin! Works perfectly.

OverlappingMarkers were firing tons of unnecessary events (one for each marker in the cluster), so I decided to try markercluster. :+1: 

Can I spiderfy at any zoom level? My use case is that I have lots of markers in the same position, and I dont want the user to have to zoom all the way to maxzoom before spiderfying.

Can that be done?

**Comment by danzel** [comment]
You can call ```spiderfy()``` on a ```MarkerCluster``` object.
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js#L17

You can only have one cluster spiderfied at a time though.

The default click implementation just decides what to call:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L650-L653
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L663

**Comment by george-silva** [comment]
Cool. I did not see that!
