### ISSUE TITLE
sqDist calculation error when using leaflet.bouncemarker bounceOnAdd option

### ISSUE THREAD

**Issue by xLegoz** [Leaflet/Leaflet.markercluster#504]
bouncemarker library: https://github.com/maximeh/leaflet.bouncemarker

Example which causes the error. Specifically if there are more than 2 marker then any markers added after the 2nd will cause this error. I'm unsure of how the distance is calculated, or if bouncemarker affects the reported `x`,`y` position of the marker, but I believe it's probably the latter. 

http://jsfiddle.net/xLegoz/o1bzg7j0/1/

**Comment by adamghx** [comment]
Have you figured out what the issue is yet? I just encountered the problem too when using markercluster and bouncemarker at the same time. The console will display: "TypeError: Cannot read property 'x' of undefined".

**Comment by xLegoz** [comment]
Hey @adamghx 

So far the only way I managed to get around this was to make sure bounce marker is disabled on any markers added to cluster groups (marker option `bounceOnAdd: false`).

**Comment by danzel** [comment]
bouncemarker appears to move the lat/lng of the marker around, which will cause all sorts of badness as we need to know where the marker is to cluster it.
If you use a css animation instead it should work fine.
