### ISSUE TITLE
Show icon count instead of sublayer count

### ISSUE THREAD

**Issue by andi98** [Leaflet/Leaflet.markercluster#505]
Hi, folks!
MarkerCluster is a great plugin, thanks for it <3
I have a question: Is it possible, to show the count of all icons in a cluster instead of the count of subclusters? This would be much more impressive on a world map.

**Comment by danzel** [comment]
Isn't that what the default does?

Check out:
https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers
