### ISSUE TITLE
Bump bower package version

### ISSUE THREAD

**Issue by RJacksonm1** [Leaflet/Leaflet.markercluster#508]
Hi guys,

The version of the package available on Bower seems to be rather old.  If I understand how Bower versioning / updating works, then the codebase distributed by Bower is from Jan 2014.

I'm sure the package has had some major improvements in the last year and a half (chunked loading is the one that made me realise something was off).  I'm not familiar enough with the codebase to update the version number myself (has there been enough changes for a minor or major version bump).

Could any of you update the version number in bower.json when you have a moment, to make the latest code available for all bower users.

Thanks, and thanks for the great plugin!

**Comment by danzel** [comment]
You can use this tag for now:
https://github.com/Leaflet/Leaflet.markercluster/tree/v0.4.0-hotfix.1
We'll do an updated full release when leaflet does.
