### ISSUE TITLE
Markers with the same location are not clickable

### ISSUE THREAD

**Issue by metajungle** [Leaflet/Leaflet.markercluster#509]
Markers in a cluster that have the same location are conveniently spread out at the lowest zoom level. However, some markers do not respond to click events because they are shadowed by other DOM elements. I tried to capture this in the attached screenshots. The non-clickable markers seem to be too close to the center of the cluster, and hence are behind some DOM element and do not respond to events. 

![image](https://cloud.githubusercontent.com/assets/2658733/8060117/8426e2d2-0e91-11e5-9c5d-31789bf2da2e.png)

![image](https://cloud.githubusercontent.com/assets/2658733/8060120/8ac2c520-0e91-11e5-981a-c6fb7c1a81d4.png)

**Comment by meggers** [comment]
As a workaround, you could try increasing the 'spiderfyDistanceMultiplier' setting.

**Comment by metajungle** [comment]
Yes, changing 'spiderfyDistanceMultiplier' to '2' solved my issue for now. Is the default value too low?

**Comment by danzel** [comment]
Default is fine with default marker icons, which I think is the main use case for the default, so probably ok :)

**Comment by metajungle** [comment]
Makes sense. Thanks.
