### ISSUE TITLE
Cluster updating (while  movement of markers)

### ISSUE THREAD

**Issue by Daggett-ua** [Leaflet/Leaflet.markercluster#510]
I didn't found solution via Google to solve this problem.

Problem: while updating marker position using `setLatLng` method, cluster doesn't updated. Cluster still stay in the same position.

Can anyone help me? Thanks in advance.

**Comment by danzel** [comment]
This only works when using the leaflet-master branch of markercluster with the master version of leaflet

https://github.com/Leaflet/Leaflet.markercluster/tree/leaflet-master

**Comment by Daggett-ua** [comment]
This works! Thanks a lot:)
