### ISSUE TITLE
Open a popup when cluster has been clicked

### ISSUE THREAD

**Issue by mattwagl** [Leaflet/Leaflet.markercluster#511]
Sorry for asking such a trivial question but I just couldn't find any hints in the docs or in the source code. How do you add popup to a cluster? Basically I would need to iterate over all the clusters and call `bindPopup` on each of them. The problem is that there is no public method to get all the clusters on the map. Calling `markerClusterGroup.eachLayer` only seems to iterate over all the child markers not the clusters themselves. Am I missing something?

Thanks for creating this awesome plugin!

**Comment by danzel** [comment]
Listen to the 'clusterclick' event
https://github.com/Leaflet/Leaflet.markercluster#events
