### ISSUE TITLE
bower.json missing and .bower.json missing main attribute

### ISSUE THREAD

**Issue by mastermind1981** [Leaflet/Leaflet.markercluster#513]
Hi,

I have installed the markercluster via bower and i noticed that there is no bower.json file. Besides that, the .bower.json misses the main attribute.

Could you please fix that?

Thanks

**Comment by JonathanWolfe** [comment]
Bower removes the bower.json when you `bower install`. Why do you need it?

**Comment by mastermind1981** [comment]
to know the file i would use from the library because i use the main attribute to get the file i should use

**Comment by JonathanWolfe** [comment]
Oh, gotcha.

Well, the `bower.json` currently does have a `main` attribute, but because the maintainer forgot to make a release for it or assign a tag, bower doesn't know it's been updated.

So once that happens, you should be good to go.

**Comment by danzel** [comment]
We have the main attribute in the leaflet-master branch, so this will be fixed when that eventually releases.
