### ISSUE TITLE
zoomToBounds offset?

### ISSUE THREAD

**Issue by mattots** [Leaflet/Leaflet.markercluster#515]
I'm trying to figure out a way to add a horizontal offset to the zoomToBounds centre-point. I have a 400px wide sidebar on the right hand side of the map so I would like zoomToBounds to zoom to a centre-point 200px left of where it would normally (I know this isn't perfect since the bounds could still be slightly wider than the visible area of the map, but I'm not too worried about that).

I've figured out how to acheive this with leaflet itself (see https://github.com/Leaflet/Leaflet/issues/859) but struggling to know how to do it with markercluster.

Any ideas?

**Comment by ghybs** [comment]
Hi,

Just in case you would be still looking for a proper solution, you could consider using one of those 2 plugins:
- [Leaflet-active-area](https://github.com/Mappy/Leaflet-active-area)
- [Leaflet.ControlledBounds](https://github.com/MazeMap/Leaflet.ControlledBounds)

(see also #322 for more details)

Hope this helps.
