### ISSUE TITLE
Ability to specify spider legs width, opacity and colour

### ISSUE THREAD

**Issue by jessertaylor** [Leaflet/Leaflet.markercluster#518]
A little feature request for one of the best leaflet plugins I've seen.

I have tried setting the stoke properties via css but it is a little glitchy as it seem the stroke is actually animated, and overriding them causes them to be what they are at the end of the animation.

ETA: I've just realised the spider leg animation is actually glitchy overidden or not, it was just more noticeable when I made the legs white and wider.

If it were possible to specify the ending stroke width, stoke opacity and stroke colour in javascript it would be nice, or do you suggest just doing this via css?

Many thanks

**Comment by danzel** [comment]
We have ```spiderLegPolylineOptions```
https://github.com/Leaflet/Leaflet.markercluster#defaults
Which should do it?

**Comment by jessertaylor** [comment]
Ah I'm blind - thanks danzel.
