### ISSUE TITLE
Get Marker parent Cluster for current zoom level

### ISSUE THREAD

**Issue by bpevangelista** [Leaflet/Leaflet.markercluster#519]
I have a swipe feature that goes to the next Map marker, which might be inside of a cluster in the current zoom level. If the next marker is inside of a cluster, I want to open his cluster. I've implemented this in a couple of different ways but they all look very hacky:

Non-safe code:
```
    var spiderfyParent = function(marker) {
        var parent = marker.__parent.__parent.__parent.__parent;
        if (parent._zoom >= $scope.map.getZoom()) { // Only care if zoom level is bigger or equal
            parent.spiderfy();
        }
    }
```

I'm not sure why I have to go 4 parents up but this code always work for me. Another option is: traverse all Map layers that are L.MarkerCluster and compare the '_leaflet_id' but this is not guaranteed to work if I'm panning the map.

Is there a better way to achieve this? Can we have a function like that added to the lib?

Thanks a lot

**Comment by danzel** [comment]
Use this:
https://github.com/Leaflet/Leaflet.markercluster#getting-the-visible-parent-of-a-marker

**Comment by bpevangelista** [comment]
There appear to be an issue in this case, if I click on the cluster and then on a marker inside of it and call getVisibleParent it returns the current marker, although it has a cluster visible with ~0.5 opacity in the screen.

**Comment by danzel** [comment]
Yeah, If the marker is currently spiderfied it'll return the marker as it is visible.

You'll need to check out the code of the method and change it to check for this specific case. Not sure this is how the default behaviour should be.
