### ISSUE TITLE
bower install installs an old version, because of bower naming convention

### ISSUE THREAD

**Issue by guyzi** [Leaflet/Leaflet.markercluster#520]
Names that contain '-' are considered pre-released version and not the latest version and thus not downloaded when using bower install.

See this issue for details:
https://github.com/bower/bower/issues/782

I've solved this issue by creating a tag with a name such as 0.4.1

**Comment by mattgrande** [comment]
Did you manually create that tag? I'm trying to get `0.4.0-hotfix.1` into my app, and it keeps installing `0.4`.

**Comment by guyzi** [comment]
Yeah exactly. I've created a tag for my own fork though. This is exactly the 'bug', a tag with '-' in its name is not considered the latest version, but a prereleased version (see this https://github.com/bower/bower/issues/782)

**Comment by mattgrande** [comment]
I changed my bower.json to have the explicit version number (ie, `"leaflet.markercluster": "0.4.0-hotfix.1"`), and that got it working.

I was trying to say "`0.4.0-hotfix.1` or greater," but couldn't get that to work, unfortunately.

**Comment by danzel** [comment]
This isn't really a markercluster bug.
There will be a new pre-release version soon for 1.0.0 compatibility. Watch #528
