### ISSUE TITLE
Markers disappear when zooming out with open popup when using an iconCreateFunction

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet.markercluster#522]
I've created this [jsFiddle](http://jsfiddle.net/Eschon/x34qbz3e/). If you zoom out and back in the markers disappear and the popup stays on the map. I can reproduce this in the latest versions of Chrome and FF but not in Safari.

Is there something else that I should do in the iconCreateFunction to prevent this or is this a bug?

**Comment by Eschon** [comment]
Bump
Can anyone help with this?

**Comment by danzel** [comment]
Can you do a video/gif, I don't think I'm doing the same thing as you.

**Comment by Eschon** [comment]
Ups it seems my fiddle was missing the iconCreateFunction for some reason.
But even with the icon create function I can't manage to reproduce it in the fiddle, so I made a gif from my project.
![markercluster](https://cloud.githubusercontent.com/assets/11647830/9105397/992c713e-3c17-11e5-8092-e1bc5a7ad572.gif)
Also the popup doesn't stay on the map anymore but the markers still disappear.
I'll try to look into it and make a fiddle where I can reproduce it again.

**Comment by danzel** [comment]
Are you using an old version of MarkerCluster?
There was a bug like this once upon a time.

You could dom inspector the marker layer and see if the markers are there when you zoom back in, they might have opacity 0 or something.

**Comment by Eschon** [comment]
I use the leaflet 1.0 beta so I had to build markercluster myself from the leaflet-master branch maybe the fix is not in there.

**Comment by danzel** [comment]
I don't think so, the bug was ages ages ago IIRC.

**Comment by Eschon** [comment]
Hm I tried to switch my fiddle to the leaflet and markercluster versions I use but still not reproducing.
Maybe it's some problem in my code. 
If I find something I'll report back here.

**Comment by danzel** [comment]
:+1:

**Comment by Eschon** [comment]
Ok I've found out a few more things:

* The markers are there, they just have an opacity of 0 like you said
* It doesn't matter if I use an iconCreateFunction or not
* There is an error in the JS console (see screenshot)

![screen shot 2015-08-06 at 09 28 24](https://cloud.githubusercontent.com/assets/11647830/9106088/c0e38504-3c1d-11e5-861d-8153300fc3c9.png)

**Comment by danzel** [comment]
Whatever is causing this error will be doing it.
Break on the error and see what is null, then look up the stack to see where the null comes from.

**Comment by Eschon** [comment]
The thing that is null is this._map.
I went up the call stack but I didn't find anything. I think it gets somehow set to null when zooming out but the error is thrown when zooming back in.

**Comment by desperate-man** [comment]
I assume this happens because pop up updates the marker instance and when zoom out occurs the markercluster checks if the marker is the same instance or not and it fails to find the marker since it's not the same. I have overcome this problem by detaching the marker from the cluster and attaching it directly on the map or to some other layer.

**Comment by Eschon** [comment]
@desperate-man Thank you, this seems to be the problem.
I'm not sure if changing the icon or adding the popup is the problem but removing the marker from the cluster when highlighting and adding it back when unhighlighting seems to solve the problem.

@danzel Should I close this now or should there be a fix to handle this in markercluster?

**Comment by danzel** [comment]
It does sound like a possible bug, but if you can't reproduce it so we can fix it, then close it.

**Comment by Eschon** [comment]
Since I know what the problem is now I should be able to make a fiddle to reproduce it.

**Comment by Eschon** [comment]
Ok, so there seems to be more going on than I thought at first.
I don't want to invest too much time in playing around with a fiddle to reproduce this so I'll close this for now.

**Comment by danzel** [comment]
ok thanks
