### ISSUE TITLE
Markercluster group is not working properly if we check map.getBounds before adding marker to the cluster group.

### ISSUE THREAD

**Issue by mayuri2601** [Leaflet/Leaflet.markercluster#523]
Hi,

I have created a map with a markerclustergroup. I have added a check for zoom in / out and dragging that if  map.get bounds contains the marker then only add the marker in the cluster group else remove the same marker from the group.

As i have a very long list of markers so I just want ti display the markers on screen within the bounds.

This is my code -

var items2 = [{"lat" : "-41.3", "lon" : "174.7"},{"lat" : "-42.28846", "lon" : "175.76844"},{"lat" : "-40.28756", "lon" : "173.76854"},{"lat" : "-39.28666", "lon" : "172.76864"},{"lat" : "-38.28576", "lon" : "171.76874"},{"lat" : "-43.28496", "lon" : "176.76894"},{"lat" : "-44.28326", "lon" : "177.76884"}];
                  var blankMarkerlist = new Array();
                  var blankMarkers = L.markerClusterGroup();
                  map.on('zoomend dragend', function () {
                      blankMarkers.clearLayers();
                      var bounds = map.getBounds();
                      for (i = 0;i &lt; items2.length;i++) {
                          var LamMarker2 = new L.marker([items2[i].lat, items2[i].lon], 
                          {
                              icon : markerIcon
                          });
                          if (bounds.contains(LamMarker2.getLatLng())) {
                              blankMarkerlist.push(LamMarker2);
                              blankMarkers.addLayer(blankMarkerlist[i]);
                          }
                      }
                      map.addLayer(blankMarkers);

But here the marker cluster is not behaving properly after adding this line -  if (bounds.contains(LamMarker2.getLatLng()))

Thanks for your return on this point!

**Comment by danzel** [comment]
Is this wrong?

blankMarkers.addLayer(blankMarkerlist[i]);

I'm not going to debug your code sorry.
