### ISSUE TITLE
Using markercluster alongside Timeline

### ISSUE THREAD

**Issue by iggnacho** [Leaflet/Leaflet.markercluster#527]
I was wondering if it is possible to use the marker cluster visualizations of points with timeline plug-in(https://github.com/skeate/Leaflet.timeline) to create a temporal animation with my points being clustered instead of overlapping. I thought Since timeline plug-in extends L.geoJson I could try to plug in directly but that did not work.

**Comment by danzel** [comment]
I dunno.
Try it and find out?
Probably you will need to change the add/remove marker code in timeline to use a MarkerClusterGroup layer, then it might work?

**Comment by dmundra** [comment]
@iggnacho I was able to use layer support sub-plugin to work with Leaflet.timeline: https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport
