### ISSUE TITLE
Update for Leaflet 1.0 Beta

### ISSUE THREAD

**Issue by Liquid2Sky** [Leaflet/Leaflet.markercluster#528]
Would like to know if there are plans to update the markercluster plugin to work fine with Leaflet 1.0 Beta.

**Comment by Eschon** [comment]
There is the `leaflet-master` branch that works for me. You'll have to build it yourself though.

**Comment by Liquid2Sky** [comment]
Leaflet Master (0.7.3) is working fine with the markercluster plugin but I would like to test the Leaflet Beta in our project.
Did I miss something? 
Sorry...git noob ;-)

**Comment by Abbe98** [comment]
@Liquid2Sky the markercluster branch `leaflet-master` works with Leaflet 1.0 Beta...

**Comment by Liquid2Sky** [comment]
Thx for pointing me the rigth way. I tried leaflet-master and i get the same error.
Build a jsFiddle, to demonstrate the problem.
http://jsfiddle.net/LiquidSky/thc75836/
Try to investigate it

**Comment by inod** [comment]
I'm using Leaflet 1.0.0 beta 1 from the CDN and having built markercluster: `leaflet-master` myself, I get the same error as Liquid2sky.

`var markers = new L.MarkerClusterGroup();` brings the error.

**Comment by Eschon** [comment]
Hm... strange I see the error in @Liquid2Sky's fiddle but my own local version works fine.
I have no idea whats wrong here.

**Comment by nakhbari** [comment]
I just jaked the master branch and still get the same error as @inod

**Comment by Eschon** [comment]
@nakhbari did you use the markercluster branch called `leaflet-master` or the markercluster master branch? If it is the latter one it is not compatible with Leaflet 1.0.0 beta 1

**Comment by inod** [comment]
@Eschon here is the `leaflet.markercluster-src.js` I've built from `leaflet-master` and gives the error: http://pastebin.com/2TrrUQmv

Could you please compare or share your working file to see if we're building from `leaflet-master` correctly?

**Comment by Eschon** [comment]
I can do that on monday when I'm back at work

**Comment by patrickarlt** [comment]
@danzel any chance of maybe releasing a 1.0.0-beta.1 to match the Leaflet release and merging leaflet-master? Is there anything I can help with?

**Comment by Eschon** [comment]
Here's my [working markercluster file](http://pastebin.com/3ZjK6LtA)
One thing that might be different is that I built it from https://github.com/Eschon/Leaflet.markercluster where I prepared a PR for fractional zoom levels but as far as I know there have been no changes to the `leaflet-master` branch since my PR was merged.

**Comment by Liquid2Sky** [comment]
@Eschon Thx man! I took a quick look and it is working fine.

**Comment by supaustin** [comment]
@Eschon Thanks for posting this!  Worked like a charm!

**Comment by nebadom** [comment]
@Eschon your version from http://pastebin.com/3ZjK6LtA works. None of the existing versions merged seems to work but yours.

Thanks! good job!

**Comment by zavan** [comment]
Running jake from the root directory solved

`Cannot read property 'trim' of undefined`

For me.

**Comment by Eschon** [comment]
@zavan I remember getting some kind of error at first too.
Did you run `npm install`?

**Comment by zavan** [comment]
@Eschon  Yes, I had to run npm install to install jake and two other dependencies:

`sudo npm install -g jshint`
`sudo npm install -g uglify-js`
`sudo npm install -g jake`

Then run `jake` from the the root directory.

**Comment by joshdickerson92** [comment]
The pastebin from @Eschon solved the issue for me!

**Comment by Toub** [comment]
Good to know that leaflet-master branch works with 1.0.0.-beta-2.

But what does it mean exactly, as this branch has not been updated for a while.

What about creating a 1.x branch from master and upgrade the plugin to be compatible with last beta?

**Comment by jgravois** [comment]
i agree with @patrickarlt.  given that the `leaflet-master` branch is working with 1.0.0-beta.2, a tagged release would be really helpful.  please let me know if there's anything i can do to chip in.

**Comment by Monduiz** [comment]
I agree with @patrickarlt and @Toub. Its a little confusing for now to go back to the master which hasn't been updated in awhile, it would be much better to have a release that matches the new beta. Thanks for all the work! I cant wait for the improvements of version 1.0.

**Comment by laurence-hudson-tessella** [comment]
:+1: A tagged build (#582), with an updated dist, known to work with the leaflet 1.0-beta2 would be useful

**Comment by TimMcCauley** [comment]
Dito, the pastebin from @Eschon solved the issue for me, too.

**Comment by danzel** [comment]
Master branch is now the leaflet 1.0 compatible version (0.7 has been branched off).
Will do a tag later today if I remember.

**Comment by danzel** [comment]
Ok tagged
https://github.com/Leaflet/Leaflet.markercluster/tree/v1.0.0-beta.2.0

**Comment by dmsmidt** [comment]
Thanks for the tag, however I still have the earlier mentioned problem with the file dist/leaflet.markercluster.js.

```js
Uncaught TypeError: Cannot read property 'trim' of undefined
```

**Comment by jgravois** [comment]
@dmsmidt are you certain you're leveraging the dist files from the actual tagged release @danzel linked above?  when i click on his link, select `Download ZIP` and run the samples in the `example` folder locally, they don't throw any errors.

another alternative would be to get a local reference to the latest contents of the [`master`](https://github.com/Leaflet/Leaflet.markercluster/tree/master) branch and run the command `npm install` to lay down dependencies and `jake build` to concatenate and minify the current contents of the `src` folder (and rewrite the stale content that's in `dist`).

@danzel, i'd be happy to lay down a PR to remove the `dist` folder from version control entirely if you're into it.  either way, thanks for the tag!

**Comment by zavan** [comment]
The tag solved it for me. Thanks.
Installed through bower and using from the dist folder.

If the dist folder is going to be removed, is there a way of bower automatically run the build process on install? Or maybe a separate repo should be created just for bower?

**Comment by jgravois** [comment]
@zavan it would be really easy to make sure tags/releases continue to include concatenated/minified source (**without** tracking in version control the rest of the time) so that there wouldn't be a need to invoke a post install routine or maintain a seperate repo.  

totally the maintainers call, but seems like it would reduce some justifiable confusion amongst some of the project's users.

**Comment by dmsmidt** [comment]
@jgravois I tried again and it works indeed, must have messed up something in my automated setup, or may have had a caching issue. Thanks for checking for me, sorry for the bother.

@zavan Preferably the dist folder with the compiled version of the lib stays in. I'm pulling in a lot of libraries in a Drupal 7 project automatically and prefer for the moment to not have to build the lib myself each time. I guess it's easy for others as well, since you need less software to get up to speed.

**Comment by danzel** [comment]
I'm thinking about removing the built files from master and just have them in tags, stops confusion like this.

Will need to do more releases more often to make it work though.

**Comment by danzel** [comment]
Have removed the built js files from dist except on tags

**Comment by jgravois** [comment]
@danzel awesome!

**Comment by danzel** [comment]
This is all done and stuff. Not sure how I missed closing this issue.
