### ISSUE TITLE
getLayer should use ==, not ===

### ISSUE THREAD

**Issue by Brad-E** [Leaflet/Leaflet.markercluster#531]
Leaflet/src/core/Util.js stamps _leaflet_id with a number, but getLayer takes a string id.

---------- leaflet.markercluster-src.js ----------
```javascript
    //Overrides LayerGroup.getLayer, WARNING: Really bad performance
    getLayer: function (id) {
        var result = null;

        this.eachLayer(function (l) {
            if (L.stamp(l) === id) {
                result = l;
            }
        });
    
        return result;
    },
```

---------- LayerGroup ----------
http://leafletjs.com/reference.html#layergroup-getlayer
getLayer( \<String> id )	ILayer	Returns the layer with the given id.

-------- Leaflet/src/core/Util.js ----------
```javascript
	// return unique ID of an object
	stamp: function (obj) {
		/*eslint-disable */
		obj._leaflet_id = obj._leaflet_id || ++L.Util.lastId;
		return obj._leaflet_id;
		/*eslint-enable */
	},

	lastId: 0,
```
-------------------------------------------------

**Comment by danzel** [comment]
PR plz
