### ISSUE TITLE
Updating cluster DivIcon when markers inside of it change.

### ISSUE THREAD

**Issue by misabel** [Leaflet/Leaflet.markercluster#535]
Right now I have it so that the cluster changes color depending on the status of the markers inside of it. Is there a way to force ClusterGroup to call on iconCreateFunction again?

**Comment by danzel** [comment]
So you update properties of a marker, but don't move them?

As a hack you could remove/re-add the marker which will cause it to redo the icon.

Or use this:

**Comment by misabel** [comment]
I've already tried removing/adding the marker again, but this slows down my application down by a lot when dealing with thousands of markers. I will try the getting the visible parent method and see how that works out.

**Comment by danzel** [comment]
#564 has been merged which implements this
