### ISSUE TITLE
Custom divIcon for marker endpoint

### ISSUE THREAD

**Issue by ScaredyCat** [Leaflet/Leaflet.markercluster#538]
I have a custom icon which is a divIcon. I can add this to a standard leaflet map with

                L.marker(new L.LatLng(arr[0], arr[1]) {icon: pulseIcon});

When using markerClusterGroup I want to keep the coloured circles with their value but I'd like to override icon at the base (when you can zoom no further). It seems that the only thing you can do is override the default icon L.Icon.Default with an image and corresponding shadow. Is there any way to use a divIcon instead. I tried using

                for (var i = 0; i < addressPoints.length; i++) {
                        var a = addressPoints[i];
                        var title = a[2];
                        var marker = L.marker(new L.LatLng(a[0], a[1]), { title: title }, {icon: pulseIcon});
                        marker.bindPopup(title);
                        markers.addLayer(marker);
                }

                map.addLayer(markers);

where pulseIcon is my divIcon but it's ignored. Is this possible, if not can I add a feature request. Every example I've found only uses the default blue marker. It's also worth noting that even modifying the default icon causes problems because, for example iconSize appears to get ignored.

**Comment by danzel** [comment]
You'll need to use this:
https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers

And maybe use the ```cluster._zoom``` variable

**Comment by ScaredyCat** [comment]
Thanks for the reply. In the end I actually switched to PruneCluster as it offered this ootb and deadlines are deadlines.
