### ISSUE TITLE
Popup disapears when zooming out and marker is put into a cluster

### ISSUE THREAD

**Issue by aliparlar** [Leaflet/Leaflet.markercluster#539]
Not an issue, perhaps a feature request,

In my use case, I find it beneficial if the centered marker popup is open, and we are zooming out, the marker should be left out of clustering, so we can spot where it is, from a zoomed out distance. I think this is true for many use cases and it could be an option.

**Comment by danzel** [comment]
You'll need to remove the marker from the marker cluster when it is open (and add it directly to the map).
Then do the opposite when the popup is closed.

**Comment by mirko77** [comment]
@danzel I would like to know if there is a callback when the popup is closed due to the marker being put into a cluster.

I tried:

```
markers.on('clusterpopupclose', () => {
    console.log('clusterpopupclose');
});

```

but nothing

Thanks

**Comment by danzel** [comment]
Maybe `popupclose` ?
Do some testing with normal leaflet and leaflet.markercluster to compare, and if there is an issue make a new issue with reproducable cases. Thanks!

**Comment by mirko77** [comment]
Thanks for your reply. `popupclose` was already there, then I looked at the docs where it says to add the `cluster` namespace. Not working, though. The original `popupclose` triggers when I manually close a popup, that's it.
