### ISSUE TITLE
Blocks all links in popups

### ISSUE THREAD

**Issue by under-score** [Leaflet/Leaflet.markercluster#540]
Leaflet.markercluster blocks links in popups to be executed.
The example code at http://stackoverflow.com/questions/13698975/click-link-inside-leaflet-popup-and-do-javascript isn't working whenever a L.MarkerClusterGroup is being defined.

**Comment by danzel** [comment]
I really doubt this is our fault.
Please make a js fiddle to reproduce

**Comment by under-score** [comment]
I agree, the problem was with the largely undocumented layer handling of leaflet, not with Leaflet.markercluster. Thank you.
