### ISSUE TITLE
Update GeoJSON SQL query when a select box changes - L.markerClusterGroup(); Causing Error

### ISSUE THREAD

**Issue by dchadney** [Leaflet/Leaflet.markercluster#541]
I am trying to change the SQL query when a select box changes. It's working, but instead of clearing out what is currently there it's just resubmitting the same query and adding it to the existing one. So if I have 440 results and select an option I now get 880 results.

I thought that map.removeLayer (geojson); would take care of that but I think I am missing something.

    <select id="dropdown_selector">
        <option value="Agricultural">Agricultural</option>
        <option value="Property">Property</option>
        <option value="VisualImpact">Visual Impact</option>
        <option value="Safety">Safety</option>
        <option value="Vegetation">Vegetation</option>
    </select>

    var markers = L.markerClusterGroup();
      var geojson = null;  
      var sqlQuery = "SELECT * FROM cartoDBdatabase";

      // CALL THE CARTODB SQL API HERE IN URL FORMAT
      function setViewer(){
      if(map.hasLayer(geojson)){
        map.removeLayer(geojson);
      };

      $.getJSON("https://username.cartodb.com/api/v2/sql?format=GeoJSON&q="+sqlQuery, function(data, latlng) {
        geojson = L.geoJson(data, {
        pointToLayer: function(feature, latlng) {
            return L.marker(latlng, {
              icon: L.icon({
                iconSize: [27, 27],
                iconAnchor: [13, 27],
                popupAnchor:  [1, -24], 
                iconUrl: 'images/commentMarker.png'
              })
            })
          },
      onEachFeature: function (feature, layer) {          
        // ADD A POPUP WITH SOME INFO
        layer.bindPopup("<h2>" + feature.properties.name + "</h2><hr><p><b>Comment:</b> " + feature.properties.description + "</p><p><b>User Address:</b> " + feature.properties.profile_address +"</p><p><b>User Address:</b> " + feature.properties.profile_address +"</p>" );

      }
    });
    markers.removeLayer(geojson);
    markers.addLayer(geojson);
    markers.addTo(map);

           $('#dropdown_selector').change(function(){
                 var commentType = $(this).val();
                 sqlQuery: "SELECT * FROM cartoDBdatabase WHERE comment_type ILIKE '%"+commentType+"%'";
                setViewer();
          });
     });
    }

    
setViewer();

Images that illustrate the issue:
![beforefilterclick](https://cloud.githubusercontent.com/assets/6171283/9233301/92d4ca7a-40ef-11e5-96b0-6d1fefd4fb72.JPG)

![after1click](https://cloud.githubusercontent.com/assets/6171283/9233289/7cd8f2b4-40ef-11e5-813f-b215f6f6f1b6.JPG)

![after2clicks](https://cloud.githubusercontent.com/assets/6171283/9233298/8e302a14-40ef-11e5-8802-56732f730ec0.JPG)

![click on show all](https://cloud.githubusercontent.com/assets/6171283/9233304/9a1ca2d0-40ef-11e5-982c-800fd8e7615f.JPG)

You can see that the quantity of the markers doubles each time the filter is clicked... it's not clearing out the previous markers.

I have narrowed it down to the leaflet plugin L.markerClusterGroup();, but I have no idea how to fix this. Any help is greatly appreciated!

**Comment by danzel** [comment]
You are providing the new geojson layer to removeLayer, so it doesn't have the old markers in it.
We're not here to debug your app sorry.

**Comment by dchadney** [comment]
Okay thanks. All I was hoping for was a reference to what I was doing wrong, since there is hardly any documentation provided on this plugin.

**Comment by ibrahimmohammed1** [comment]
danzel. you are a son of bitch

**Comment by ibrahimmohammed1** [comment]
did you manged to fix this ?

**Comment by danzel** [comment]
@ibrahimmohammed1 
Maybe think twice about posting these sorts of things.
![image](https://cloud.githubusercontent.com/assets/393086/14662724/16ce36de-070d-11e6-9ee1-3d492aebe61b.png)
