### ISSUE TITLE
MarkerClusterGroup Popup Close Issue

### ISSUE THREAD

**Issue by JagannathNanda** [Leaflet/Leaflet.markercluster#542]
Hi Every One ,
I am adding around 2500 marker to MarkerClusterGroup at a time and all the marker contains popup. When i am clicking a marker it's pan the map to fit the popup but suddenly closed . I tried a lot but can't make it appear . But when there is a space to open popup it working fine .

**Comment by danzel** [comment]
Please make a jsfiddle test case.
