### ISSUE TITLE
Is it possible to provide custom image to MarkerClusterGroup?

### ISSUE THREAD

**Issue by mayuri2601** [Leaflet/Leaflet.markercluster#544]

**Comment by IvanSanchez** [comment]
Yes.

See also: http://homepage.ntlworld.com./jonathan.deboynepollard/FGA/questions-with-yes-or-no-answers.html

**Comment by mayuri2601** [comment]
Can you please provide me the syntax of custom marker cluster ? I tried this: but its not working.

var markerCluster = L.markerClusterGroup( {
iconCreateFunction : function (cluster) {
return L.divIcon( {
                html : '<b>' + cluster.getChildCount() + '</b>', className : 'mycluster', iconSize : L.icon( {
    iconUrl : '../resources/images/test.PNG', iconSize : [30, 30]})
            });

**Comment by IvanSanchez** [comment]
You're using `iconCreateFunction` properly but your instances of `L.DivIcon` don't look right. Read the [Leaflet documentation](http://leafletjs.com/reference.html) on how to create `L.DivIcon`s or `L.Icon`s. Note that a `L.DivIcon` does **not** have a `iconUrl` property.

And, please, indent your code.

**Comment by maximou4391** [comment]
Hi, related to @mayuri2601 I'm wondering if it's posssible to change the class dynamically, because I can't figure out a way to access the outer div and its classList attribute. To be able to do something like classList.add or remove. 
Regards,
Maxime.

**Comment by IvanSanchez** [comment]
This issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
