### ISSUE TITLE
removeLayers not working when cluster is not on map

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet.markercluster#545]
I've prepared a small [fiddle](http://jsfiddle.net/Eschon/92aLfywq/) to show my problem.
I added a cluster to the map and added a marker to the cluster.
Then I removed the cluster from the map. While the cluster isn't on the map I try to remove the marker using the removeLayers function. When I add the cluster back to the map the marker is still there.

I know that I could just use removeLayer for this small example and it works fine, but for my real use case I have a lot of markers and looping through all of them and removing then one at a time isn't good for performance.

**Comment by danzel** [comment]
Looks like a bug yep :(

**Comment by Eschon** [comment]
I found out that it works fine when the markerClusterGroup was not on the map when the marker was added: [fiddle](http://jsfiddle.net/Eschon/92aLfywq/2/)
But once it was on the map it stops working: [fiddle](http://jsfiddle.net/Eschon/92aLfywq/3/)
