### ISSUE TITLE
Popup on hovering over marker cluster

### ISSUE THREAD

**Issue by dbanka** [Leaflet/Leaflet.markercluster#547]
I want a popup on hovering over a cluster which shows how many marker locations are there inside the cluster

**Comment by misabel** [comment]
One way to do it is to create a leaflet label and add it to the map with the clusters coordinates.
cluster.on('clustermouseover', function(c) {
     var label = new L.Label().setLatLng(a.layer.getLatLng());
     map.addLayer(label);
}

but then you need to also create a 'clustermouseout' that removes this label from the map
