### ISSUE TITLE
Feature Request - Show Heat Map option

### ISSUE THREAD

**Issue by nrakochy** [Leaflet/Leaflet.markercluster#548]
Thanks for the great plugin. Would you consider adding a showHeatMap option on the marker clusters? 

The functionality is already there in `showCoverageOnHover`: 

    shownPolygon = new L.Polygon(a.layer.getConvexHull(), this.options.polygonOptions);   
    map.addLayer(shownPolygon);
    }

Not sure if you could add a custom attribute on the `DivIcon` or something like that. It would be great to allow the Polygon to persist and pass it a color scheme.

The `getConvexHull` is the key point of interest on this. It would yield very interesting maps visuals that were based on the data rather pre-determined polygons.

**Comment by danzel** [comment]
You should be able to implement this outside of markercluster (as a plugin for markercluster).
Sounds like a cool idea, but probably not something that should live in the core library.

**Comment by danzel** [comment]
Not for the core.
