### ISSUE TITLE
Is build 0.4.0 hotfix.1 a stable build?

### ISSUE THREAD

**Issue by dbanka** [Leaflet/Leaflet.markercluster#550]
I wanted to know if the 0.4.0 hotfix.1 version a stable build, so that I can use that in my app.Thanks

**Comment by danzel** [comment]
There is no stable build ever.
It will probably work though, and bug reports are welcome!

**Comment by mattgrande** [comment]
For what it's worth, dbanka, I've been using it in production for a few months now with 0 issues.
