### ISSUE TITLE
wiredep

### ISSUE THREAD

**Issue by cyrilchaponeverysens** [Leaflet/Leaflet.markercluster#551]
[This commit](https://github.com/Leaflet/Leaflet.markercluster/commit/b66b9d72de0186735a620589667b9713c1b405cb) duplicated `main` section of bower.json, and wiredep still doesn't work. In addition, the added "_main_" section is bad because it only contains the `.js` file, while the older one contains also `.css` (that wiredep can understand too)

Overall, the thing that disallows wiredep to work was not the absence of `main`, but rather the fact that _bower_ doesn't seem to checkout the file _bower.json_ itself, probably due to a bad `ignore` section (that I don't understand) inside bower.json. Wiredep, indeed, parses modules' bower.json to fetch main property, but when I `bower install leaflet.markercluster --save`, it doesn't checkout the file _bower.json_ itself.

Temporary solution, add this section in the root of your bower.json (your main module that need leaflet.markercluster) :

```
  "overrides": {
    "leaflet-markercluster": {
      "main": [
        "dist/leaflet.markercluster-src.js",
        "dist/MarkerCluster.css",
        "dist/MarkerCluster.Default.css"
      ]
    }
  }
```

**Comment by danzel** [comment]
Send a PR to fix?

**Comment by cyrilchaponeverysens** [comment]
I have investigated a bit, and have no clue about what is making *bower.json* not checking out. Both `ignore` pattern inside *bower.json itself and `.gitignore` seem valid.

However, the other repo [Leaflet.label](https://github.com/Leaflet/Leaflet.label) just acts same.

oO

**Comment by cyrilchaponeverysens** [comment]
How just got it.

The [released tag](https://github.com/Leaflet/Leaflet.markercluster/tree/0.4) doesn't include the *bower.json* file. Bower is checking out the last semver tag. I can't realy submit a PR since I don't know your releasing process.

**Comment by cyrilchaponeverysens** [comment]
Needa get a proof this is fixed by the build process

**Comment by danzel** [comment]
Assuming this is good now
