### ISSUE TITLE
Spiderleg animation throws warning in Chrome

### ISSUE THREAD

**Issue by ealders** [Leaflet/Leaflet.markercluster#554]
It looks like when the spiderLeg animation is done in Chrome it throws a warning... SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead. This occurs on line 1956 of the src.

**Comment by cyrilchaponeverysens** [comment]
Just, to formalize it a little, [this line](https://github.com/Leaflet/Leaflet.markercluster/blob/a415818d4eb05ab128aad1ea1dae7f09d40fbfe4/dist/leaflet.markercluster-src.js#L1958) of *leaflet.markercluster-src.js* throws the warning  
`/!\ SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.`

**Comment by ealders** [comment]
Sounds good.

**Comment by danzel** [comment]
ah dumb, thanks we'll need to fix this at some stage.

**Comment by DPaaske** [comment]
Does this in any way reduce performance? We've been experiencing and searching through our code to find a performance hindering piece, but if this could explain it, it would be lovely!

**Comment by danzel** [comment]
The only time this code is used is when a cluster is spiderfying and the legs are expanding.

**Comment by danzel** [comment]
Fixed in #585
