### ISSUE TITLE
How to explain the big performance gap between Chrome and IE11?

### ISSUE THREAD

**Issue by fnicollet** [Leaflet/Leaflet.markercluster#557]
Hello,

I am trying to understand why MarkerCluster is so slow in IE11, compared to other browsers.
For instance, the debug page with 10K markers:
http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.10000.html

At initial zoom, both browser perform fine when you pan, no lag.
But if you zoom in a lot, until you only get 2/3/4 clusters, panning works ok in Chrome (just a little pause on mouseup) while IE struggles, freezing the UI for a couple seconds every time, and it seems to get worse and worse as you try to pan.

Do you have an explanation as to why IE and Chrome perform so differently? IE11 is now comparable to other browsers in terms of performances, sometimes even faster so I am wondering why this lib would perform bad in IE.
Is there a specific part of the code which is slow in some interpreter, maybe the intersection test or something?
Does leaflet-1.0 performs better (I have seen in a presentation that creation of LatLng is 8x faster for instance)?

Thanks for your help,
Fabien

**Comment by IvanSanchez** [comment]
Maybe you can have a look at what's eating IE's time:
https://msdn.microsoft.com/en-us/library/dn255005%28v=vs.85%29.aspx

**Comment by fnicollet** [comment]
Hello Ivan and thanks for the suggestion,

It gives some interesting results. I took a piece of time when the app was at 0 FPS, with a message telling me that there was blocking long-running script. Here is a sample call stack:
![image](https://cloud.githubusercontent.com/assets/1240481/10026688/7c461900-6163-11e5-883e-d379598d59ea.png)

Continued:
![image](https://cloud.githubusercontent.com/assets/1240481/10026696/889a7fc0-6163-11e5-8a3c-4b940179b64f.png)

addDoubleTapListener? Seems to be in leaflet's code
Also, not sure that recursion should be that big?

Fabien

**Comment by fnicollet** [comment]
Note that my screen is a touch screen so even if is a laptop, L.Browser.touch is true

**Comment by IvanSanchez** [comment]
Nah, all that recursion is right (a marker is inside a cluster inside a cluster inside a cluster ... inside a cluster).

You should definitely try out 1.0.0-beta1 and see if the results are different. Trying to debug this kind of behaviour in 0.7.x will just give us headaches :-S

**Comment by fnicollet** [comment]
Looks like markercluster is not yet compatible with leaflet-1.0.
It is looking for L.FeatureGroup.EVENTS which existed in 0.7 from a LayerGroup mixin but don't exist anymore. Have to look further ...

**Comment by fnicollet** [comment]
Just tried it with "1.0.0-beta.2" and the markercluster "leaflet-master" branch.

The results are impressive, there is no freeze anymore in IE11! I think the leaflet-master branch is just a compat branch with no changes so the changes probably come from leaflet itself!

Well at least I have my answer, in case of performance issue, migrate to leaflet 1.x :)

**Comment by IvanSanchez** [comment]
@fnicollet :+1:

**Comment by fnicollet** [comment]
will allow me to play with your leaflet-rotate ^^

**Comment by IvanSanchez** [comment]
@fnicollet Be careful of the bugginess!

**Comment by fnicollet** [comment]
Will be!

On Tue, Sep 22, 2015 at 9:47 PM, Iván Sánchez Ortega <
notifications@github.com> wrote:

> @fnicollet <https://github.com/fnicollet> Be careful of the bugginess!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet.markercluster/issues/557#issuecomment-142398832>
> .
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20

**Comment by danzel** [comment]
haha awesome :)
