### ISSUE TITLE
Script becoming unresponsive on Firefox with large dataset

### ISSUE THREAD

**Issue by DanSorahan** [Leaflet/Leaflet.markercluster#560]
Issue reported by user stating they receive a error message stating that marker cluster has become unresponsive. This issue occurs on a 8,822 point dataset, while running on 3.2GHz i3-550.

**Comment by danzel** [comment]
I'm going to steal the leaflet contributing guide.
https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md
