### ISSUE TITLE
Icon color while being clustered

### ISSUE THREAD

**Issue by emakarov** [Leaflet/Leaflet.markercluster#561]
In my project, color of icon is changing dynamically.
And we have such bug - 
Icon is yellow, we zoom out, icons are clustered.
Icon that was yellow becomes red 
But when we zoom in, it still becomes yellow.
So cluster somehow remember "old marker icon" state and shows it instead of new
Color is actually background color of html (icon is htmldiv).
So basically, icon keeps old html

**Comment by danzel** [comment]
How are you changing the color of the icon?

**Comment by emakarov** [comment]
we used direct DOM html change of each icon and I think maybe this is the issue. 
Investigation shown that when markers aggregated into a cluster, DOM elements of icon are removed. 
I will try to change the logic using leaflet methods. Is there anything to add from your side?

**Comment by danzel** [comment]
You are on to it.
When markers are merged in to clusters and expanded out from clusters they are removed and added to the map.
When this happens leaflet will remove and re-create their icon from their icon object, losing any custom html changes.

If you change the icon instead - use setHTML or setClass on the icon (I think they are methods?) then everything should work correctly.
