### ISSUE TITLE
Leaflet Js: openPopup won't show

### ISSUE THREAD

**Issue by xefiji** [Leaflet/Leaflet.markercluster#567]
Hello,

i've been reading around for a while and still haven't found a solution to my issue.

I have a GeoJson that i load in a map. I use markers clusters to group all the features. I bind popups to those markers and that works fine: popups show on click, no problem.

I build a custom control area in which i have two inputs, to filter my geojson datas regarding their price (min and max); then i load a result list below -> that works fine also, and when i mouseover a marker, i can highlight the result-list's item.

My problem: i want to open the marker's popup in the map when i click on the result-list's item that correspond to it. But popup doesn't show. Map paning seems ok, as the map is recentring toward the marker. Even the popup datas are loaded (which i can see with a console.log(layer.getPopup())). But still no popup popping.

Here is a jsfiddle http://jsfiddle.net/n3pkzcm7/4/. The openPopup() call is at line 88 in _getHtmlList function.

**Comment by ghybs** [comment]
Bonsoir xefiji,

Whenever you need some help / troubleshooting for your project, I think the most appropriate place would be the [Leaflet forum](https://groups.google.com/forum/#!forum/leaflet-js).

If you definitely pin down the issue to come from the library, then would be the time to open an issue in here.

For your project, getting rid of the MCG and directly using your geojson layer gives the same problem: http://jsfiddle.net/n3pkzcm7/5/

Good luck.

**Comment by xefiji** [comment]
You're absolutely right ghybs thank you. I will post this in the forum, which i hadn't found before that.
Best.
