### ISSUE TITLE
Marker opacity resets to 1 in leaflet-master branch

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet.markercluster#569]
Apparently the `leaflet-master` branch reintroduced #312 as a regression. Working on it.

**Comment by IvanSanchez** [comment]
Hm, I think the real issue is the `leaflet-master` branch being too out of sync with `master`... :-/

**Comment by danzel** [comment]
All the ```RememberOpacity.js``` tests pass on master now, so should be fixed.
