### ISSUE TITLE
Allow for moving markers without removing and re-adding them

### ISSUE THREAD

**Issue by github12345** [Leaflet/Leaflet.markercluster#57]
> If you are going to move a marker that is in a L.MarkerClusterGroup you must remove it first, then move it, then re-add it. If you move it while it is in the MarkerClusterGroup we can’t track it and that marker will become lost.

Unfortunately, this has some drawbacks: if the popup is open, it will be closed, and there is no nice panning animation if the popup leaves the visible area. Also, there is a huge performance penalty if the marker is still in range of its clusters.

Therefore, it would be great if Leaflet.markercluster supported moving markers, e.g. by a move() function, or by hooking into setLatLng().

Use case: vessel tracking (with up to 30k ships); vessels move small distances only, therefore they seldomly leave their clusters.

**Comment by emakarov** [comment]
Could you please update how to move markers properly now?

**Comment by danzel** [comment]
You move them with ```marker.setLatLng``` and it all works magically. (hopefully)

**Comment by hypergreatthing** [comment]
is this code still in the master branch?
I pulled down the latest git repository and didn't see it.  Manually adding it doesn't seem to work...

**Comment by danzel** [comment]
Not the master branch, the ```leaflet-master``` branch

**Comment by hypergreatthing** [comment]
Thanks.  Got it working.  Just FYI the dist files aren't right in the leaflet-master branch.  The source files worked fine and recompiling to the dist using jake also worked.  Otherwise some error keeps on popping up.

**Comment by danzel** [comment]
Supported as above, so closing.
