### ISSUE TITLE
Option removeOutsideVisibleBounds actually removes outside visible bounds like mobile

### ISSUE THREAD

**Issue by ghybs** [Leaflet/Leaflet.markercluster#573]
Hi,

As stated in comments of [commit "Return the whole map bounds instead of our size"](https://github.com/Leaflet/Leaflet.markercluster/commit/ba0c2146cac507a7592a7ddc827e18b662514bda), the current implementation of `removeOutsideVisibleBounds` option actually behaves like for mobile devices when set to `false`: it **does** remove markers and clusters which are outside the view port, without any extra padding.

This is due to the use of `map.getBounds()` which gives only the bounds of the view port, not of the entire map.

The previous version of this implementation used `thisGroup.getBounds()`, which builds bounds from all contained markers and non-point layers. Besides a few potential issues (see danzel's comment), it is also quite computational intensive, every time the `_getExpandedVisibleBounds()` method is called, i.e. at every move, zoom and other actions.

Maybe we could use a constant bounds object, like:
```javascript
L.latLngBounds(
    [-Infinity, -Infinity],
    [Infinity, Infinity]
)
```

Demo: http://jsfiddle.net/zn7q7or6/6/

**Comment by danzel** [comment]
Sounds like a possible option. throw a test in and we'll find out?
