### ISSUE TITLE
Tagged release for Leaflet 1.0 beta

### ISSUE THREAD

**Issue by patrickarlt** [Leaflet/Leaflet.markercluster#582]
@danzel it looks like @Eschon has a working version of markercluster for Leaflet 1.0 https://github.com/Leaflet/Leaflet.markercluster/issues/528#issuecomment-122784710. I've also noticed that https://github.com/Leaflet/Leaflet.markercluster/pull/570 seems like it is working toward a 1.0 release.

Do you need any help or assistance with getting a tagged release out the door for 1.0?

**Comment by danzel** [comment]
AFAIK the leaflet-master branch works with 1.0.0, we just need to merge in the changes from master to get sync'd up (as #570 sorta does), not sure what the confusion is in that issue.

I'll get on to this later this week, deciding how to handle #570.
We probably could just tag off master (for leaflet 0.7.X versions) and bring the leaflet-master branch into master, leaflet 1.0.0 is going to release soon right? ;)

CC @IvanSanchez

**Comment by Eschon** [comment]
@danzel The problem seems to be that building from the leaflet-master branch doesn't work for everybody. I have no Idea what I have done different but it works without problems for me.

**Comment by czb** [comment]
The last commit on `leaflet-master` is 7 months old. Is that correct?

**Comment by danzel** [comment]
Yep, there is an open PR to bring in all the latest changes #570

**Comment by czb** [comment]
Any time frame when the latest changes will be pushed to Leaflet 1.0?

I would like to use Leaflet 1.0 as it corrects some bugs with zooming on IOS and also I would like to use the new Refresh feature.

**Comment by danzel** [comment]
soon :tm:
I'll try take a look at it next week. Want to do a fine pass on it.

In the mean time try the branch that PR is coming from.

**Comment by czb** [comment]
Any updates on that? :)

**Comment by lauritzen** [comment]
Would be fantastisc with an update of the 1.0 branch.

**Comment by danzel** [comment]
Dupe #528
