### ISSUE TITLE
README Demo/Debug pages broken

### ISSUE THREAD

**Issue by digitaldavenyc** [Leaflet/Leaflet.markercluster#586]
Both showing an error of `Uncaught ReferenceError: L is not defined`

**Comment by ghybs** [comment]
Hi,

Please can you kindly share the page links?
Maybe Leaflet CDN was unavailable when you opened those pages?

**Comment by digitaldavenyc** [comment]
http://leaflet.github.com/Leaflet.markercluster/example/marker-clustering-realworld.388.html

http://leaflet.github.com/Leaflet.markercluster/example/marker-clustering-custom.html

**Comment by ghybs** [comment]
I could not reproduce your bug sorry.

Please can you check if you have direct access to Leaflet CDN files?
http://cdn.leafletjs.com/leaflet-0.7/leaflet.js
http://cdn.leafletjs.com/leaflet-0.7/leaflet.css

**Comment by danzel** [comment]
Works for me. Going to need more details, I doubt this is actually broken.
