### ISSUE TITLE
Consider adding bulkAddBegin/bulkAddEnd methods

### ISSUE THREAD

**Issue by danzel** [Leaflet/Leaflet.markercluster#59]
Currently when you call addLayer while the MarkerClusterGroup is on the map it will add/remove/update markers on the map as it goes.
Need to investigate if this is a performance issue, if it is then add some new methods:

bulkAddBegin: Stops addLayer from adding/updating/removing layers on the map
bulkAddEnd: Adds all layers that should be on the map to the map.

This is for the cases where you load 1000s more markers via AJAX later.

**Comment by Azmisov** [comment]
Based on @danzel's benchmarks, the optimal cutoff to start using clearLayers would be > 39% of markers getting removed (using exponential interpolation). Would need to do more testing to see if that holds for variable sample sizes, different browsers, and different computers though. But that's probably a good rough number to start with.
