### ISSUE TITLE
NPM release out of date

### ISSUE THREAD

**Issue by dallonf** [Leaflet/Leaflet.markercluster#590]
Just pulled down the latest version from npm and noticed that it didn't support a function for `maxClusterRadius` as the docs mentions. Dug a little deeper and found out that this was introduced in `0.4.0-hotfix-1`. Semver nitpicks regarding adding a feature without bumping the version number aside, the npm package should be updated to include the "hotfix" changes.

**Comment by danzel** [comment]
Sorry, there is a new tag at
https://github.com/Leaflet/Leaflet.markercluster/tree/v1.0.0-beta.2.0
But npm doesn't like this version number, so no new npm package for now :(

```npm ERR! Tag name must not be a valid SemVer range: 1.0.0-beta2.0```

**Comment by jgravois** [comment]
not positive, but i think it might be your trailing [`0`](https://www.npmjs.com/package/esri-leaflet).

**Comment by danzel** [comment]
Yeah quite possibly, pretty certain I'm valid semver.

**Comment by danzel** [comment]
1.0.0 is released
