### ISSUE TITLE
Name for sub-plugin of markercluster?

### ISSUE THREAD

**Issue by ghybs** [Leaflet/Leaflet.markercluster#591]
Hi,

I would like to share a small sub-plugin for Leaflet.markercluster. I have currently named it "[Leaflet.MarkerClusterGroup.Auto](https://github.com/ghybs/Leaflet.MarkerClusterGroup.Auto)", but maybe we can find a name that would be more appropriate?

It essentially makes MCG become compatible with L.Control.Layers, and so with a few other plugins (LeafletSlider…). A demo is available [here](http://ghybs.github.io/Leaflet.MarkerClusterGroup.Auto/examples/autoMCG-controlLayers-realworld.388.html). It works by simply redirecting calls to `map.addLayer` and `map.removeLayer` to the MCG.

I have found these issues that would be addressed by such plugin: #13, #145, #238, #432, #458, #543.

Please what do you think for the name, before it is too late to change?

**Comment by danzel** [comment]
Cool plugin!

Maybe ```Leaflet.MarkerCluster.LayerSupport``` ?

**Comment by ghybs** [comment]
Thank you for the feedback.

Actually I realized that for the use case of L.Control.Layers only, this plugin is quite overkill. A very small plugin for an L.FeatureGroup would be more than enough. Then we could have:
- `Leaflet.FeatureGroup.MarkerClusterSupport` just for L.Control.Layers compatibility.
- `Leaflet.MarkerCluster.LayerSupport` for Control and other plugins compatibility.

**Comment by ghybs** [comment]
Here we go for the simple version, compatible with Layers Control only:
https://github.com/ghybs/Leaflet.FeatureGroup.SubGroup
(I did not mention MCG as it could be used for any other Layer Group)
[Demo page](http://ghybs.github.io/Leaflet.FeatureGroup.SubGroup/examples/subGroup-markercluster-controlLayers-realworld.388.html)

**Comment by ghybs** [comment]
And here is the complex version (virtually compatible with all other Leaflet plugins):
https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport
I did not setup the live demos yet.

**Comment by danzel** [comment]
Ok, cool.

We should mention this somewhere in the markercluster readme so people will hopefully see it :)
