### ISSUE TITLE
refreshClusters not included in dist files

### ISSUE THREAD

**Issue by suurjaak** [Leaflet/Leaflet.markercluster#592]
The files `dist/leaflet.markercluster-src.js` and `dist/leaflet.markercluster.js` have not been updated for a year and as such they lack the new `refreshClusters` functionality.

**Comment by danzel** [comment]
Yep, I don't plan on updating it going forward, we'll do something else but I dunno what yet, something automatic would be awesome and best :)

Having the file in git pollutes our version history and makes the repository bigger.

We use the same build system as leaflet, so follow that guide to get set up:
https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#setting-up-the-build-system

I did a tag with an update a while back:

https://github.com/Leaflet/Leaflet.markercluster/tree/v0.4.0-hotfix.1

**Comment by suurjaak** [comment]
Well, I would still suggest having updated distribution files available, either in git or under releases. Not all people using Leaflet are Node developers.

(The 0.4.0 tag does not have refreshClusters at all.)

**Comment by johnnybaloney** [comment]
:+1: asking as per [gis.stackexchange](http://gis.stackexchange.com/questions/167314/leaflet-marker-cluster-refreshcluster-function-issue) suggestion :-) I also went for the latest release and ended up scratching my head. If there is no chance of having it included right now then perhaps a remark in the documentation would help?

**Comment by cmalven** [comment]
This is very confusing. I'm using v0.4.0 installed via npm (`"leaflet.markercluster": "^0.4.0"`) which points to `"main": "dist/leaflet.markercluster.js",` as its `main` and  bundled through web pack, and `refreshClusters` doesn't seem to be available at all. Spent way too long scratching my head over this one.

**Comment by danielabar** [comment]
I'm also trying to use `refreshClusters`, and using v0.4.0 from npm, via jspm as follows:

```
"leaflet.markercluster": "npm:leaflet.markercluster@0.4.0",
```

Had noticed there was a 0.5.0 release, so tried to update but doesn't seem to be a 0.5.0 in npm.

Does anyone know how to get `refreshClusters` working?

**Comment by danzel** [comment]
You need the `0.5.0` release.
I'll try figure out how to upload it to npm later today.

**Comment by danzel** [comment]
ok should be published now :)

**Comment by danielabar** [comment]
Awesome, thanks for your help and quick reply!
