### ISSUE TITLE
Generate clusters, which are not backed up by present markers

### ISSUE THREAD

**Issue by Tobulus** [Leaflet/Leaflet.markercluster#597]
I'm working with a search-engine for OSM and came across a problem which I'm not sure how to solve elegantly.

In principal, I want to create markerClusters, which are not backed up by markers. That means, I get the information from the server, that a specific region (bbox) on the map contains e.g. 50000 locations which are just markers at different places. Now I want to draw a Cluster element which contains the information "500000", but not by downloading the actual location elements and clustering them. This should be done on-demand, if the user clicks on the clustericon or by zooming. The search-engine is then giving me more informations about how the region is separated into more regions, for which I want to draw again clustericons. 

In some cases, the regions are small enough, that I can easily download everything and cluster it locally. And I also want these clusters (described at the top) to merge with clusters generated with this library. Thats the reason why i want to extend the current library.

I've worked through the code for the last two days and thought about how to integrate this easily, but it seems pretty tough. Do you have any hints for me on this topic?

**Comment by danzel** [comment]
Check out #351 for some details.
I think: do the server side clustering, send the resulting mid/lower level clusters down and cluster those, override the icon creation function so your icons take in to account the amount of clusters contained in these clusters.
When you zoom below their level request lower level clusters for the visible viewport.

**Comment by Tobulus** [comment]
just started, but I think this is working pretty good. Thanks a lot for your help!

**Comment by Tobulus** [comment]
one more question, associated with this whole server-side clustering:

the common scenario is, that a user inserts a query and the server returns information about the clustering. using the tips that you posted i can set up clustericons, which can be clicked so that more information about this area is loaded. the server just returns clustering information, as long as the user clicks on a clustericon, which has a cluster-count bigger than a constant: otherwise the whole items of the area is downloaded.

Now I want to eliminate the action of clicking the clustericons. The workflow should be the same as if the items are already downloaded. So, when I zoom-in the server is queried about the information for the currently viewed clustericons. Is see a few problems here, maybe you can help me:

1) Where should I implement the logic? Do I need a new subclass like in #217?
2) I don't really have information at which zoomfactor a clustericon should be resolved by child-clusters from the server. Should I test this empirically or is there a better way? e.g. at zoom-level=x start to resolve clusters with count > 1000, at zoom-level=x+1 start resolve clusters with count > 800, ....
3) Is this going to work, that i resolve just clusters in the current viewport using the events zoomend/moveend for zooming and dragging?

**Comment by danzel** [comment]
1) You probably need to listen to ```viewreset``` or ```zoom``` events on the map, and load the data then?
I don't think you'd need to subclass markercluster, you should be able to just interact with it.

2) You'll need to remember the area and depth of markers/clusters you have downloaded and fetch more when this data doesn't cover the current view/zoom any more I think?

3) I am pretty certain this will work :)
