### ISSUE TITLE
MarkerClusterGroup with a single marker displays nothing

### ISSUE THREAD

**Issue by Nexus6** [Leaflet/Leaflet.markercluster#60]
If I add two markers, I see them both.  If I add only one, I see no markers.  This is easily reproduced by changing one of the examples such that it adds only a single marker.

**Comment by math4music** [comment]
I think that the bug come back

**Comment by brenykurien** [comment]
> I think that the bug come back

+1

**Comment by christian-beckmann** [comment]
Can you please fix it. Version 1.4.1 is not showing one marker.

**Comment by chogori92** [comment]
It's the same for me. The bug is back.

**Comment by bizouarn** [comment]
I have the same bug.

**Comment by BennyK80** [comment]
I have the same bug.

**Comment by Quanda** [comment]
Was seeing this issue as well. In my case it seemed to be happening because I set the maps `minZoom` and `defaultZoom` to the same value, `4`.

If I lower minZoom to `3` those features with only a single marker now appear as expected.
