### ISSUE TITLE
Class leaflet-cluster-anim remains if removing MCG while spiderfied

### ISSUE THREAD

**Issue by ghybs** [Leaflet/Leaflet.markercluster#605]
If a cluster is spiderfied and the MarkerClusterGroup is removed from map, the `"leaflet-cluster-anim"` remains forever on `mapPane`.

This makes cluster icons **lag behind during zoom in/out** once the group is added back to the map. The class may be added a 2nd time later on, but only 1 instance is getting removed.

Demo: http://jsfiddle.net/ve2huzxw/44/
 1. Click on cluster to spiderfy markers.
 2. Remove MCG from map (using the provided button, do not unspiderfy manually).
 3. Re-add MCG to map (using the provided button).
 4. Zoom in/out.

This seems to be due to [`L.MarkerCluster._animationUnspiderfy()`](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js#L257) which uses a [timeout](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js#L299) to call `group._animationEnd()`, where the class is [being removed](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L1163), but only if the group is still on the map… which is no longer the case since we removed it.

Maybe we could simply use the [`group._noanimationUnspiderfy()`](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js#L390) instead to avoid this issue?

Demo: http://jsfiddle.net/ve2huzxw/46/

**Comment by danzel** [comment]
Yep this fix sounds right.

**Comment by ghybs** [comment]
Fixed with PR #607
