### ISSUE TITLE
Using MarkerClusterGroup along with DeferredLayer plugin issue

### ISSUE THREAD

**Issue by wsenjer** [Leaflet/Leaflet.markercluster#611]
Hi, 
I am trying to use MarkerClusterGroup plugin along with DeferredLayer plugin. 
https://github.com/shramov/leaflet-plugins/blob/master/layer/Layer.Deferred.js

I made a jsfiddle case to illustrate the issue, you can check it here.
http://jsfiddle.net/wSytj/156/

The problem is that I get this error message in the console.
`Uncaught Map has no maxZoom specified`

This error is thrown by the MarkerClusterGroup plugin when it is trying to get the MaxZoom of the map. I guess it is thrown because Google API will be not fully loaded yet.
Here is the code where the problem occurs.

```
if (!isFinite(this._map.getMaxZoom())) {
	throw "Map has no maxZoom specified";
}
```
Exactly at this line:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L495

I will be very grateful if you take a look at this issue.

**Comment by ghybs** [comment]
Hi!

Why not simply specifying that `maxZoom` in the [map options](http://leafletjs.com/reference.html#map-maxzoom), so that it is already there when the Marker Cluster Group is added to the map, without having to wait for the Google Maps layer?

Note that by default, the Google layer from DeferredLayer uses `maxZoom` at 18.

Updated jsfiddle: http://jsfiddle.net/wSytj/158/

Hope this helps.

**Comment by AlexanderUhl** [comment]
Despite this topic has been closed a year ago, I will present a workaround as I was facing similar problem.

Setting maxZoom in the map options doesn't bring up the error but as this option overrides layer options' maxZoom value this has its downsides. I dont use the DeferredLayer plugin but had to deal with the same error as I load the tile layer after everything else.

What you can do is set the layersMaxZoom option without the need of an actual tile layer. This is done by adding the following line right after you init the map:
`map._layersMaxZoom = 19;`

As this is just a temporary value until you add the real tile layer, it doesn't really matter what value you set at this stage. Just care that the value doesn't interfere with your custom settings like disableClusterAtZoom.

**Comment by robertharm** [comment]
@AlexanderUhl thanks a lot for sharing your solution - this issue nearly drove me crazy and your approach seems to work for me now - will add it to the upcoming v3.0 of Maps Marker Pro.
I`d like to offer you a free pro license of our plugin as small way to say thanks for helping us out here - if you´re interested, get in touch via https://www.mapsmarker.com/contact
