### ISSUE TITLE
Handling lot of markers in localstorage

### ISSUE THREAD

**Issue by httpways** [Leaflet/Leaflet.markercluster#615]
Hi,

I'm handling a lot of Markeers, 30K +.

So I would like to store in localstorage my marker list just calling that method:
markers.addLayers(markerList);

I tried to do JSON.stringify(markerList) but I have an error like this:
Uncaught TypeError: Converting circular structure to JSON

Here is the code that I wanted to make work:
sessionStorage.setItem('contacts', JSON.stringify(markerList));
markers.addLayers(JSON.parse(sessionStorage.getItem('contacts')));

Is there any ways to store locally this collection of Leaflet Markers ?

Thanks you

**Comment by ximex** [comment]
Use markerList.toGeoJSON() instead of JSON.stringify(markerList). To add it you could use geojson layer
