### ISSUE TITLE
ability to use L.circleMarker with markerclsuter

### ISSUE THREAD

**Issue by brunob** [Leaflet/Leaflet.markercluster#62]
Hi @danzel  and thanks for your work on this plugin.

I'was trying to play with markercluster by adding L.circleMarker to the cluster but it don't seem possible for now. The map shows ok after loading but I get an error when i try to change zoom level :

```
TypeError: m.setOpacity is not a function
m.setOpacity(1);
leaflet.markercluster-src.js line 970
```

When i look at the code i see that it call setOpacity on the marker object, but unfortunatly this method is not available for L.circleMarker objects.

Do you think that this could be an hadled case for markercluster ?

This issue is more an feature request that a bug report :p

**Comment by shengzheng1981** [comment]
L.CircleMarker.include({
            setOpacity: function(opacity) {
                this.setStyle({
                    opacity: opacity,
                    fillOpacity: opacity
                })
            },

            clusterHide: function () {
                var backup1 = this.options.opacity;
                var backup2 = this.options.fillOpacity;
                this.setOpacity(0);
                this.options.opacity = backup1;
                this.options.fillOpacity = backup2;
                return this;
            },

            clusterShow: function () {
                this.setStyle({
                    opacity: this.options.opacity,
                    fillOpacity: this.options.fillOpacity
                });
            }
        });
