### ISSUE TITLE
Unknown (random) error when zooming on clusters

### ISSUE THREAD

**Issue by mahmoudmy** [Leaflet/Leaflet.markercluster#620]
I'm using this helpful plugin in my web application. Sometimes when I click on a cluster or zooming in map, the following error occurs and I can not pan the map and also the clustering doesn't work anymore!
```javascript
TypeError: this._map is undefined
	this._map._panes.markerPane.removeChild(this._icon);
```
**leaflet-src.js (line 3623, col3)**
	
 Any Idea?

**Comment by IvanSanchez** [comment]
This is not enough information to know what's going on. Please provide a stack trace (using `leaflet-src.js` instead of `leaflet.js`) and/or a test case that demonstrates the bug (e.g. using [JSFiddle](http://jsfiddle.net/) or [JS Bin](http://jsbin.com/)).

**Comment by danzel** [comment]
^^ Reopen or create a new issue when these details are provided. Thanks.
