### ISSUE TITLE
Missing "main" attribute in ".bower.json"

### ISSUE THREAD

**Issue by raphaelyancey** [Leaflet/Leaflet.markercluster#621]
When installing the package from Bower, the `.bower.json` file is missing a `main` attribute. This attribute is particularly used by build systems to automatically link scripts & stylesheets off the Bower directory inside an `index.html` file.

`.bower.json` as I got it from Bower using `bower install leaflet.markercluster`
```
{
  "name": "leaflet.markercluster",
  "homepage": "https://github.com/Leaflet/Leaflet.markercluster",
  "version": "0.4.0",
  "_release": "0.4.0",
  "_resolution": {
    "type": "version",
    "tag": "v0.4.0",
    "commit": "20cf8edd0dfc51ace1db1eee0cf34cf0533a2fb9"
  },
  "_source": "git://github.com/Leaflet/Leaflet.markercluster.git",
  "_target": "~0.4.0",
  "_originalSource": "leaflet.markercluster",
  "_direct": true
}
```

I do noticed that this attribute is present in the `bower.json` though.

**Comment by IvanSanchez** [comment]
See #553.

**Comment by IvanSanchez** [comment]
The current `bower.json` file does have a `main` section: https://github.com/Leaflet/Leaflet.markercluster/blob/master/bower.json#L9 so I doubt there is any action to be taken.

**Comment by danzel** [comment]
Yep, sounds like you got the current release which has this issue. It has been fixed in later commits.
