### ISSUE TITLE
Group of Groups of Markers do not cluster

### ISSUE THREAD

**Issue by ghybs** [Leaflet/Leaflet.markercluster#622]
Hi,

Following [this issue on GIS Stack Exchange](http://gis.stackexchange.com/questions/176641/leaflet-marker-cluster-plugin-not-working), it appears that `addLayer` in Marker Cluster extracts only the first level children when it is passed a Layer Group / Feature Group / GeoJSON Layer Group.

Therefore, if that group contains nested groups, the latter will not cluster (as they would then go straight to `addLayers`, which no longer checks for Groups, concluding that these are non-point layers, hence non cluster-able).

Maybe `addLayer` and `addLayers` could be made more bullet proof by recursively extracting individual (i.e. non-group) layers from groups?

**Comment by danzel** [comment]
Yep that sounds good change, not sure the best way to implement it.
Maybe the loop at the start of addLayer can become a recursive-like function?

**Comment by ghybs** [comment]
Hi,

To cover #623, the modification should also be done on `addLayers`.

Since `addLayers` would be the one doing the job anyway (the group(s) likely have more than one layer), I would even implement the new loop in it, and let `addLayer` do only the first check?
