### ISSUE TITLE
No clustering when using addLayers (multiple layers) in beta release

### ISSUE THREAD

**Issue by rhewitt22** [Leaflet/Leaflet.markercluster#623]
I'm using the beta release of Leaflet and Markercluster.  It appears that adding multiple layers to a cluster using an array does not enable clustering.  The addLayer (singular) works as expected.

Browser: Chrome 47.0.2526.106 (64-bit), same result in FF & Safari
OS: Mac OSX El Capitan
Leaflet: 1.0.0-beta.2
MarkerCluster: 1.0.0-beta.2
**Test Case**: https://jsfiddle.net/0ur1uaxa/2/

**Comment by rhewitt22** [comment]
Workaround: use addLayer more than once

**Comment by danzel** [comment]
Sounds like the same thing as #622 right?

**Comment by ghybs** [comment]
Updated test case with main code of PR #624: https://jsfiddle.net/0ur1uaxa/4/

**Comment by rhewitt22** [comment]
This was a bit of a simpler case than #622 as it didn't involve any layer groups or otherwise nested layers.  In any event it seems like @ghybs has a solution based on the test case above.  Feel free to close when #624 gets merged, and thank you both for your :eyes:
