### ISSUE TITLE
clustermouseout event lost when setting icon with divIcon

### ISSUE THREAD

**Issue by maletor** [Leaflet/Leaflet.markercluster#625]
Setting a divIcon on `clustermouseover` callback prevents the `clustermouseout` callback from happening. I think this is related to #252.

```coffeescript
@clusterGroup = new L.MarkerClusterGroup
@clusterGroup.on('clustermouseover', @clusterMouseOver)
@clusterGroup.on('clustermouseout', @clusterMouseOut)

clusterMouseOver: (e) =>
  marker = e.layer
  icon = L.divIcon
    html: "<i class='icon-people'></i>#{marker.getChildCount()}"
    iconSize: [30, 70]
    className: "marker-cluster"
  marker.setIcon(icon)  

clusterMouseOut: (e) =>
  marker = e.layer
  icon = L.divIcon
    html: "<i class='icon-people'></i>#{marker.getChildCount()}"
    iconSize: [15, 35]
    className: "marker-cluster"
  marker.setIcon(icon)
```

**Comment by danzel** [comment]
You change the icon during the mouse over? That will probably be what causes the issue.
Put a console log in that method, I'd guess it gets continuously called as the mouse will make a new mouse over event every time the icon is replaced.

**Comment by maletor** [comment]
It looks like the issue is caused by adding a div element to the divicon
which obviously doesn't make any sense and the sample code I provided does
not show that. Please feel free to close this issue.
