### ISSUE TITLE
Is it possible to get parent cluster weather near viewport or not?

### ISSUE THREAD

**Issue by weltwinkel** [Leaflet/Leaflet.markercluster#627]
Is there any way to get the coordinates of a (possibly) clustered marker at the current zoom level weather it has been rendered to the screen or not?

**Comment by danzel** [comment]
Nope.
Take a look at ```getVisibleParent```, but instead of looking for ```_icon```, compare ```_zoom```.

https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L565-L571

**Comment by weltwinkel** [comment]
Thanks for the tip danzel, this method solved my problem quite nicely!
        
getParent : function(zoom_level,marker){
            
            var vMarker = marker;
            while (vMarker && vMarker._zoom != zoom_level) {
                    vMarker = vMarker.__parent;
                }
            return vMarker || marker;
        }
