### ISSUE TITLE
Refershing clusters' icon on zoom end

### ISSUE THREAD

**Issue by tduchateau** [Leaflet/Leaflet.markercluster#628]
Hi!

I'm using https://github.com/angular-ui/ui-leaflet with the markercluster plugin.
I have overriden the `iconCreateFunction` function to adapt the cluster icon depending on the contained markers:
````
// Leaflet map configuration
      $scope.map = {
         center: {
            autoDiscover: true,
            zoom: 9
         },
         markers: {},
         layers: {
            baselayers: {
               mapbox: _.clone(leafletService.tileLayers.mapbox.streets)
            },
            overlays: {
               things: {
                  name: 'things',
                  type: 'markercluster',
                  visible: true,
                  layerOptions: {
                     iconCreateFunction: function (cluster) {
                        return customIcon(cluster);
                     }
                  }
               }
            }
         }
      };
````
Now I would like to refresh the clusters' icons when zooming/dezooming.
I'm calling the  `refreshCluster` as follows...
````
leafletData.getMap().then(function (map) {
         map.on('zoomend', function () {
            leafletData.getLayers().then(function (layers) {
               layers.overlays.things.refreshClusters();
            });
         });
      });
````
... but the icons never get refreshed. Is the `iconCreateFunction` function supposed to be invoked when calling `refreshClusters()`?
If you need more details, feel free to let me know.

Thanks!

**Comment by danzel** [comment]
What you've got there looks like it'd work from what I know about this.
Put a breakpoint on refreshClusters and step through and see what is happening?

**Comment by tduchateau** [comment]
My mistake. After deep debugging, the problem was actually coming from my algorithm :-/
Thanks!
