### ISSUE TITLE
Markers/Clusters left on map after using map.setView() in mobile

### ISSUE THREAD

**Issue by grantlucas** [Leaflet/Leaflet.markercluster#63]
Came across a weird issue last night which happens when testing the map out on an iPad. I haven't been able to reproduce this in a desktop environment.

Circumstances:
- I have cluster markers which on first page view are off the visible map
- All's well when zooming in and out from these markers in normal usage
- I have a "reset view" button on my map which returns the map back to the initial starting point using map.setView()
- If I'm zoomed in on markers/cluster which will be off the map after resetting the view, they are stuck there until I refresh or zoom all the way in and then out again.
- The clusters are still properly calculated but have the addition of these left over clusters or markers on the map

I've uploaded a photo walk through as what I'm describing may not make complete sense.

Images with notations can be found at  http://imgur.com/a/72Nyp

If you need any more information at all just let me know. I know how much of a pain these types of bugs can be to track down :s

Grant

**Comment by MelloDredd** [comment]
@danzel ... i have a similar weird issue. When resetting map view center the map readjusted but the cluster layer stays where it was just before map reset.

1. initial map with cluster (fig-1)
2. zoom in
3. reset map center includes setting lat lng for map center and zooming (page change action listener)
4. map center and zoom does reset but the cluster layer stays a bit top/down/side where it was just before resetting map. (fig-2)

btw .. i am using google map as base layer. i am thinking about refreshing the layer. i tried removing and adding the cluster layer. but it didn't work. can you give me any clue ?? please ... its quite emergency.

![cluter layer wrong position -- fig 02](https://cloud.githubusercontent.com/assets/8975327/7344552/5c639318-ecee-11e4-8b2d-b4744ac8392b.PNG)
![map initial state -- fig 01 1](https://cloud.githubusercontent.com/assets/8975327/7344553/5c63cb6c-ecee-11e4-8ace-aed29f959d73.PNG)

**Comment by danzel** [comment]
Try with a normal tile layer instead of gmaps.
And make a new issue with all your findings and a jsfiddle to reproduce.
