### ISSUE TITLE
Compiled code of the version compatible with Leaflet 0.7.x isn't updated

### ISSUE THREAD

**Issue by clementprdhomme** [Leaflet/Leaflet.markercluster#630]
Hi all!

I'm currently integrating the library within a project that uses the version 0.7.3 of Leaflet and noticed that it was impossible to "spiderfy" a marker at any level zoom as described the the README.md:
> Note: the spiderfy occurs at the current zoom level if all items within the cluster are physically located at the same latitude and longitude.

What happens is that the source code is frequently updated and that the compiled isn't (the `/dist` folder):
![Current tree of the project](https://cloud.githubusercontent.com/assets/6073968/12558736/7dd6f98e-c391-11e5-9b54-00c1f9992b11.png)

In my case, if you look at the method `_zoomOrSpiderfy`, you will see that the code differs and that one (the source) enable the "spiderfy" effect at any level zoom, whereas the other one is outdated (the compiled):
[Source 👍🏼] (https://github.com/Leaflet/Leaflet.markercluster/blob/leaflet-0.7/src/MarkerClusterGroup.js#L711) - [Compiled 👎🏼] (https://github.com/Leaflet/Leaflet.markercluster/blob/leaflet-0.7/dist/leaflet.markercluster-src.js#L661)

Could you compile the source whenever you update the code base or just add a note to the README.md so people won't be confused about the features the library offers?

Thanks,
Clément

**Comment by danzel** [comment]
Thanks for the bump.

I've removed the built JS from master now, we will only ship it in tags.
I've done a final build for that branch now too so there is one somewhere..
