### ISSUE TITLE
Using Leaflet Draw in conjunction with marker clustering

### ISSUE THREAD

**Issue by SwagMuffinMcYoloPants** [Leaflet/Leaflet.markercluster#631]
I'm trying to get marker clustering to work with Leaflet Draw and I noticed an issue when you edit a marker's position on a map.  When I tried to do the following, I didn't get the results I expected.

1.Draw two markers relatively close to each other.
2.Draw a third marker slightly farther away so that it won't cluster with the other two markers when zoomed out.
3.Edit one of the two markers in Step 1 to be farther away from the marker drawn in Step 2.

For some reason, the initial two markers will still cluster as if they were still next to each other even though the third marker is closer.  Am I supposed to be doing something on my end to update the clustering?

**Comment by danzel** [comment]
Don't point leaflet.draw at a markerclustergroup layer. All sorts of weird things will happen. This is not supported sorry.

**Comment by SwagMuffinMcYoloPants** [comment]
Oh.  I've been using the leaflet marker cluster plugin indirectly through ui-leaflet which is just an AngularJS directive using Leaflet.  I started reading more and more into the source code and found out that it doesn't change the draw layer to a marker cluster group.  It actually adds the same layer to the draw layer and the marker group.  

I tried to make an equal comparison to what ui-leaflet does without AngularJS in the following Plunker.
https://plnkr.co/edit/5c3YvDcOyd9iWhzWFLgC

Is using the same layer to add to two different feature groups also not recommended?

**Comment by danzel** [comment]
Adding a marker to two layers sounds really dodgy. I don't think you should do that.

**Comment by SwagMuffinMcYoloPants** [comment]
How should I do edit a marker's location or is it something that should never change?

**Comment by danzel** [comment]
The 1.0.0 branch of marker cluster supports that, just use ```setLatLng```.

**Comment by SwagMuffinMcYoloPants** [comment]
So I can't just set a marker's draggable option to be true?

**Comment by danzel** [comment]
That should work I think, but haven't tested it.

**Comment by SwagMuffinMcYoloPants** [comment]
I can't seem to get the Marker Clustering to work by dragging markers.  I keep getting errors that the latlng values don't exist.  I noticed that in the following lines of code while I was debugging that the oldLatLng object isn't populated when you drag a marker.
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L662-L668
```
_childMarkerMoved: function (e) {
		if (!this._ignoreMove) {
			e.target._latlng = e.oldLatLng;
			this.removeLayer(e.target);

			e.target._latlng = e.latlng;
			this.addLayer(e.target);
		}
	},
```

Would removing and re-adding the layer cause issues for dragging?  I would think that the removal and addition of the layer would cause the drag event to come to a halt.  


I tried fixing it by adding the following to the _childMarkerMoved function:

```
_childMarkerMoved: function (e) {
		if (!this._ignoreMove && !(e.originalEvent instanceof MouseEvent)) {
			e.target._latlng = e.oldLatLng;
			this.removeLayer(e.target);

			e.target._latlng = e.latlng;
			this.addLayer(e.target);
		}
	},
```

By doing this childMarkerMoved will only be called if it's not a mouse event so that draggable doesn't get caught up in this method.  

As for draggable, I added two listeners for drag start and drag end.

```
	_storeDragStart : function(e){
	  this._startPosForDrag = e.target._latlng;
	},
	
	_onDragEnd : function(e){
		  if (!this._ignoreMove) {
		  var newLatLng = e.target._latlng;
			e.target._latlng = this._startPosForDrag;
			this.removeLayer(e.target);

			e.target._latlng = newLatLng;
			this.addLayer(e.target);
		  }
		},
```

I'm not sure if I need to remove and add the listener the way that I did.  I did it because it was what was done in the move function.  It also seems to be where all the clustering logic is located at.  I added the listener creation where the move listener was added.

```
layer.on('move', this._childMarkerMoved, this);
layer.on('dragstart',this._storeDragStart,this);
layer.on('dragend',this._onDragEnd,this);
```

I made a Plunker here.  

https://plnkr.co/edit/Egpr54ZDEyjqEenZo8d4?p=preview

**Comment by danzel** [comment]
Maybe leaflet doesn't populate oldLatLng when a marker is dragged? Check it in the stack trace.
When you manually call ```setLatLng``` it should get set, so maybe leaflet bug?

**Comment by SwagMuffinMcYoloPants** [comment]
I already did that.  It fixes the strack trace but I still have the issue where the clustering happens according to the marker's original location.  It's in the first plunker of my last post.  https://plnkr.co/edit/fkjjQif6wXapSN9SQwjZ?p=preview

I added oldLatLng in that plunker.
```
	_onDrag: function (e) {
		var marker = this._marker,
		    shadow = marker._shadow,
		    iconPos = L.DomUtil.getPosition(marker._icon),
		    latlng = marker._map.layerPointToLatLng(iconPos);

		// update shadow position
		if (shadow) {
			L.DomUtil.setPosition(shadow, iconPos);
		}

        e.oldLatLng = marker._latlng;
		marker._latlng = latlng;
		e.latlng = latlng;

		marker
		    .fire('move', e)
		    .fire('drag', e);
	}
```

**Comment by danzel** [comment]
Your latest plnkr seems to work correctly with whatever changes your done AFAICT?

**Comment by SwagMuffinMcYoloPants** [comment]
Looks like forking the plunker doesn't give it a new ID when you fork the plunker.  It keeps sending me to the wrong Plunker.  The Plunker you're looking at is the fixed version.

**Comment by danzel** [comment]
Ah ok, so fixing this bug requires the dragging change in leaflet and the event type check in marker cluster?
Send some PRs :)

**Comment by danzel** [comment]
Dragging markers is working again as of 1.0.1
