### ISSUE TITLE
Zoom to bounds

### ISSUE THREAD

**Issue by ayozebarrera** [Leaflet/Leaflet.markercluster#633]
Hi.

I have spiderfyOnMaxZoom to false, and disableClusteringAtZoom 13 and all works great except if I click the cluster on zoom 13 it wont uncluster (ignore my click).

I know if I click the cluster in zoom 13, it should spiderfy but If I disabled it, it shouldn't zoom?

thanks

**Comment by danzel** [comment]
```disableClusteringAtZoom``` should mean there are no clusters at zoom 13.

Can you please post a reproducable test? (jsfiddle or similar) thanks

**Comment by ayozebarrera** [comment]
I can't at the moment.

You're right. I mean in the zoom 12.

In the "last zoom" of clustering, usually If you click it spiderfy the markers. But if you disable spiderfy, then if you click the clusters in that "last zoom", it wont do anything

**Comment by danzel** [comment]
Fixed by #657
