### ISSUE TITLE
Partial server pre-computation

### ISSUE THREAD

**Issue by akre54** [Leaflet/Leaflet.markercluster#636]
We have a dataset with 250k points that we want to turn into a clusterable, searchable map.

Is there a way to combine markercluster with some server-side pre-computation? I'm thinking it might involve some way to tap into markercluster's circle drawing / labeling, and lazily fetch any data past a certain zoom level. Any ideas?

**Comment by danzel** [comment]
Have a search through the issues, this gets asked fairly often.
Probably #597 is a good place to start and the other issue I linked to from there.
