### ISSUE TITLE
Why is leaflet listed as a dependency in package.json?

### ISSUE THREAD

**Issue by sebastian-nowak** [Leaflet/Leaflet.markercluster#639]
Leaflet is listed as a dependency in `package.json`. Why? Leaflet.markercluster can be build without it. Listing Leaflet in `package.json` results in Leaflet being downloaded by npm and not used at all, what's the point here?

I understand that it was listed there to specify what Leaflet version is required, but that's not how `package.json` works. It won't enforce the version used by the developer, it just downloads it into `node_modules` and does nothing. Waste of bandwidth and disk space.

Take a look at other Leaflet plugins, they're not listing any dependencies at all - and that's the way it should be done:
https://github.com/Leaflet/Leaflet.fullscreen/blob/gh-pages/package.json
https://github.com/Leaflet/Leaflet.label/blob/master/package.json

**Comment by ghybs** [comment]
Testing?

**Comment by sebastian-nowak** [comment]
`devDependencies` are for testing, not the `dependencies`.

**Comment by ghybs** [comment]
True.
Maybe a mistaken re-use from Bower then, which behaves differently.

**Comment by danzel** [comment]
Cool please send a PR.
You won't get far if you have leaflet.markercluster without leaflet, but it sounds like that isn't the point of that field :-S

**Comment by yohanboniface** [comment]
Closed by #658
