### ISSUE TITLE
Pause clustering when move/add new markers

### ISSUE THREAD

**Issue by elbowz** [Leaflet/Leaflet.markercluster#640]
Hi,

I would like know if there is some way to:
*pause the clustering "process"
*add or move some markers without that these markers are included in the cluster icons
*unpause the clustering (the markers are included)

thanks!

**Comment by danzel** [comment]
Nope, just don't add or move them until you want them?

**Comment by elbowz** [comment]
Yeah, I have solved in the past days...thanks
