### ISSUE TITLE
Problematic animations on zoom

### ISSUE THREAD

**Issue by czb** [Leaflet/Leaflet.markercluster#646]
Often I experience that when zoom in or out in Windows / Chrome the markers are updated without animation. I have traced the problem to

```
//In case we are starting to split before the animation finished
this._processQueue();
```

in `_mergeSplitClusters`. When I comment it out, the animations are nice and smooth.

I think the problem is that due to timing the order of calling `_mergeSplitClusters` and `this._enqueue` in `_animationZoomIn` and `_animationZoomOutSingle` is somehow reversed.

So you call `this._enqueue` and just after that you somehow call `_mergeSplitClusters` which kills that animation immediately and not after 300ms.

ps: just to make sure, I zoom by one step and then wait and then zoom again by one step and wait, so animation should be finished by that time when I zoom again.

EDIT:
ok, the problem is that `_zoomEnd` is sometimes fired twice just after each other and this makes the problem. So it is probably bug in `leaflet`?

EDIT2:
the problem is described here: 
https://github.com/Leaflet/Leaflet/issues/4023

**Comment by danzel** [comment]
Fixed in leaflet
