### ISSUE TITLE
clustering with geojson

### ISSUE THREAD

**Issue by fils** [Leaflet/Leaflet.markercluster#650]
I am using the code example at:  http://jsfiddle.net/drfils/4nyfp2s3/6/

which is based on my research on the net and the kind examples others have shared.  

The GeoJSON is at:  http://opencoredata.org/api/v1/spatial/expeditions

It is big so I have been hoping I could get it to cluster.  I just never seem to be able to get the cluster option to work.  The markers display fine and I get no errors reported my Chrome.  I just don't see the behavior I am looking for.

**Comment by danzel** [comment]
I think you need a version of MCG with this fix #624
Looks like the geojson contains nested layers

**Comment by fils** [comment]
@danzel Thanks..  I pulled the 1.0.0beta2 from https://github.com/Leaflet/Leaflet.markercluster/releases  Is there a way to get a new version from a dist, or do I need to git clone and build from the repo?  I've never used jake before, is that what I use?

**Comment by danzel** [comment]
Yeah 1.0.0beta2 doesn't have the fix.

Didn't realise we don't have the build process documented :(
https://github.com/Leaflet/Leaflet.markercluster/blob/master/CONTRIBUTING.md#building
Check out master and try that out.

**Comment by fils** [comment]
@danzel Thanks..   I pulled and built that with no problem..  incorporated it in my work locally and it's clustering fine.  Not sure how I could update the fiddle though with that build easily.   
Screenshot is proof enough...

The popup dialogs don't seem to be working anymore, but I will investigate that..  might be a known thing..  I will research that and if I still have issues will raise another issue if it seems appropriate.  

Thanks much for the quick help, really appreciate it!  
This sure makes a WORLD of difference in performance!

![screen shot 2016-03-22 at 9 47 42 pm](https://cloud.githubusercontent.com/assets/57170/13974266/47832236-f078-11e5-8f09-33d283e0221c.png)

**Comment by danzel** [comment]
Awesome, good to hear.
