### ISSUE TITLE
Calling setLatLng on marker causes marker popup to close

### ISSUE THREAD

**Issue by krumware** [Leaflet/Leaflet.markercluster#651]
using latest master: #d91addd7bd37d926cf7ce032e6a3e35d774ecdcb
Using leaflet latest

(also verified with earlier #44963c185116e38b1dc54fc9b8a42e1e118f66e6)

Calling setLatLng (with new lat lng) on marker causes its bound popup to close.  This only happens to markers that have been added to a MarkerClusterGroup.

With default leaflet functionality on markers that have been added directly to map or to layerGroup, when setLatLng is called the popup remains open and moves with the marker to its new location.

As an additional remark for potential related issue: Calling setLatLng on a marker that is currently within a spiderfy group also causes the spiderfy group to collapse, but unsure of the desired functionality.

**Comment by icrm-amusienko** [comment]
Temporary solution is:
			var isPopupOpened = marker._popup.isOpen();
			marker.setLatLng([x, y]).update();
			if (isPopupOpened) {
				marker.openPopup();
			}
It is not good because we use private _popup variable, but I didn't found other way to fix the issue.

**Comment by danzel** [comment]
Pushing a 'fix' for this where we just embed the temporary solution.
MarkerCluster removes and re-adds the layer when it is moved to recluster it, which causes the popup to be closed.

If you move the marker in to a cluster, the popup will still close.
