### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by fabriziomazzoni** [Leaflet/Leaflet.markercluster#652]
Hi. I have installed the plugin with bower as per docs but it is actually installing the version for 1.0.0b2. I'm not an expert in bower, but shouldn't there be a different install command for latest version?

**Comment by danzel** [comment]
The 1.0.0 beta versions aren't on any of the js distribution things. 
Grab it from here instead:
https://github.com/Leaflet/Leaflet.markercluster/tree/v1.0.0-beta.2.0
