### ISSUE TITLE
How to expand a spiderfied a cluster markers group. 

### ISSUE THREAD

**Issue by wsenjer** [Leaflet/Leaflet.markercluster#659]
Hello, 

I'm building a website where I need to expand a spiderified a cluster markers group on a specific action from the user. I understand that the cluster group will be expanded when the user clicks on it. 
But I couldn't perform that programmatically. 

![screenshot from 2016-04-05 01 02 00](https://cloud.githubusercontent.com/assets/132250/14265493/75f2e9d8-faca-11e5-9869-741245f362ff.png)

Any ideas or advice?

**Comment by danzel** [comment]
The method is ```myMarkerCluster.spiderfy()```, but first you need to get the cluster. (Will add this to the docs now...)

If you listen to the ```clusterclick``` event you get passed the cluster, or you can use ```getVisibleParent```
https://github.com/Leaflet/Leaflet.markercluster#getting-the-visible-parent-of-a-marker
