### ISSUE TITLE
Is it possible to zoom in to one specific marker ?

### ISSUE THREAD

**Issue by httpways** [Leaflet/Leaflet.markercluster#660]
Hi,

I would like to know if it is possible to zoom in to a specific marker automatically ?

myMarker.zoomin() ?

Thanks for your help

**Comment by ghybs** [comment]
[`group.zoomToShowLayer(myMarker)`](https://github.com/Leaflet/Leaflet.markercluster#other-group-methods)?

**Comment by httpways** [comment]
It works indeed, :)

Thank you very much!
