### ISSUE TITLE
Animation is not working

### ISSUE THREAD

**Issue by zatziky** [Leaflet/Leaflet.markercluster#662]
Hello,
with the below setup I can't see the nice animations like the ones from the example - http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html. With animation enabled such as:

```
L.markerClusterGroup({
  animate: true,
  animateAddingMarkers: true
});
```

The `L.DomUtil.TRANSITION` has this value: **webkitTransition**

I still don't see any animations. Is it the problem that I am using AngujarJS or is it something else?

**Comment by danzel** [comment]
I don't know. Maybe?
Have you included the css?

**Comment by zatziky** [comment]
@danzel You were right I was only missing the CSS file. Thank you!

**Comment by maximou4391** [comment]
Hi @danzel ,

I'm using you great library, however even on your example (http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html ) the animation is not always done. sometimes the markers just appear without animation and sometimes the animation is working. 

Is it normal, do you experience the same behavior?

**Comment by aanti** [comment]
@maximou4391 I have the same issue in my app, did you solve this problem? In my case the example works just fine, the problem occurs only in my own app so I'm not sure who's guilty, me or the library ;)

**Comment by maximou4391** [comment]
Hi @aanti, for the problem was that I was not using the latest version of the lib... Sorry for my dummy question.
Hope this can help you.

**Comment by peterkowalsky333** [comment]
By me also the animation is not working.But the css is imported and i have the same configuration for markerClusterGroup.
On the documentation page is not explained how can i make the L.DomUtil.TRANSITION to have the webkitTransition value.
I guess i am missing that part.Please help

**Comment by peterkowalsky333** [comment]
i tried L.DomUtil.TRANSITION = 'webkitTransition'; but it is still not working.

**Comment by bpatrik** [comment]
Run into the same issue. The solution for me was to include both `MarkerCluster.Default.css` and  `MarkerCluster.css` (this contains the transitions).

**Comment by joric** [comment]
> Run into the same issue. The solution for me was to include both `MarkerCluster.Default.css` and `MarkerCluster.css` (this contains the transitions).

THIS. This MUST be in README. Because first thing you do you go to CDN and you paste the headers but there's only Default.css. Have to be right after the animate option, something along the lines if you don't include the second css your animation won't work.

**Comment by IvanSanchez** [comment]
@joric Pull requests are welcome.
