### ISSUE TITLE
leaflet.markercluster-src.js is missing

### ISSUE THREAD

**Issue by riostevenson** [Leaflet/Leaflet.markercluster#663]
Leaflet.markercluster-src.js is missing from dist folder and so non of the examples work please help

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster/blob/master/CONTRIBUTING.md#building

We only ship built files in tags now:
https://github.com/Leaflet/Leaflet.markercluster/blob/v1.0.0-beta.2.0/CONTRIBUTING.md
