### ISSUE TITLE
Is it possible to show popup with markers inside cluster

### ISSUE THREAD

**Issue by zinotinder** [Leaflet/Leaflet.markercluster#664]
When I click on marker cluster on last zoom spiderfy works fine but I need something different.
Is it possible to:
- Detect click on marker cluster icon (what event),
- Open popup,
- Get all markers inside that cluster (so I can print them inside popup)

I am using this plugin with ui-leaflet plugin.

Thanks

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster#events
