### ISSUE TITLE
Reorganize versions, publish 1.0 supported version on npm

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet.markercluster#666]
- The most current version of markercluster on npm is from two years ago, has version number 0.4.0.
- It doesn't support Leaflet 1.0 and ends in a cryptic messages of Trim not supported on undefined. This is the root cause of https://github.com/Leaflet/Leaflet/issues/4422 which no one knew why is happening. (and also https://github.com/Leaflet/Leaflet/issues/2408)
- The readme says user should use bower, yet bower is discouraged by current Leaflet recommendations.
- The 1.0 supporting master is still on 0.4.0 version number, just like the old 0.7 build.
- The 0.7 branch is on 0.5.0 version (!), which is also what you get on bower.
- brainmelt :-(

We should discuss how to handle markercluster, since it's an official repo and has 1400+ stars.

As a temp workaround I published a "built" branch, so users can just use:
```
"leaflet.markercluster": "hyperknot/Leaflet.markercluster#built"
```
in their package.json to support Leaflet 1.0. Ideally something like this should be pushed on npm with version number 0.6.0 or something.

@mourner @perliedman @IvanSanchez @yohanboniface What do you think we should do?

**Comment by yohanboniface** [comment]
I'd say let's publish a 1.0.0-rc1 to follow Leaflet. I'm doing that with Leaflet.Editable over the week-end.

**Comment by danzel** [comment]
I've pushed up 0.5.0 to npm (final 0.7 compatible release).
Doing the other bits now too ^^

- [ ] Update version number
- [ ] Create a 1.0.0-rc.1 tag (with built js)
- [ ] npm publish 1.0.0-rc.1

**Comment by danzel** [comment]
I'm not sure we should be matching leaflet version numbers, as when we change things we will want to bump our version number, and then we won't line up.
But will go with it for now.

**Comment by danzel** [comment]
Ok, should be able to npm install this tag using:
```
npm install leaflet.markercluster@1.0.0-rc.1.0
```
(extra `.0` because I published the `.1` which updated the latest tag, which was bad, so I unpublished that version but you can't reuse version numbers...)

**Comment by danzel** [comment]
Ok, think this is all done now :)

**Comment by yohanboniface** [comment]
Excellent, thanks @danzel :)

> I'm not sure we should be matching leaflet version numbers, as when we change things we will want to bump our version number, and then we won't line up.

Agreed!
But I think bumping to 1.0.0 make sense for this long used plugin :)
But then I agree plugins should not follow leaflet version number.

**Comment by almereyda** [comment]
Also in a way the increase represents a breaking change within the lineup
of releases, which is justified by a semantic versioning approach.
