### ISSUE TITLE
On click, max zoom around a cluster's center point

### ISSUE THREAD

**Issue by rey-awesense** [Leaflet/Leaflet.markercluster#667]
I have a use case in which a user would like to click on a cluster to max zoom around its center point. This can be easily done with a listener on `clusterclick` but was wondering if this could be considered an additional feature to the already available `zoomToBoundsOnClick`  and `zoomToShowLayer()` alternatives. 

I have forked this repo and added the described behaviour. Would anyone find this useful?

**Comment by danzel** [comment]
This can easily be implemented in user code, I don't think this should go in the core codebase.
