### ISSUE TITLE
Counting one marker as many

### ISSUE THREAD

**Issue by lstanczak** [Leaflet/Leaflet.markercluster#668]
Hello, first of all thanks for this great plugin. 

I have a question if it would be possible to add feature allowing one marker to be counted as many. I would like to add one marker (single coordinates and a label) that would be counted in cluster as lets say 10000. 

Idea behind it is to track number of service calls - there are single clients that do 10000 calls from single location and it is important that cluster numbers should add up all those calls. Adding for each call single marker can be very slow (I have something like 400 - 5000 locations, and each can have up to 100k calls - which just hangs browser if I create one marker per call) even with "spiderfication" disabled.

Thanks

**Comment by IvanSanchez** [comment]
Use a markercluster with an `iconCreateFunction` that not only counts how many markers are there, but accesses one of their attributes or options and sums it.

Just like http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-custom.html does.
