### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by kennynaoh** [Leaflet/Leaflet.markercluster#669]
Hello @danzel ,
I am the member of the [cdnjs](https://github.com/cdnjs/cdnjs).
We want to host this library.
But there is a version problem on [npm](https://www.npmjs.com/package/leaflet.markercluster).
The latest version on github is v1.0.0-rc.1.
But the latest version on npm is 0.0.5
Please publish the latest version on npm.
Thanks.

https://github.com/cdnjs/cdnjs/issues/6746

**Comment by danzel** [comment]
There is a v1.0.0-rc.1.0 (or something like that) on npm as a prerelease.
It isn't a stable package yet, so it's not published as one.
(Actually it looks like the npm stuff might be messed up, I don't know :s )
Will be published as stable when leaflet 1.0 is, will keep this issue for then.

**Comment by pvhee** [comment]
Hi @danzel - the last version on npm is 0.2.0 (see https://www.npmjs.com/package/leaflet-markercluster)

Any chance you could push the other versions there, such as 0.5.0?  Then also CDN via https://unpkg.com/leaflet-markercluster@0.5.0 would work.

Thanks!

**Comment by itsOgden** [comment]
@pvhee the correct npm package is here: https://www.npmjs.com/package/leaflet.markercluster. 

On that note, is there any idea when we might see an update for leaflet 1.0.0, @danzel?

**Comment by ghybs** [comment]
Hi,

Version 1.0.0-rc.1 is already available: https://unpkg.com/leaflet.markercluster@1.0.0-rc.1.0/dist/

**Comment by itsOgden** [comment]
@ghybs 1.0.0-rc.1 isn't stable enough. A stable release for 1.0.0 would be awesome.

**Comment by danzel** [comment]
that is rc1 of markercluster, you can use it with the 1.0 release of leaflet.
Going to check things work and package a 1.0 now.

**Comment by danzel** [comment]
Ok should be all published and stuff
