### ISSUE TITLE
Weird spiderified markers positioning

### ISSUE THREAD

**Issue by slmgc** [Leaflet/Leaflet.markercluster#670]
Hi! I've stumbled upon some rendering issue: edges and marker positions differ greatly for spiderified markers.

```
const markerCluster = L.markerClusterGroup({
	showCoverageOnHover: false
});
```

![screen shot 2016-05-06 at 10 42 52](https://cloud.githubusercontent.com/assets/5236786/15076409/84951a9a-1377-11e6-9eb3-8324d703faa4.png)

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by slmgc** [comment]
@IvanSanchez sure, I'll try to make one.

**Comment by slmgc** [comment]
@IvanSanchez, sorry, looks like we had some conflicting css properties for our map markers. I think this issue could be closed.
