### ISSUE TITLE
Examples not loading?

### ISSUE THREAD

**Issue by ikb42** [Leaflet/Leaflet.markercluster#671]
http://leaflet.github.com/Leaflet.markercluster/example/marker-clustering-realworld.388.html
http://leaflet.github.com/Leaflet.markercluster/example/marker-clustering-custom.html

**Comment by ghybs** [comment]
Hi,

Looks like `http://XYZ.github.com` redirects to `https://XYZ.github.io`… (notice the change in protocol)
For the record, you can properly load the example by removing the `s` from `https` after being redirected.

Hope this helps.

**Comment by danzel** [comment]
Links updated as above ^^
