### ISSUE TITLE
Clusters are marker order dependant

### ISSUE THREAD

**Issue by mishal153** [Leaflet/Leaflet.markercluster#673]
The cluster formations are dependent on the order of the markers in the markers array. The problem occurs if there is an attempt to clone the leaflet map from the output of getLayers(), Its not the same if cloned. 
If a sorting is maintained before feeding the array to MarkerClusterGroup, then the results are consistent.

Leaflet v0.77

**Comment by danzel** [comment]
This is by design of the greedy clustering algorithm.
If this is important to you there are alternatives that may work:
http://leafletjs.com/plugins.html#clusteringdecluttering
