### ISSUE TITLE
showCoverageOnHover triggered wrong

### ISSUE THREAD

**Issue by FindTheApple** [Leaflet/Leaflet.markercluster#677]
I have the following problem: I am using markerCluster for Leaflet with the showCoverageOnHover option set to true. However, in Firefox (v 46.0.1), the event showCoverageOnHover is not triggered correctly, meaning that the cluster area is shown not only when the mouse is hovered over the cluster, but also if the mouse is far away from that cluster. Basically, I am using the standard procedure to create a markerClusterGroup, but with a customized icon creation function (Using d3 to draw a Pie chart). For details on my code please see http://stackoverflow.com/questions/37280535/leaflet-markercluster-showcoverageonhover-triggered-wrong.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by FindTheApple** [comment]
Sure, here is my Fiddle: https://jsfiddle.net/FindTheApple/sqeypmrn/

**Comment by FindTheApple** [comment]
Solution is published in  http://stackoverflow.com/questions/37280535/leaflet-markercluster-showcoverageonhover-triggered-wrong.
