### ISSUE TITLE
coloring MarkerClusters based on some other aggregate features of the underlying markers

### ISSUE THREAD

**Issue by sevamoo** [Leaflet/Leaflet.markercluster#678]
Hi
I am wondering if it would be possible to color the MarkerClusters based on some aggregate features of the markers belonging to each cluster? I mean instead of count use some mean values of the markers. Let say we have a price attribute for each market and now we are interested to color clusters based on the average or median price.
Thanks a lot.

**Comment by IvanSanchez** [comment]
Yes. Read the documentation and roll out your own `iconCreateFunction`.
