### ISSUE TITLE
Suggestion - % Rate inistead of Number

### ISSUE THREAD

**Issue by rafaeluriarte** [Leaflet/Leaflet.markercluster#679]
In many cases I need markercluster, it would be very interesting to show the rate of the total number of markers in the map (in form of %) instead of the number of the number of children of the cluster. So if you have 20 makers in that cluster and the total in the map is 100, I would like it to show 20% in that region of the map instead of 20. Do you think it is possible?  If such a feature is not a priority, could you please briefly suggest what could I change to make it (getChildCount fuction???) ?

thank you

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
