### ISSUE TITLE
Examples request over HTTP

### ISSUE THREAD

**Issue by micolous** [Leaflet/Leaflet.markercluster#680]
Related to #671, the examples are still broken for me on Chrome 51.  It looks like the examples request Leaflet over HTTP, so the page doesn't load at all:

```
Mixed Content: The page at 'https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.50000.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.leafletjs.com/leaflet-0.7/leaflet.css'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.50000.html' was loaded over HTTPS, but requested an insecure script 'http://cdn.leafletjs.com/leaflet-0.7/leaflet.js'. This request has been blocked; the content must be served over HTTPS.
```

The CDN is also available via HTTPS, so should be as simple as changing the examples to point to HTTPS URLs instead of HTTP. :)

**Comment by ghybs** [comment]
Hi,

The README links explicitly use the `http://` protocol, so you should have been directed through HTTP… unless you have browser specific settings / extensions that try to stay on HTTPS?

Could your situation be similar to that one?
https://github.com/ghybs/Leaflet.FeatureGroup.SubGroup/issues/2

AFAIK, the **official** Leaflet CDN is still on HTTP only?
It is true that it would save a lot of headaches once an HTTPS version is available though.

Hope this helps.

**Comment by danzel** [comment]
Where did you find https links to those pages?
Open them in http, all the examples in the readme are http AFAICT.
If you are using https everywhere plugin that might cause this problem?

**Comment by micolous** [comment]
Ah, I see that it is because of the HTTPS Everywhere plugin, which applies a redirect to `*.github.io`.  However, both the CDN and github.io support HTTPS, so you should really consider using it anyway.

**Comment by danzel** [comment]
Changes for https were in master, just not in the gh-pages branch. Have pushed this up now so it should be corrected.

**Comment by micolous** [comment]
Thanks, looks good now. :smile:
