### ISSUE TITLE
Unable to open popup after zooming into a cluster

### ISSUE THREAD

**Issue by dhrubo001** [Leaflet/Leaflet.markercluster#682]
The function working fine for the markers which are outside of any cluster.

function markerFunction(id){
	
	
        for (var i in m){
			
            var markerID = m[i].options.title;
			if (markerID == id){
				
				  markers.zoomToShowLayer(m[i], function(){
					   m[i].openpopup();
				    });
					
			}
       }
		
    
}

But causing problem when zooming into a cluster and opening the popup.

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster/blob/master/CONTRIBUTING.md#reporting-bugs

Make a JSFiddle
