### ISSUE TITLE
leaflet.markercluster-src.js missing

### ISSUE THREAD

**Issue by iwasherefirst2** [Leaflet/Leaflet.markercluster#683]
Hey, I just noticed that the leaflet.markercluster-src.js file is missing in the master branch in the desc folder.

**Comment by ghybs** [comment]
Hi,

The built files are available in [tag releases](https://github.com/Leaflet/Leaflet.markercluster/releases).
E.g. for current Leaflet version, use [v1.0.0-rc.1 tag](https://github.com/Leaflet/Leaflet.markercluster/tree/v1.0.0-rc.1)

Hope this helps.

**Comment by danzel** [comment]
Yep ^^
We no longer ship the built files in master as we didn't rebuild them so they would be wrong.
You can build them manually or used a tagged version.
