### ISSUE TITLE
Can we get a "title" attribute on a cluster to show on hover?

### ISSUE THREAD

**Issue by japhy-** [Leaflet/Leaflet.markercluster#684]
The cluster marker shows the number of markers it represents, and we can get a polygon to display the coverage area on hover, but could we also get a "title" attribute on the cluster that appears on hover, like on normal markers?

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers
Default implementation:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L760
