### ISSUE TITLE
Export variable with NPM

### ISSUE THREAD

**Issue by Becherman** [Leaflet/Leaflet.markercluster#686]
Hi! Do you can explain me, what is a best way to import L.MarkerGroupClaster from source code to my project. I have any idea!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by Becherman** [comment]
Thank you for quick answer! I know,  how impor L variable, but what about markercluster? Sorry for nooby question!

**Comment by IvanSanchez** [comment]
If I haven't made myself clear: don't make questions in a bug tracker.
