### ISSUE TITLE
can disableClusteringAtZoom be set dynamically ?

### ISSUE THREAD

**Issue by dceejay** [Leaflet/Leaflet.markercluster#688]
Is there a way to set/reset the disableClusteringAtZoom value after the clusterGroup has been initialised ? - without destroying any existing markers etc. (Ideally on the 0.7 branch)

**Comment by ghybs** [comment]
Hi,

You might be interested in this plugin: [Leaflet.MarkerCluster.Freezable](https://github.com/ghybs/Leaflet.MarkerCluster.Freezable).
See [demo](http://ghybs.github.io/Leaflet.MarkerCluster.Freezable/examples/mcg-freezable.html) with Leaflet 0.7.

It provides you with extra methods beyond what MCG already offers, including `disableClustering()` and `enableClustering()`.

Hope this helps.

**Comment by dceejay** [comment]
Thanks, yes have seen that... that seems to just do enable disable... I would like to leave enabled - but change the value at which it clusters (so I can offer the user control).

**Comment by ghybs** [comment]
Hi,

Attaching to zoom event, this should be easy to do with that plugin.

Example: http://plnkr.co/edit/4OXYrN4lup3yMTJaA9i7?p=preview
