### ISSUE TITLE
Spiderfier doesnt' take care of iconAnchor propertie

### ISSUE THREAD

**Issue by brunob** [Leaflet/Leaflet.markercluster#689]
Hi, i think spiderfier script is missing something with iconAnchor option. I've got a simple map that use personal icons on markers. These icons are circles images with an iconAnchor defined to show them at the right coords, but when a cluster spiderfy them, they are shown as the same position of a default leaflet icon like shown in the image below : 

![74fb8736-348d-11e6-9943-6128a06cabb5](https://cloud.githubusercontent.com/assets/418064/16149222/96c42c90-348f-11e6-9163-e9beea4a0eed.png)

I'm using leaflet-0.7 branch for now, but i'm quit sure the bug is also present in master branch since there is no occurrence of `iconAnchor` in `MarkerCluster.Spiderfier.js` script.

**Comment by ghybs** [comment]
Hi,

I think there is no mention of `iconAnchor` because it is internal to Leaflet core, and MCG relies on `L.Icon` to properly position the icon. But I may be wrong.

Please can you provide your code and reproduce your issue on an online editing tool (JSFiddle, Plunker, etc.)?
That would greatly help in providing you with some support, or pinpointing a potential bug in the library.

**Comment by brunob** [comment]
@ghybs as requested here is  a simple fiddle showing the bug : http://playground-leaflet.rhcloud.com/naj/edit?html,output

**Comment by ghybs** [comment]
Bonjour,

Thank you for the playground!

Please can you kindly describe how you would have expected the icons to appear when spiderfied?

It looks like your icons are set just above the geographical position, exactly like Leaflet default markers:
![leafletmcg_issue689](https://cloud.githubusercontent.com/assets/12232803/16184866/c49245ce-36d0-11e6-912f-aae8fde6d308.jpg)
(generated in the playground by duplicating the markers with default icon, and adding them to map but unclustered: http://playground-leaflet.rhcloud.com/rale/edit?html,output)

Therefore, it seems logical that they are positioned just like default markers when spiderfied...

**Comment by brunob** [comment]
Nice catch @ghybs in fact the problem seems to be cluster related and not only spiderfy...

As i said in my first comment : 

> These icons are circles images with an iconAnchor defined to show them at the right coords

If you log `marker.options.icon.options` (i've updated your playground to show this) you will see that default markers and personal markers doesn't have the same `iconAnchor` values but are displayed at the same coords, wich seems to be a bug since `iconAnchor` allow to align the tip of the icon so that this point is at the marker's geographical location http://leafletjs.com/reference.html#icon-iconanchor

**Comment by brunob** [comment]
Ha my bad @ghybs i think the problem is form my side, iconAnchor values are not the right ones in my json (the site seems to use an outdated version of our lib). Sorry for the noise, and thanks for your time, i'm closing this one :\
