### ISSUE TITLE
Open popup on an on-screen, clustered marker

### ISSUE THREAD

**Issue by itsOgden** [Leaflet/Leaflet.markercluster#693]
I have a list of locations and I'm trying to open the popup of any marker when I click on its list item. This is working for non-clustered markers and any marker not currently on screen, but for markers that are currently clustered and on screen, it just zooms to the location and doesn't open the popup. Any ideas what's happening here or how to get around it?

The code: 
 
        map.setView(marker.getLatLng(), 16);
        marker.openPopup();

**Comment by ghybs** [comment]
Hi,

You probably do not give time for the marker to be unclustered, hence for its popup to be "open-able".

Have you tried the [`zoomToShowLayer()`](https://github.com/Leaflet/Leaflet.markercluster#other-group-methods) method?

For more help, you can have a look at the bottom part (just after the "EDIT" line) of this post:
https://stackoverflow.com/questions/35772717/searching-markers-with-leaflet-control-search-from-drop-down-list/35793616#35793616

Hope this helps.

**Comment by itsOgden** [comment]
Huzzah! Thanks, @ghybs, that works perfectly!
