### ISSUE TITLE
[Question] Find biggest cluster?

### ISSUE THREAD

**Issue by v3ss0n** [Leaflet/Leaflet.markercluster#696]
Is there ways to find the biggest cluster , so i can zoom to there by default?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet.markercluster useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
