### ISSUE TITLE
Changing the color bounds

### ISSUE THREAD

**Issue by jared-clarifai** [Leaflet/Leaflet.markercluster#698]
I see the CSS file where the default bound colors are set, but how do we change the 10, 100 and 1,000 boundaries to other limits? Is that possible

**Comment by jared-clarifai** [comment]
Found a good solution after a ton of searching, in case anyone else is interested:

http://www.xenabeast.com/solution-modify-style-leaflet-markercluster-cluster-marker/

**Comment by ghybs** [comment]
Hi,

I think you would have been interested in that section:
https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers

Hope this helps.
