### ISSUE TITLE
Support for leaflet groups?

### ISSUE THREAD

**Issue by tsbzb** [Leaflet/Leaflet.markercluster#699]
Hi!

The clustering feature is very nice, but I have run into the following problem: I have a leaflet group of objects (e.g. the marker and a circle around the marker). Using this group for clustering, both objects are counted. Thus this group is ignored, clustering the circle with the marker and displaying the wrong number. Is there a possibility to configure this library to cope with leaflet groups?

Thank You!

**Comment by danzel** [comment]
You could sort of work around this maybe:
https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers
Make it not add 1 for the circle.

Probably what you should do instead is just cluster the markers, then add the circles dynamically when the markers appear on the map?
