### ISSUE TITLE
First zoomToBounds and then spiderfy on clusterclick

### ISSUE THREAD

**Issue by Dexus** [Leaflet/Leaflet.markercluster#705]
Is it possible to zoomToBounds and then open the spiderfy on clusterclick?
And if it not yet possible can it be integrated?

Used Version: Leaflet 0.7.x last stable; markercluster last stable

**Comment by ghybs** [comment]
Hi,

I think it might help if you could provide more details on what you try to do.

Note that when you do `zoomToBounds` on the clicked cluster, there is a very high chance it splits into smaller clusters and/or individual markers. Which of those child clusters should spiderfy, if any? (I am not sure you can have several of them opened simultaneously with current code).

Currently, `zoomToBounds` does not take any callback, but you could imagine adding a one shot listener like `map.once("moveend", fn)` and/or `map.once("zoomend", fn)` to perform your next operation (like spiderfying).

Hope this helps.
