### ISSUE TITLE
Customize markers count display

### ISSUE THREAD

**Issue by badreal** [Leaflet/Leaflet.markercluster#710]
Is there a simple to customize markers count display ?

Let's say i have 500 markers and that at some zoom level a cluster contains 50 markers, i would like to display 10% = 50/500 instead of 50.

I have seen that piece of code

    iconCreateFunction: function(cluster) {
        return L.divIcon({ html: '<b>' + cluster.getChildCount() + '</b>' });
    }

But i was wondering if there is a way to change the test only and keep the css ( circle clusters with different colors)

**Comment by danzel** [comment]
copy/paste the default code.
