### ISSUE TITLE
hasLayer doesn't work as expected 

### ISSUE THREAD

**Issue by svennd** [Leaflet/Leaflet.markercluster#711]
I'm pretty sure I'm doing something wrong, but can't figure out what ...  Initially I load only the markers that are within the bounds of the map and when the map is dragged around I redraw all the markers. This works, however there is a slight time when the map is empty, so I tried to just add the markers that are "new" to the map. Using the hasLayer() function, sadly it always returns false, irrelevant whats drawn.

Here's what I thought should work : 

```
var cluster = L.markerClusterGroup();

function load_map() {
	// map setup 
	var map = L.map();
	// add the initial markers
	add_markers(map);
	// when the move is ended add the markers again
	map.on('moveend', function () {
		add_markers(map) 
	});
}

	
function add_markers(map) {
	var bounds = map.getBounds();
	
	jQuery.ajax({
		url : 'ajax/get',
		method : 'POST',
		data : { nlat : bounds.getNorth(), nlng : bounds.getEast(), slat : bounds.getSouth(), slng : bounds.getWest()},
		dataType : 'json',
		success : function(location) {
			for (var spot in location) {
				
				// create the marker
				var marker = L.marker(location[]);
				
				// this always prints "false"
				console.log(cluster.hasLayer(marker));

				// add the marker to the cluster layer
				// *here i want to check hasLayer()*
				cluster.addLayer(marker); 
			}
		}
	});

	// draw it on the map
	cluster.addTo(map);
}

// load the map
load_map();
```
Is calling clearLayers() the only option ? Note that in my use case, its not a huge dataset. <1k markers

**Comment by danzel** [comment]
You are creating new markers in the ajax response.

**Comment by svennd** [comment]
So hasLayers only works when all markers are known upfront ?

**Comment by danzel** [comment]
It only works when you pass in the same layer.
This is standard leaflet behaviour.

**Comment by piodabro** [comment]
But hasLayer doesnt work as expected in clusterGroup.
I have a problem with that.
I've stored reference to geoJSON layer and then call hasLayer with that referenced object gives me false.
Standard FeatureGroup.hasLayer() works as expected, the same called on markerClusterGroup (changed FG to markerClusterGroup) gives false.
