### ISSUE TITLE
Documentation missing non-npm install instructions

### ISSUE THREAD

**Issue by catbadger** [Leaflet/Leaflet.markercluster#713]
Not everyone is using npm. Can the documentation please include directions for install without npm? Specifically what files need to be included to get the functionality?

**Comment by danzel** [comment]
The instructions don't even fully document how you use it with npm. They advise to check out the included examples for usage.

Happy to have this improved, otherwise you can view the example and figure it out.

**Comment by catbadger** [comment]
I have no problem getting this to work, it was just a suggestion.

**Comment by danzel** [comment]
Sorry if there was some misunderstanding there. I meant this would be a good contribution if someone wanted to add it :)
