### ISSUE TITLE
Problem with dulicate markers the same latitude and longtitude

### ISSUE THREAD

**Issue by thuanitdn** [Leaflet/Leaflet.markercluster#714]
Currently i have got problem ralated with dulicated markers , when render cluster ,... i display with strange.
![image](https://cloud.githubusercontent.com/assets/10988591/18352815/131ef7aa-760a-11e6-8f91-82527f633f3e.png)

Please help me resolve problem, Sorry for my english.

**Comment by ghybs** [comment]
Hi,

Your screenshot exhibits the behaviour of `spiderfyOnMaxZoom ` option (see [options](https://github.com/Leaflet/Leaflet.markercluster#all-options)).
What is your question?
