### ISSUE TITLE
need bind this 

### ISSUE THREAD

**Issue by kocokolo** [Leaflet/Leaflet.markercluster#715]
this.eachLayer(function (marker) {
                marker.off('move', this._childMarkerMoved, this);
                delete marker.__parent;
            }**.bind(this)**);

**Comment by kocokolo** [comment]
in

>  Leaflet.markercluster/src/MarkerClusterGroup.js

**Comment by IvanSanchez** [comment]
First: **Why** is this code change needed?

It's bad practice to say "you need to change this code" without explaining why. Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html#symptoms

Second: Can you make this code change in a [pull request](https://help.github.com/articles/creating-a-pull-request/) instead?
