### ISSUE TITLE
Add a way to set custom marker weight?

### ISSUE THREAD

**Issue by d33tah** [Leaflet/Leaflet.markercluster#719]
I'm working on a project where I need to display a clustered map that contains a huge number of markers - in some cases way more than the 50k allowed right now. A lot of the points overlap on each other though and I don't really care about labels for them - it would be okay to group them together. Could you add a way for me to add, say, a marker that is worth 1000 points and is counted this way, but is displayed as a single one for performance reasons?

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers
