### ISSUE TITLE
Trigger openPopup() on clustered markers

### ISSUE THREAD

**Issue by dannychua** [Leaflet/Leaflet.markercluster#72]
Hi, I have every marker added to the markerclusterer `markers` also added to an object `markersList = {}` Each marker added also creates a row in a sidebar, such that when a user clicks on a row, the marker corresponding to that row will `openPopup()`.

**Problem:** Without adding the markers to markercluster, the markers will `openPopup()` when its row in the Sidebar is clicked. However if these markers were to be added to markerclusterer, `openPopup()` does nothing. _`this.model.id` is an id unique to each marker, retrieved from a backbone.js model `this.model`._

Is there currently a way to achieve this with the markers added to markerclusterer? Thank you so much!! :)

**A loop creates all the markers required**

```
// Create marker
var marker = new L.marker(
    new L.LatLng( this.model.get('lat'), this.model.get('lng') ));
var content = this.templatePopup( this.model.toJSON() );
marker.bindPopup(content);

// Popup does not open if added to marker clusterer
//markers.addLayer(marker);

// Popup works when added to map
marker.addTo(map);

// Add to list of markers
markersList[this.model.id] = marker;
```

**When a row in the sidebar is clicked...**

```
// Opens the marker's popup when row in Sidebar is clicked
$('row').click(function() {
    markersList[this.model.id].openPopup();
})
```

**Comment by telardil** [comment]
```
openMarkerPopup: function() {
    var marker = markersList[this.model.id];
    if (!marker._icon) marker.__parent.spiderfy();
    marker.openPopup();
}
```

**Comment by birdage** [comment]
@telardil NICE! :+1:

**Comment by krishnaisdinesh** [comment]
Hi,

On markers click popup is opening properly using bindPopup() function. But i want to open popup on cluster click. I am able to capture cluster click event but bindPopup() is not working for cluster.

```
this.markers.on('clusterclick', function (a) {
	    //Cluster click event is captured but how to show popup.
	},this);

```
Please help  me out..

**Comment by jaychacko** [comment]
@krishnaisdinesh something like marker.openPopup(). i had a similar issue i just resolved. This answer might help future users 

`angular.forEach(rawAssetsObjects, function (_asset) {
               
              let marker =  L.marker(L.latLng(_asset.latitude,
                      _asset.longitude), {
                          id: _asset.id,
                          icon: L.divIcon({
                              html: self.siMarkers.createHTMLMarker(_asset),
                              popupAnchor: [0,-80]
                          })
                          
                      });`
