### ISSUE TITLE
How can I hide markers on page load?

### ISSUE THREAD

**Issue by Joci933** [Leaflet/Leaflet.markercluster#720]
Hello!

How can I hide markers on page load?

Here is the current map: [http://image.prntscr.com/image/74e5314cc7214d8486f02cf5bef75c2c.png](http://image.prntscr.com/image/74e5314cc7214d8486f02cf5bef75c2c.png)

Here is what I want: [http://image.prntscr.com/image/3762c1e57eb7490a95120172c988d37b.png](http://image.prntscr.com/image/3762c1e57eb7490a95120172c988d37b.png)

Here is my markercluster options:
`options: {
            maxClusterRadius: 80,
            iconCreateFunction: null ,
            spiderfyOnMaxZoom: !0,
            showCoverageOnHover: !0,
            zoomToBoundsOnClick: !0,
            singleMarkerMode: 0,
            disableClusteringAtZoom: 0 ,
            removeOutsideVisibleBounds: !0,
            animate: !0,
            animateAddingMarkers: !1,
            spiderfyDistanceMultiplier: 1,
            spiderLegPolylineOptions: {
                weight: 1.5,
                color: "#222",
                opacity: .5
            },
            chunkedLoading: !1,
            chunkInterval: 200,
            chunkDelay: 50,
            chunkProgress: null ,
            polygonOptions: {}
        },`

And the leaflet map options:
`var map = L.map('map-leaflet', {
			zoom: 7,
			maxZoom: 20,
			center: [46.6268063953552, 19.53369140625]
		});`

**Comment by danzel** [comment]
You are probably doing something stupid like adding the markers to the map. Don't do that.
