### ISSUE TITLE
Any solution to show markers with  group of clusters only arround 3 kilometer area

### ISSUE THREAD

**Issue by rahulmahadik** [Leaflet/Leaflet.markercluster#721]
![map](https://cloud.githubusercontent.com/assets/13520131/18826988/f93aca02-83ed-11e6-8e7d-08667753bf26.png)
 also i want to show count of markers , when i click on cluster.

Thanks

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by rahulmahadik** [comment]
ok thanks, @IvanSanchez
