### ISSUE TITLE
How to change the individual markers

### ISSUE THREAD

**Issue by adithya003** [Leaflet/Leaflet.markercluster#723]
Can you give a demo of how to change the individual marker image

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
