### ISSUE TITLE
typescript type definition for Leaflet.markercluster

### ISSUE THREAD

**Issue by darcyparker** [Leaflet/Leaflet.markercluster#725]
An up to date (free of syntax errors) typescript definition for Leaflet markercluster is needed.

And it would be great if the definition can be included in this repo and specified in the `package.json`.  (See http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

Currently [registry:dt/leaflet-markercluster#0.4.0+20160919070725](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc3d223a946f661eff871787edeb0fcb8f0db156/leaflet-markercluster/leaflet-markercluster.d.ts#L87) is broken.  I did some initial investigation and I believe but could be wrong that:
- It should be exporting an interface that extends `FeatureGroup`. A class usually isn't in a type definition because it is an implementation.  Currently there is an error from typescript compiler saying a class doesn't extend, but implements - which is true. But the problem is that it shouldn't be a class, but rather an interface definition.
- `FeatureGroup` is not a generic

I can look at this more, but I don't know the API very well so it may take me more time.  If someone else has solved this or can get to it before me, I'd appreciate it.

**Comment by darcyparker** [comment]
FYI: https://github.com/Leaflet/Leaflet/issues/5003 is a similar issue for leaflet.

**Comment by danzel** [comment]
Will gladly accept the package.json changes and release a bumped version with them included once the definition on definitelytyped is updated.

**Comment by danzel** [comment]
The typescript definitions were updated:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/leaflet-markercluster

**Comment by danzel** [comment]
If they aren't right, make an issue on DefinitelyTyped (or just fix them on there :+1:)

**Comment by grimace** [comment]
this page does not exist:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/leaflet-markercluster

Where could I find the typescript definition for leaflet markercluster?

**Comment by danzel** [comment]
`npm install @types/leaflet-markercluster` maybe?
https://www.npmjs.com/package/@types/leaflet-markercluster

**Comment by ghybs** [comment]
Hi @grimace,

DT changed their repo structure by adding a `types` folder in the path.
Therefore the new correct path is:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leaflet-markercluster

**Comment by denyo** [comment]
Hello,
I have a similar issue or at least related issue here. I am using
```
"leaflet": "^1.0.3",
"leaflet.markercluster": "^1.0.4"
```
and 
```
"@types/leaflet": "^1.0.60",
"@types/leaflet-markercluster": "^1.0.3"
```
Code completion and everything works perfectly fine. However during compilation of `ng serve` it fails with
```
Property 'markerClusterGroup' does not exist on type 'typeof L'.
```

Any ideas how to solve this?

**Comment by severinbeauvais** [comment]
I'm using
```
"leaflet": "^1.3.1",
"leaflet.markercluster": "^1.3.0"
```
and
```
"@types/leaflet": "^1.2.6",
"@types/leaflet-markercluster": "^1.0.3"
```
The following worked for me:
```
import 'leaflet';
import 'leaflet.markercluster';

const L = window['L'];
```
