### ISSUE TITLE
Draggable marker leaflet v1.0.0 and MarkerCluster 1.0.0.

### ISSUE THREAD

**Issue by julienVoltzenlogel** [Leaflet/Leaflet.markercluster#726]
I am in leaflet v1.0.0 and MarkerCluster 1.0.0.

I have a problem with MarkerCluster :
When I start dragging à marker, the cursor is blocked with the hand icon and I can't drop my marker.

If I add a marker without using the MarkerCluster plugin, the drag and drop work perfectly.

This is my code, can you identify my problem ? :

```
drawnMarkers = new L.MarkerClusterGroup({
        maxClusterRadius: 100,
        chunkedLoading: true,
        showCoverageOnHover: false,
        removeOutsideVisibleBounds: true,
        zoomToBoundsOnClick: true,
        singleMarkerMode: false
    });

    var compteur = 1;

    markers.forEach(function (jsonData) {
        var marker = L.marker([jsonData.Latitude, jsonData.Longitude], { draggable: true });

        drawnMarkers.addLayer(marker);

        // On recentre l'affichage sur les markers quand ils ont tous été ajouté sur la carte
        if (compteur == markers.length) {
            var group = new L.featureGroup(drawnMarkers.getLayers());
            map.fitBounds(group.getBounds());
        }       

        compteur++;
    });

    map.addLayer(drawnMarkers);
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
