### ISSUE TITLE
spiderfied and unspiderfied event

### ISSUE THREAD

**Issue by lfiebach** [Leaflet/Leaflet.markercluster#729]
how to use theese two events ?

I try 

        markers.on('spiderfied', function (a) {
            // a.layer is actually a cluster
            console.log(a);
        });

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by brahmachen** [comment]
玩儿玩儿
