### ISSUE TITLE
Doesn't work work leaflet 1.0.0 or 1.0.1

### ISSUE THREAD

**Issue by vmikeska** [Leaflet/Leaflet.markercluster#730]
Just versions 0.4.0 and 0.5.0 works. I have tried with both leaflet 1.0.0 and 1.0.1

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by ghybs** [comment]
Hi,

Leaflet 1.0.1 + Leaflet.markercluster 1.0.0 seems to work: https://jsfiddle.net/3v7hd2vx/103/

**Comment by IvanSanchez** [comment]
Will reopen if a proper test case is provided.
