### ISSUE TITLE
Can't get CircleMarker popups to work properly?

### ISSUE THREAD

**Issue by booherbg** [Leaflet/Leaflet.markercluster#731]
Hello. I'm doing an experimental upgrade from 0.7.7 to 1.0.1. This is one of three issues that I'm having.

I'm making circlemarkers with popups. I'm using a very traditional bindPopup() inside a onEachFeature() loop, on circleMarkers that get created with pointToLayer from a geoJson collection.

The markers show up fine. However, I can't get the popups to work. It *seems* like there is something akin to a z-index problem. When I right click and inspect element, I get the actual image tile -- not the SVG marker. So it seems like the click event isn't even "reaching" the circlemarker handler. 

The code basically looks like this:

``` javascript
const mappables = L.geoJson(geoJsonCollection, {
   pointToLayer: (feature, latlng) => L.circleMarker(latlng, options),
   onEachFeature: (feature, layer) => {
      layer.bindPopup('<p>Popup</p>');
   }
}
mappables.addTo(map); // add to leaflet map
```

**Comment by danzel** [comment]
Um, did you mean to post this in leaflet.markercluster?

**Comment by booherbg** [comment]
Nope. Sorry about that :P 

I figured it out anyway. Future googlers: make sure your css file was updated to the latest version (mine wasn't).
