### ISSUE TITLE
file missing leaflet.markercluster-src.js

### ISSUE THREAD

**Issue by kazes** [Leaflet/Leaflet.markercluster#732]
Hi,
I'm using an older version that is only one js file `leaflet.markercluster-src.js`, I'm trying to update it but I can't find it in your github.
In your examples the path leads to dist/ folder  `<script src="../dist/leaflet.markercluster-src.js"></script>` but there is no such file in it :(
https://github.com/Leaflet/Leaflet.markercluster/tree/master/dist

Is it an error in the html or is the file really missing ? Should it be build somehow in my localhost ?
Thanks !

**Comment by IvanSanchez** [comment]
See https://github.com/Leaflet/Leaflet.markercluster/blob/master/Jakefile.js . Feel free to submit a PR to explain this in the main readme.

**Comment by kazes** [comment]
Yes, thanks I didn't know about jakefiles :+1:
