### ISSUE TITLE
How can I have the clusters zoomed and centred?

### ISSUE THREAD

**Issue by McCABRUS** [Leaflet/Leaflet.markercluster#736]
Once the map is loaded it shows at the min zoom, just like this:

![screen](https://cloud.githubusercontent.com/assets/13442935/19873656/3fe98fe0-9f8e-11e6-815e-7fbe6470ab3e.png)

I want to have this view once the map is loaded:

![screen 2](https://cloud.githubusercontent.com/assets/13442935/19873693/7c17b352-9f8e-11e6-838a-21b14b40e438.png)

how can I do this?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by McCABRUS** [comment]
Sorry, I thought the clustering functionality is provided by this plugin
