### ISSUE TITLE
Script becomes unresponsive

### ISSUE THREAD

**Issue by mukuls-brdsys** [Leaflet/Leaflet.markercluster#737]
Hey, I am trying to use it with leaflet polymer component. When I try to call addLayer browser responds that the marker cluster script is not responding.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
