### ISSUE TITLE
Issue with .zoomToShowLayer()

### ISSUE THREAD

**Issue by PlaidPhantom** [Leaflet/Leaflet.markercluster#739]
I'm having an odd issue with the `zoomToShowLayer` function.  In the callback, I am opening a popup on the selected marker.  However, in certain situations it seems that instead of zooming in on the marker markercluster tries to spider the associated cluster before it zooms in, resulting in all the markers in that cluster disappearing until the map redraws.  After some trial-and-error, I think i've found an example that, for me at least, consistently reproduces the issue: http://codepen.io/plaidphantom/pen/zodYRE

**Comment by mukuls-brdsys** [comment]
I'm having this issue too. Any update on this?

**Comment by newmanw** [comment]
Hey all, I am still having problems with this.  Good news is I think I might have an idea on why, although I am not sure of the fix yet.

This is not working is the marker has a divIcon (http://leafletjs.com/reference-1.0.3.html#divicon).

Seems that a marker with a divIcon does not have an _icon, nor does its parent.  Meaning this if check to show the marker fails:

https://github.com/Leaflet/Leaflet.markercluster/blob/31e413d287f83750a97714c248562d331f5a6f7a/src/MarkerClusterGroup.js#L544

Would it be possible to reopen this issue?
