### ISSUE TITLE
Markers doesnt completely grouped

### ISSUE THREAD

**Issue by tenznhok** [Leaflet/Leaflet.markercluster#741]
I tried to use the leaflet marker cluster. I have a popup bind to each marker. If I want to have the popup works, then my map will look like this:

![cluster and popup](https://cloud.githubusercontent.com/assets/6728831/20956764/e84837fc-bc19-11e6-9a78-40a63626ba1f.PNG)

The code : 

       var popup = "popup test";
       map.addLayer(marker);

       markers[marker._leaflet_id] = marker;
       marker.bindPopup(popup);
       clusterMarkers.addLayer(marker);
       map.addLayer(clusterMarkers);
     

But if I want the cluster works nice and neat (by delete the map.addLayer(marker) from the previous code), then the popup doesn't work on my map when I try to click onto the marker. 
![popup problem](https://cloud.githubusercontent.com/assets/6728831/20956625/0fe58a36-bc19-11e6-98dd-a80f4773a7d9.PNG)

The code : 

       var popup = "popup test";
       //map.addLayer(marker);

       markers[marker._leaflet_id] = marker;
       marker.bindPopup(popup);
       clusterMarkers.addLayer(marker);
       map.addLayer(clusterMarkers);
     

I am wondering how can I have nice and neat marker cluster but the marker popup is still working fine for each marker?

**Comment by IvanSanchez** [comment]
This is in https://stackoverflow.com/questions/41010682/leaflet-marker-cluster-popup-doesnt-work-on-the-cluster , so closing unless it can be proven it's a bug.
