### ISSUE TITLE
How to add icons to marker cluster & change marker icon something other than blue?

### ISSUE THREAD

**Issue by pallaviMN** [Leaflet/Leaflet.markercluster#742]
Currently via CSS, we are clearing marker cluster, can we change it to use icons?
All marker icons are in blue color, can it be changed?

IF yes, please let us know the place to change in the code?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
