### ISSUE TITLE
Marker Cluster Radius not changing dynamically based on map zoom

### ISSUE THREAD

**Issue by rahulanand71** [Leaflet/Leaflet.markercluster#748]
trying to change the marker cluster radius dynamically based on the zoom level of the map.

Objective: I want the first view of the map (which is set to zoom = 4) to have the marker cluster radius as 80 pixels; once a cluster has been clicked and the map zooms in - the marker cluster radius should be 10 pixels. This is so that once zoomed in, there is no clustering [I have tested it on my dataset and map render and a radius of 10 or less ends up with no clusters]

The sample data file is available here:
https://drive.google.com/file/d/0B2LJXtBTsuhhbklTMEhOMjVOSkk/view

The code for a basic version of the view is as below:

`library(leaflet)
library(dplyr)
library(shiny)

#Read Data
stackdata <- read.csv("stackdata.csv")

ui <- fluidPage(
  fluidRow(
    column(4, uiOutput("aid")),
    column(4, uiOutput("io")),
    column(4,actionButton(inputId = "update", label= "Update",style = "margin-top:25px", icon = icon("refresh")))
  ),
  fluidRow(leafletOutput("locatemap"))
)

server <- function(input,output){

  #Reactive Datasets

  delivery_data <- eventReactive(input$update,{stackdata %>% filter(io == input$io)})

  #Input Controls

  output$aid <- renderUI({
    selectInput(inputId="aid",label="AID",choices = unique(stackdata$aid),selected="1225103")
  })

  output$io <- renderUI({
    selectInput(inputId="io",label="IO",choices = unique(stackdata$io), selected = "375779")
  })

  #Clustering by Clicks
  cluster = 
    "function (cluster) {
  var markers = cluster.getAllChildMarkers();
  var sum = 0;
  var count = 0;
  var avg = 0;
  var mFormat = ' marker-cluster-';
  for (var i = 0; i < markers.length; i++) {
  if(markers[i].options.weight != undefined){
  sum += markers[i].options.weight;
  count += 1;
  }
  }
  sum = Math.round(sum);
  if(sum<10) {mFormat+='small'} else if (sum>80){mFormat+='large'}else{mFormat+='medium'};
  return L.divIcon({html: '<div><span>' + sum + '</span></div>', className: 'marker-cluster'+mFormat, iconSize: L.point(42, 42)});
}"

  # Marker Radius
  marker_radius_final    <- reactive({
    if(is.null(input$locatemap_zoom)){
      return (80)
    } else if (input$locatemap_zoom == 4) {return(80)} else if (input$locatemap_zoom > 4) {return(10)}
  })

  #Rendering Leaflet Map - Heatmap

  output$locatemap <- renderLeaflet({
    leaflet() %>% 
      setView(lng=133.4166,lat=-24.25,zoom=4) %>% 
      addProviderTiles("OpenStreetMap.BlackAndWhite") %>%
      addCircleMarkers(
        lng=delivery_data()$longitude,
        lat=delivery_data()$latitude,
        radius=5,
        stroke=FALSE,
        weight = delivery_data()$click,
        fillOpacity = 0.9,
        clusterOptions=markerClusterOptions(iconCreateFunction = JS(cluster), maxClusterRadius = marker_radius_final(), spiderfyOnMaxZoom = FALSE, disableClusteringAtZoom = 10)
      )
    })

}

shinyApp(ui = ui, server = server)`

	
Newbie in R shiny here!

I am working with leaflet - and trying to change the marker cluster radius dynamically based on the zoom level of the map.

Objective: I want the first view of the map (which is set to zoom = 4) to have the marker cluster radius as 80 pixels; once a cluster has been clicked and the map zooms in - the marker cluster radius should be 10 pixels. This is so that once zoomed in, there is no clustering [I have tested it on my dataset and map render and a radius of 10 or less ends up with no clusters]

The sample data file is available here:

https://drive.google.com/open?id=0B2LJXtBTsuhhbklTMEhOMjVOSkk

The code for a basic version of the view is as below:

library(leaflet)
library(dplyr)
library(shiny)

#Read Data
stackdata <- read.csv("stackdata.csv")

ui <- fluidPage(
  fluidRow(
    column(4, uiOutput("aid")),
    column(4, uiOutput("io")),
    column(4,actionButton(inputId = "update", label= "Update",style = "margin-top:25px", icon = icon("refresh")))
  ),
  fluidRow(leafletOutput("locatemap"))
)

server <- function(input,output){

  #Reactive Datasets

  delivery_data <- eventReactive(input$update,{stackdata %>% filter(io == input$io)})

  #Input Controls

  output$aid <- renderUI({
    selectInput(inputId="aid",label="AID",choices = unique(stackdata$aid),selected="1225103")
  })

  output$io <- renderUI({
    selectInput(inputId="io",label="IO",choices = unique(stackdata$io), selected = "375779")
  })

  #Clustering by Clicks
  cluster = 
    "function (cluster) {
  var markers = cluster.getAllChildMarkers();
  var sum = 0;
  var count = 0;
  var avg = 0;
  var mFormat = ' marker-cluster-';
  for (var i = 0; i < markers.length; i++) {
  if(markers[i].options.weight != undefined){
  sum += markers[i].options.weight;
  count += 1;
  }
  }
  sum = Math.round(sum);
  if(sum<10) {mFormat+='small'} else if (sum>80){mFormat+='large'}else{mFormat+='medium'};
  return L.divIcon({html: '<div><span>' + sum + '</span></div>', className: 'marker-cluster'+mFormat, iconSize: L.point(42, 42)});
}"

  # Marker Radius
  marker_radius_final    <- reactive({
    if(is.null(input$locatemap_zoom)){
      return (80)
    } else if (input$locatemap_zoom == 4) {return(80)} else if (input$locatemap_zoom > 4) {return(10)}
  })

  #Rendering Leaflet Map - Heatmap

  output$locatemap <- renderLeaflet({
    leaflet() %>% 
      setView(lng=133.4166,lat=-24.25,zoom=4) %>% 
      addProviderTiles("OpenStreetMap.BlackAndWhite") %>%
      addCircleMarkers(
        lng=delivery_data()$longitude,
        lat=delivery_data()$latitude,
        radius=5,
        stroke=FALSE,
        weight = delivery_data()$click,
        fillOpacity = 0.9,
        clusterOptions=markerClusterOptions(iconCreateFunction = JS(cluster), maxClusterRadius = marker_radius_final(), spiderfyOnMaxZoom = FALSE, disableClusteringAtZoom = 10)
      )
    })

}

shinyApp(ui = ui, server = server)
I have made the following attempts:

Attempt I: I simply tried the disableClusteringAtZoom and set it to 5, but then the markers would either spiderfyOnMaxZoom or simply become un-clickable - neither of these is what I'm looking for.

Attempt II: If I increase disableClusteringAtZoom to 7 or 8 - I get a lot of views when there exists a combination of markers and marker clusters - which is not what I want. To counter this, I set singleMarkerMode = TRUE but it made no difference at all.

Attempt III: The github page for leaflet marker cluster mentioned that: "You can also use a function that accepts the current map zoom and returns the maximum cluster radius in pixels."

So, I created a reactive marker_radius which would take the current map zoom and return the radius in pixels. However, in this case, once I zoom in - I am automatically zoomed back out to the first view of the map - and I am not sure why.

I know I must be missing something here - but I haven't been able to figure it out. Any help on this would be really great! 

Thank You!

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster#other-options
Set `maxClusterRadius` to a function that takes a zoom level and returns the radius for that zoom level.

**Comment by rahulanand71** [comment]
Hi - tried that as well:

here's the amended markerClusterOptions code:
clusterOptions=markerClusterOptions(iconCreateFunction = JS(cluster), maxClusterRadius = marker_radius(input$locatemap_zoom), spiderfyOnMaxZoom = FALSE, disableClusteringAtZoom = 9)

here's the marker radius function:
  marker_radius <- function(x){
    if(is.null(input$locatemap_zoom)){return(80)}
    if (input$locatemap_zoom == 4){return(80)}
    else if (input$locatemap_zoom > 4){return(10)}
    else (return(40))
  }

What happens is that the first value is returned correctly however, once I zoom in - I am zoomed out to the original view - here's a gif which shows what's happening:
![heatmap - marker radius issue](https://cloud.githubusercontent.com/assets/24472466/21836659/ec42db7a-d7ec-11e6-8606-632dda706723.gif)

**Comment by danzel** [comment]
I have no idea what's going on in that image sorry.
Can you make a minimal reproducing case on https://playground-leaflet.rhcloud.com/?html,output ?

**Comment by rahulanand71** [comment]
Hey sorry - but I have no experience web development - I am using leaflet in R Shiny.  That said, the first comment from me has the R code for a reproducible case. Attaching the code and dataset here:

[Shiny Leaflet Marker Cluster reproducible.txt](https://github.com/Leaflet/Leaflet.markercluster/files/701097/Shiny.Leaflet.Marker.Cluster.reproducible.txt)

[stackdata.txt](https://github.com/Leaflet/Leaflet.markercluster/files/701113/stackdata.txt)


Please let me know if there's anything else!

**Comment by danzel** [comment]
Sorry I can't debug your R code for you.

**Comment by rahulanand71** [comment]
Hey that can be run directly on an R console - dont mean for you to debug the R code - just what's going on underneath. 
As in, I can't figure out why the zoom value of the map is changing when I am only playing around with the radius of the marker? Please re-open.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
