### ISSUE TITLE
uncaught exception: Map has no maxZoom specified

### ISSUE THREAD

**Issue by JulienItard** [Leaflet/Leaflet.markercluster#750]
I'm trying to use your plugin with Google layer [from here](https://github.com/gam6itko/leaflet-plugins)
I specified `maxZoom` but `uncaught exception: Map has no maxZoom specified`. Any idea ?

Thanks

**Comment by IvanSanchez** [comment]
That plugin for using google maps tiles is deprecated. Consider using https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant , and see the conversation at https://github.com/shramov/leaflet-plugins/issues/250

**Comment by carlos-mg89** [comment]
I'm getting this error while using the leaflet-mapbox-gl library along with the Leaflet.markercluster library. If I use it without the marker cluster, everything works alright. However, my intention is to use both.

Does anyone have an idea about why could this happen?

This are my dependencies:

```
<script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('js/latinise.min.js') }}"></script>
<script src="https://cdn.maptiler.com/mapbox-gl-js/v0.53.0/mapbox-gl.js"></script>
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
                integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
                crossorigin=""></script>
<script type="application/javascript" src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
<script src="https://cdn.maptiler.com/mapbox-gl-js/v0.53.0/mapbox-gl.js"></script>
<script src="https://cdn.maptiler.com/mapbox-gl-leaflet/latest/leaflet-mapbox-gl.js"></script>
```

I thought I followed the correct indications to make it work but somehow I'm getting this error that is blocking the markercluster from working. The rest of the JS code is working nicely.

Any help would be much appreciated.
