### ISSUE TITLE
Need help setting up markercluster on Polymer Web Component

### ISSUE THREAD

**Issue by dimassrio** [Leaflet/Leaflet.markercluster#751]
Im trying to setup the marker cluster on Polymer, but somehow the page always end up with Aw Snap (chrome) Warning.

Any idea what i did wrong?

Im starting with 20000 marker, and then decrease it and realize it also give warning at 1000 marker.

```
var markers = L.markerClusterGroup({
	chunkedLoading : true
});
response.response.data.forEach(function(data){
	var x = {};
	x.latitude = data.latitude;
	x.longitude = data.longitude;
	markers.addLayer(L.marker(L.latLng(parseFloat(x.latitude), parseFloat(x.longitude))));
});
this.$.leafletMap.map.addLayer(markers);
```

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by dimassrio** [comment]
Ok thank you :)
