### ISSUE TITLE
Change marker position when markercluster layer is unmount from map overlay layers.

### ISSUE THREAD

**Issue by MMajo** [Leaflet/Leaflet.markercluster#753]
Hi, sometimes I need temporary unmount markercluster layer from overlay layers. When markercluster layer is unmount, asynchronous event change lat, lon for markers. Then, when I again mount markercluster layer to overlay layers, occurs exception: TypeError: Can not read property '_Zoom' of undefined.

I attach JSFiddle example:

https://jsfiddle.net/q9a6eaya/

Reproduce behavior:
1. Uncheck Group
2. Change Position
3. Check Group

How can I proceed, when markercluster layer is unmount and asynchoronous event changig markers position in markercluster layer?

Thaks

**Comment by danzel** [comment]
Ok taking a look, progress so far:

When the marker is moved we add it to our to remove list.
When we are added to the map again, we try remove the marker, but we fail to as it is in a different location (we fail in `_removeFromGridUnclustered`).

This leads to us trying to cluster the marker with itself.

We probably need to record the position the marker was moved from and remove it from that somehow.

**Comment by danzel** [comment]
Have pushed up a fix for this, please test it out in your app and report back.

There is a built version here:
https://gist.github.com/danzel/e3f170316fd8473f7b2188f85aa44357

**Comment by MMajo** [comment]
danzel, thank you for your interest, but it does not work on multiple markers / groups.

jsfiddle example with many markers / groups:
https://jsfiddle.net/q9a6eaya/3/

**Comment by danzel** [comment]
Thanks! Changed the fix so that it properly handles this situation.
https://jsfiddle.net/q9a6eaya/6/ has the updated code.

**Comment by MMajo** [comment]
It works, thanks to danzel. :-)

**Comment by danzel** [comment]
Awesome, released as 1.0.3

**Comment by moahammadalt** [comment]
setLatLng is not working with CircleMarker, please any fix can be done for CircleMarker or canvas?
