### ISSUE TITLE
CircleMarker and Popups

### ISSUE THREAD

**Issue by Magnuzoid** [Leaflet/Leaflet.markercluster#754]
Hi,
I'm on version 1.0.2 through the rails gem.
My issue is that the popup does not stay correctly center aligned to the circleMarker when zooming in.
I understand the issue, but I can't see how I would correct it:
The cursors position defines the position for the popup (within the circleMarker), and when zooming in the popup stays where it got positioned, which mean that when zooming in, the popup ends up very offset, which can be really confusing if working with many closely added circles.

I found [this issue](https://github.com/Leaflet/Leaflet.markercluster/issues/431) where the [jfiddle](https://jsfiddle.net/to9g5ebs/3/) shows the same issue.

Is this intended? or is there a workaround?

Thanks

**Comment by danzel** [comment]
This isn't a leaflet.markercluster issue. This behaviour is the same in standard leaflet.
Maybe see if there is a way to make this popups appear centered on the circle rather than offset?
