### ISSUE TITLE
forEach method in MarkerClusterGroup iterates through markers not visible on the map after dragging a spiderified marker.

### ISSUE THREAD

**Issue by hh-h** [Leaflet/Leaflet.markercluster#755]
Hi, I wanted to add button for my project, so users could toggle 'edit mode'. I wrote some code and got exception. 
```
var drag = false;
$('#button').on('click', function () {
    drag = !drag;
    markers.eachLayer(function (marker) {
        marker.options.draggable = drag;
        if (marker.dragging) {
            drag ? marker.dragging.enable() : marker.dragging.disable();
        }
    });
});
```
```
Uncaught TypeError: Cannot read property 'classList' of null
```
Then I asked help in SO and @IvanSanchez suggested to me to create bug report.
Here's SO question https://stackoverflow.com/questions/41863212

Here's reproducible example by @IvanSanchez (thanks!) https://playground-leaflet.rhcloud.com/qate/1/edit?html,output

> It seems that the logic for the forEach method in MarkerClusterGroup iterates through markers not visible on the map after dragging a spiderified marker. Then the logic for enabling dragging fails, as the marker does not have an icon instance, because it has been removed from the map. @IvanSanchez 

Thanks!

**Comment by danzel** [comment]
`eachLayer` loops through every marker in the MarkerClusterGroup, whether they are visible on the map or clustered or spiderfied. (At least this is the intention, to match [L.FeatureGroup.eachLayer](http://leafletjs.com/reference-1.0.3.html#layergroup-eachlayer))
Interesting that this doesn't immediately break, I'll take a closer look.

**Comment by danzel** [comment]
Ok, this is a leaflet bug I'm pretty sure:
https://github.com/Leaflet/Leaflet/issues/5293

**Comment by danzel** [comment]
Closing this, follow the leaflet bug for updates.

**Comment by IvanSanchez** [comment]
https://github.com/Leaflet/Leaflet/pull/5295 merged.
