### ISSUE TITLE
Dist folder is missing JavaScript file

### ISSUE THREAD

**Issue by gwacker** [Leaflet/Leaflet.markercluster#757]
It appears the dist folder is missing the main leaflet.markercluster-src.js file.

It's referenced in all the example files in that directory.

**Comment by ghybs** [comment]
Hi,

See https://github.com/Leaflet/Leaflet.markercluster/issues/663
You can either get the files from the release tags, or build them.
Once you build your own files, the examples work, obviously.

The demo pages use the dist files on `gh-pages` branch, but they are quite old now.

**Comment by IvanSanchez** [comment]
Or do an `npm install`, or use any CDN like https://unpkg.com/leaflet.markercluster@1.0.3/dist/

**Comment by danzel** [comment]
Have put a txt file in the dist dir explaining this. Hopefully it reduces the amount of times it gets asked :)
