### ISSUE TITLE
not save marker icon class when zoom 

### ISSUE THREAD

**Issue by rustam87** [Leaflet/Leaflet.markercluster#759]
- Leaflet version 0.77
- Leaflet.MarkerCluster version 0.72
- Browser (with version) I'm using: all (ex. chrome 55.0.2883.87 (64-bit))
- OS/Platform (with version) I'm using: Ubuntu 16.04

I am using markercluster plugin
step 1
I create marker
```
var marker = L.marker(
                    [this.lat, this.lon],
                    {icon: icon, zIndexOffset: 100, 
                    riseOnHover: true}
                );
```
step 2 
Add marker to clustering

step 3 
Wnen click to  marker, i add className to marker
` marker._icon.className = marker._icon.className + ' visited';`

the className will change(will add 'visited' className)

step 4.   zoom '-' in map, marker's icons hide in map and clustering icon is show
step 5.  zoom '+' in map, clustering icon is hide, marker's icons is show

But clicked marker will not save new classname   'visited'

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by danzel** [comment]
That isn't a supported way to add classes to icons.
That hack won't work with markercluster as we remove and add markers from the map, when this happens the class will be removed (You can reproduce this by setting the class, removing the marker from the map then re-adding it).
You need to change the classes properly if you want them to be maintained.

**Comment by rustam87** [comment]
when i cliсk to maker icon, i need to remove marker, after i need to add new marker with new classname.

did I understand you correctly?

**Comment by rustam87** [comment]
MarkerClusterGroup.Refresh.js
There is refreshIconOptions() method

**Comment by danzel** [comment]
Use marker.setIcon to change the icon
