### ISSUE TITLE
Hide/Show Polylines between the Markers

### ISSUE THREAD

**Issue by nitya12** [Leaflet/Leaflet.markercluster#762]
Hi,

I want to show the polylines between the markers when 

1.  MarkerCluster is completely busted out to Markers.
2.  When one or two Markers(those 2 markers are outside the MarkerCluster)  and MarkerCluster is also present.Then make the polyline between marker and MarkerCluster.
3. Hide Polylines when no Markers are  Visible.

**Also Is there any way to get the information of the marker/s which are outside the MarkerCluster?**

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
