### ISSUE TITLE
Show Coverage always 

### ISSUE THREAD

**Issue by Mad97** [Leaflet/Leaflet.markercluster#763]
Hi there, 

im looking for a way to show the bounds of a cluster permanently, not only on mouse over. I've tried to achieve this by modifying the iconCreateFunction(). I tried to generate a Polygone around the shown clusters. But in this case every Cluster wich is inside the shown cluster gets marked by a Polygone, too. 

```
var markers = L.markerClusterGroup({
		showCoverageOnHover: false,
		iconCreateFunction : function(cluster) {
			var val = 0;
			for (i = 0; i < cluster.getAllChildMarkers().length; i++) {
				val = val
						+ parseInt(cluster.getAllChildMarkers()[i].options.speed)
			}
			var avg = val / cluster.getAllChildMarkers().length;
			avg = Math.round(avg * 10) / 10;
			if (cluster.polygon) {
				map.removeLayer(cluster.polygon);
			}
			
			if (cluster.getChildCount() > 2 && cluster !== this._spiderfied) {
				cluster.polygon = new L.polygon(cluster.getConvexHull());
				map.addLayer(cluster.polygon);
			}

```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
