### ISSUE TITLE
Keep the spiderfy option

### ISSUE THREAD

**Issue by augustobg** [Leaflet/Leaflet.markercluster#764]
When several polygons are cluster with the spiderfy option. 
Clicking on one will active this spiderfy option, but when clicking on another cluster, closes the first group of "spiderfy polygons". Is there an option that keeps the spiderfy clusters "open" even you are selecting another ones so you can see several groups at the same time.

Hope I explained myself clearly..
Thanks

**Comment by danzel** [comment]
Nope, we only support one spiderfy at a time.

**Comment by augustobg** [comment]
Ok, thanks anyway :)
