### ISSUE TITLE
Cluster marker icon appearing behind cluster on load.

### ISSUE THREAD

**Issue by bcccgreen** [Leaflet/Leaflet.markercluster#771]
- [Maybe] I'm reporting a bug, not asking for help
- [Yes] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [Yes] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.3
- Leaflet.MarkerCluster version I'm using: @latest
- Browser (with version) I'm using: Chrome Version 56.0.2924.87 (64-bit)
- OS/Platform (with version) I'm using: MacOS 10.12.3

Create a map, add markers with the same lat longs as per fiddle below.

## What behaviour I'm expecting and which behaviour I'm seeing

On loading I only expect to see the green cluster with a number on it, not the blue map markers behind it.

When you open the cluster and close it again, the map marker disappears and only the green number is displayed, this is how I expect it to appear on load.

## Minimal example reproducing the issue

- [yes] this example is as simple as possible
- [yes] this example does not rely on any third party code

https://jsfiddle.net/t7ty6vnh/4/

**Comment by danzel** [comment]
You are adding the markers to the map as well as the cluster:
https://jsfiddle.net/t7ty6vnh/6/
Don't call `addTo(map)` on the markers, fixed :+1:
