### ISSUE TITLE
keeping the popup opened when the marker goes into a cluster

### ISSUE THREAD

**Issue by leboovski** [Leaflet/Leaflet.markercluster#777]
What i want to do is to keep a popup of a marker opened even when the map is zoomed out and the marker becomes invisible. 

By default, after a popup is opened and user zoom outs the map, the marker becomes a part of the cluster and the popup disappears. 

I think i should remove the marker from the clustergroup and add it to map when the popup is opened and reverse it when the popup is closed but i couldn't find a suitable way to do it .

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet)

(Maybe use http://leafletjs.com/reference-1.0.3.html#map-popupopen).

**Comment by exhtml** [comment]
Hi @leboovski did you find any solution to this? I'm exactly in the same situation and can't find a straightforward way for doing this. I've tried https://github.com/ghybs/Leaflet.MarkerCluster.Freezable to uncluster all the markers if I want to keep the popup opened, and cluster them back when closing the popup, but in my implementation it throws strange and unexpected results :(
Thank you very much for your information!
