### ISSUE TITLE
Minor bug in realworld-50000 example

### ISSUE THREAD

**Issue by dom1n1k** [Leaflet/Leaflet.markercluster#781]
Link: https://github.com/Leaflet/Leaflet.markercluster/blob/master/example/marker-clustering-realworld.50000.html#L63

```
for (var i = 0; i < addressPoints.length; i++) {
	var a = addressPoints[i];
	...
}
for (var i = 0; i < addressPoints2.length; i++) {
	var a = addressPoints[i];  // must be addressPoints2[i]
	...
}
```
All points are duplicated. And almost all clusters have even size. :)

![markercluster-demo](https://cloud.githubusercontent.com/assets/1683168/25410940/633655f4-2a22-11e7-8d1f-5dbbea784732.png)

**Comment by danzel** [comment]
hahahahahahahahaha!!!
Thanks, will fix now :)
