### ISSUE TITLE
Example resource errors and Uncaught TypeError: L.markerClusterGroup is not a function

### ISSUE THREAD

**Issue by bonnyross** [Leaflet/Leaflet.markercluster#783]
To reproduce the problem, download the Leaflet.markercluster zip file from Github, extract the files and open one of the examples in the example folder in either Firefox or Chrome. There are two issues:

1. The js examples (e.g. marker-clustering-realworld.388 and others as well) are looking for leaflet.markercluster-src. js in the dist folder (Failed to load resource: net::ERR_FILE_NOT_FOUND ) when the correct file seems to be MarkerCluster.js in the src folder ? There are only .css and and a text doc in the dist folder
2. When I change the source names  and move them to the correct folder, to match the resource not found errors in the browser console, I get Uncaught TypeError: L.markerClusterGroup is not a function

The same example (realworld) runs fine from the link in the examples section in the ReadMe.md on Github

I am using Firefox 53 or Chrome Version 57.0.2987.133 on Windows 7
The leaflet version in the examples (downloaded from Github today) is 1.0.3
The leaflet.MarkerCluster version is as downloaded from the zip today

**Comment by bonnyross** [comment]
I have got round the problem with the js files in the github zip download by using npm install and copying the js files across from there. The examples work fine now and the "L.markerClusterGroup is not a function" error no longer appears.
However, the root problem is still there with the js code in the github zip download either having the wrong names or something else awry

**Comment by ghybs** [comment]
Hi @bonnyross,

> There are only .css and and a text doc in the dist folder

Please have you actually looked at the [content of that text file](https://github.com/Leaflet/Leaflet.markercluster/blob/master/dist/WhereAreTheJavascriptFiles.txt)?

TL(4 lines…);DR:
Download from the link provided in the following section:
https://github.com/Leaflet/Leaflet.markercluster#using-the-plugin

#757, #732, #663

**Comment by bonnyross** [comment]
No, I didn't notice it. It would be good if there was a note in the main readme to the effect that the zip download does not contain the .js files; perhaps on the line 'Download the v1.0.5 release' ....
