### ISSUE TITLE
zooming out is slow

### ISSUE THREAD

**Issue by Yay295** [Leaflet/Leaflet.markercluster#784]
Firefox 53.0 64-bit
Windows 7

Looking at the [10k markers example](http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.10000.html), I noticed it takes a few seconds after zooming out for the markers to clump together again. Zooming in seems fine.

**Comment by danzel** [comment]
So you load the page, then click zoom out?
It clumps together immediately for me in chrome and firefox (windows 10)

**Comment by Yay295** [comment]
Zoom in a bit first.
![](https://cloud.githubusercontent.com/assets/8922038/26082979/8b1de642-3998-11e7-88ba-f8e7f70b1e4d.gif)

**Comment by danzel** [comment]
So, load the page. Click zoom in 3 times. Pause a moment, then click zoom out?
This works smoothly for me in FF.
