### ISSUE TITLE
markerCluster and panes

### ISSUE THREAD

**Issue by treecon** [Leaflet/Leaflet.markercluster#785]
https://jsfiddle.net/fcumj09w/5/

In the above example, we have 2 marker cluster groups (clustRed and clustYellow) and a single marker outside of these groups.

I want the red marker cluster group to be on top (higher z-index) of the yellow marker cluster group, when zooming out.

I have created 3 custom panes to attach each cluster group to a different pane but it seems like panes don't work with cluster groups.
I can only make panes work with the single marker.

**Comment by ghybs** [comment]
Cross posted from SO post:
https://stackoverflow.com/questions/43963932/how-to-make-markerclusters-use-panes

**Comment by danzel** [comment]
I think I'd accept a PR to add pane support if it didn't cause any troubles

**Comment by ghybs** [comment]
Hi,

Also related to https://github.com/Leaflet/Leaflet.markercluster/issues/431#issuecomment-151040827.

But actually the latter would probably need more complex functionality, like overriding the individual markers' `pane` option.

**Comment by ckrahe** [comment]
I'm prepping a pull request that supports a pane option. Anyone here at FOSS4G in Boston? I'd like to know if I've covered everything required outside of the code itself (e.g. documentation I've done).

**Comment by ckrahe** [comment]
I noticed the [GitHub page for Leaflet.markercluster](https://leaflet.github.io/Leaflet.markercluster/) doesn't have the 1.1.0 changes. What's the right way to get that done? Is it simply a merge from master into the gh-pages branch?  Or would you like a gh-pages pull request?

**Comment by danzel** [comment]
gh-pages should be fixed now, thanks.

**Comment by ckrahe** [comment]
Great to have this wrapped up. Good time as any to close this issue?

**Comment by danzel** [comment]
Sounds good.
