### ISSUE TITLE
build/build.html referenced in README, but file not in directory.

### ISSUE THREAD

**Issue by bassena** [Leaflet/Leaflet.markercluster#787]
Unless I'm missing something? I'm looking to do a custom build.

**Comment by danzel** [comment]
Looks like I removed it almost 4 years ago in b11665eb8347b42b3b8cfc280359daf5d109cb86.
What are you looking to custom build? ATM I think we should just remove this mention, I'm not sure we can actually support removing components.

**Comment by bassena** [comment]
No worries it's all good, I thought that the README reference implied something more than running a simple `jake` command.

**Comment by danzel** [comment]
Nah, just run `jake` and it'll build everything.
I'll remove that reference, thanks.
