### ISSUE TITLE
Calling `fitBounds` Throw an Error

### ISSUE THREAD

**Issue by skipjack** [Leaflet/Leaflet.markercluster#797]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet Version: __1.03__
- Leaflet.MarkerCluster Version: __1.0.5__
- Browser and Version: __Chrome 55.0.2883.95__
- OS/Platform: Mac OS Sierra 10.12.5

1. Call Leaflet's [`fitBounds`][1] method on a map containing marker clusters.
2. See `_icon` errors in console.

## What behaviour I'm expecting and which behaviour I'm seeing

Expecting to see no errors. The following stack traces are shown:

![image](https://user-images.githubusercontent.com/8988697/27186138-6d4b9e04-51b5-11e7-9c57-17e687912914.png)

![image](https://user-images.githubusercontent.com/8988697/27186187-866cccdc-51b5-11e7-9d59-3a10781cd078.png)

Which both come back to this line in the minified source:

![image](https://user-images.githubusercontent.com/8988697/27186214-a0ee89c4-51b5-11e7-8124-4c964049e297.png)

Which seem to stem back to these lines in the actual source:

[Line 544 - 554][2] in `MarkerClusterGroup.js`

It seems the `layer` variable comes in as `undefined` for some reason. I think this may have something to do with the fact that I'm using `CircleMarker`s instead of regular `Marker`s. I have a vague memory of running into this issue before with this plugin and seeing some discussion about the use of circle markers.

[1]: http://leafletjs.com/reference-1.0.3.html#map-fitbounds
[2]: https://github.com/Leaflet/Leaflet.markercluster/blob/e387e1f48f7ce7b006588e3565072c071803e80e/src/MarkerClusterGroup.js#L544

**Comment by skipjack** [comment]
I'd be happy to submit a PR to help push a fix along if someone advises what that fix should be.

**Comment by danzel** [comment]
Test case please :)

**Comment by skipjack** [comment]
Ah ok you got me 😁 ... I'll throw a simple one together as soon as I have time (should be within the next week).

**Comment by skipjack** [comment]
Ok I threw [something together](https://www.webpackbin.com/bins/-Kn-p0B_kPQSO1PshFT1) but wasn't able to reproduce. The code where I found the bug is proprietary which means I can't share. There are some other libraries and plugins involved where I'm seeing the bug (e.g. react and leaflet.heat). Including these in the demo would require more time than I have atm. I'm definitely seeing the issue stem from this package (in the stack trace) but maybe one of the other third-party plugins is affecting things somehow.

I'll close for now and re-open if I can reproduce in that bin.
