### ISSUE TITLE
Can I cluster points based on an attribute in leaflet?

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet.markercluster#800]
The method markerClusterGroup clusters many points but returns the sum of points. In my case I want to return the Total of a specific attributes of those points. Example: I want to return the sum of an attribute called volume of those aggragated points. Is it possible ?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
