### ISSUE TITLE
Clustering maps

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet.markercluster#802]
I have created a map using leaflet, with polygons. Each polygon has its proper color(style) based on the number of inhabitants. I want to aggregates polygons as I zoom out. How can I achieve that ?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
