### ISSUE TITLE
MarkerClusterGroup to return custom polygons on hover

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet.markercluster#804]
MarkerClusterGroup is a function that clusters points and return their aggregation.

See: example

In my case I have some polygons to which I calculated the centroids. Instead of returning the lines between centroids when hovering on the cluster. I want to return the polygons associated to those centroids. which means that I'll have a highlight on the polygons that have been clustered.

Basically, this is what I did for the time being, it will create the cluster and return the volume. But I want Onhover to highlight the polygons associated.

```
var clusters = L.markerClusterGroup({

              iconCreateFunction: function(cluster) {
                var markers = cluster.getAllChildMarkers();
                var volume = 0;
                for (var i = 0; i<markers.length;i++){
                  console.log("Zones clustered: " +markers[i].name);
                  if (!isNaN(markers[i].value)){
                    volume += markers[i].value
                  }                     
                }

                return L.divIcon({ html: '<b> Total Volume: ' + volume + '</b>' });
              }
            });
```
As you can see in my code I'm able to get name of the zones(ID of polygons). but this within the markerClusterGroup Object. How can I use this data to represent it ?

**Comment by Zahma** [comment]
@danzel Can you please answer to this ? (you are experimented that's why I'm asking you :) )

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
