### ISSUE TITLE
removeLayer with map option maxZoom : over 18 not working

### ISSUE THREAD

**Issue by gpalla** [Leaflet/Leaflet.markercluster#805]
js_includes_sp.jsx?v=01-29-2017_2025&lp=Tue_Jul_11_11_57_19_PDT_2017&c=2_42:11973 TypeError: Cannot read property 'removeObject' of undefined
    at e._removeFromGridUnclustered (x_mpany_core.leaflet.markercluster-src.j.jsdbx:683)
    at e._removeLayer (x_mpany_core.leaflet.markercluster-src.j.jsdbx:732)
    at e.removeLayer (x_mpany_core.leaflet.markercluster-src.j.jsdbx:173)
    at Object.map.unloadMarker (eval at providers (js_includes_sp.jsx?v=01-29-

To reproduce:
Step 1: generate a leaflet map with map options of: minZoom: 4
Step 2: addLayer to marker cluster
Step 3: removeLayer from marker cluster

**Comment by gpalla** [comment]
sorry also add leaflet option of : minZoom: 3

**Comment by gpalla** [comment]
after some troubleshooting it looks like the minZoom option is the cause for the crash you can set maxZoom over 18.

**Comment by ghybs** [comment]
Hi,

Please can you provide consistent details (`minZoom` or `maxZoom`?) and a live reproduction case, so that it is possible to investigate?

I am unable to reproduce your issue with the given steps:
http://playground-leaflet.rhcloud.com/sizu/1/edit?html,output

**Comment by arkhemlol** [comment]
I can confirm that problem occurs. In my case when minZoom for map is set. However, I can't reproduce it with fiddle you provided.

**Comment by danzel** [comment]
Please create a new issue with a jsfiddle that reproduces it.

**Comment by charlieforward9** [comment]
Had this happen when I temporarily changed my zoom bound from 15 to 1 to debug, not sure about much else but I just put the bound back at 15 and it fixed. This might help someone down the road.
