### ISSUE TITLE
Issue with storking data in Marker

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet.markercluster#809]
I have extended my leaflet object by setting two now attributes:
    - Value
    - Name

```
var customMarker = L.Marker.extend({
                options: {
                name: '',
                value: ''
                }
             });
```

Then I call this method:

```
L.geoJson(centroids,{
              pointToLayer: function(feature,geometry){
                var marker = new customMarker(geometry);
                marker.value = donnees[feature.properties.Index];
                marker.name = feature.properties.Index;
                console.log("name : "+marker.name+" volume : "+marker.volume)
                return marker;
              }
        });
```

But I noticed that not all the marker.value are stored in my markers. some have unidentified as value.

**Comment by ghybs** [comment]
Note: posted on SO as https://stackoverflow.com/questions/45220086/leaflet-not-taking-all-data-when-extending-markers

Not sure how this is related to Leaflet.markercluster plugin…
