### ISSUE TITLE
MarkerClusterGroup not updating data in a good way.

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet.markercluster#810]
I'm currently developing a visual for power BI using the leaflet library and markerclustergroup as its plugin. 

The MarkerClusterGroup works perfectly when no filter is performed on the data used on the dataView.

Here is what I did so far ..

// Remove Layer of clusters when New data is available.
    if (this.centr){

          this.clusters.clearLayers();
        
            }

// Here I'm created my Markers : 

    this.centr = L.geoJson(centroids,{
                  pointToLayer: function(feature,geometry){
                    var marker = new customMarker(geometry,{icon:icon});
                    marker.value = Population;
                    marker.name = Name;
                    return marker;
                  }
                });
    
// Here I clear the clusters in case they are not empty for the case of applying filter.

              if (this.clusters != undefined){
                this.clusters.clearLayers();
    }

// Here Creating the clusters

                      this.clusters = L.markerClusterGroup({
                      polygonOptions: {
                        fillColor: "Blue",
                        color:"black"
                      },
                      maxClusterRadius:100,
                      singleMarkerMode: true,
                      showCoverageOnHover: true,
                      iconCreateFunction: function(cluster) {
                        // Some Code
                        if (volume == 0){
                          return L.divIcon({html: '<b> Empty !</b>'});
                        }
                        else
                        return L.divIcon({html: '<b>' + volume + '</b>', iconSize: [47,15]});
                      }
                    });
    
              this.clusters.addLayer(this.centr);
              this.map.addLayer(this.clusters);

Applying this code, when I filter on some data, I get the new clusters but when I zoom Out or zoom in (to cluster) I get this error : 

Uncaught TypeError: Cannot read property '_leaflet_id' of undefined
    at n (<anonymous>:38:536)
    at e.removeLayer (<anonymous>:40:805)
    at e._hideCoverage (<anonymous>:374:20)
    at e.fire (<anonymous>:38:16896)
    at e._moveEnd (<anonymous>:39:9725)
    at e.<anonymous> (<anonymous>:39:16415)

**Comment by Zahma** [comment]
@danzel  what do you think about this ? !

**Comment by danzel** [comment]
I think you shouldn't @ people without good reason.
And I think you should make a reproducing minimal test case if you think this is a bug in markercluster
