### ISSUE TITLE
Cluster closes directly 

### ISSUE THREAD

**Issue by xell66** [Leaflet/Leaflet.markercluster#812]
## How to reproduce

- Leaflet version I'm using: 1.03
- Leaflet.MarkerCluster version I'm using: 1.06
- Browser (with version) I'm using: Chrome 59
- OS/Platform (with version) I'm using: Android 6

Press on a Cluster with your thumb (touched area needs to be slightly bigger than the cluster icon)
Cluster is opening and will close immediately

## What behaviour I'm expecting and which behaviour I'm seeing
Only a single touchevent should be processed and not a second that closes the cluster again

**Comment by danzel** [comment]
So this happens on the included examples?
What touch events are causing it?

**Comment by xell66** [comment]
It does not happen on the example.
We may solved the problem. The issue was probably that we reloaded all markers when the map is moved. So by opening the cluster on a touch device the map moved slightly and closed the cluster do to a marker reload.
