### ISSUE TITLE
Problem when click on some items. Leaflet generate a lot of lines around marker.

### ISSUE THREAD

**Issue by malajangjelin** [Leaflet/Leaflet.markercluster#814]
Leaflet version - 1.1.0
Leaflet marker cluster - 1.0.6
Browser - Chrome  60.0.3112.90
OS - MacOS Siera
<img width="1440" alt="screen shot 2017-08-08 at 11 44 27 am" src="https://user-images.githubusercontent.com/25714384/29081171-c9fed784-7c2f-11e7-8f1c-332725e60750.png">

Is there any quick way to fix that?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by danzel** [comment]
The lines are part of the spiderfier, I'm not sure why your map looks all broken like that, this is almost certainly an application bug.
If you cannot reproduce as Ivan mentions, then this isn't a bug.
Please create a new issue with a minimal reproducable case if you can.

**Comment by malajangjelin** [comment]
Here we go

https://timeinc.slack.com/files/angjelin.malaj/F6KNX22F4/app_js.js

**Comment by malajangjelin** [comment]
Well. It works fine when we have like 7 items. 
But have a weird behavior when we have 300 or so.

**Comment by malajangjelin** [comment]
@danzel Can you reopen the issue?

**Comment by danzel** [comment]
Only if there is a minimal reproducible test case like Ivan has asked for.
