### ISSUE TITLE
404 on MarkerCluster.Default.css

### ISSUE THREAD

**Issue by edent** [Leaflet/Leaflet.markercluster#818]
- [X] I'm reporting a bug, not asking for help
- [X] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

https://unpkg.com/leaflet.markercluster@1.0.6/dist/MarkerCluster.Default.css

Returns the error 

> Cannot find file "/dist/MarkerCluster.Default.css" in package leaflet.markercluster@1.0.6

The README says to use https://unpkg.com/leaflet.markercluster@1.0.6/dist/

This was working earlier today - but appears to have broken recently.

- Leaflet version I'm using: 1.1.0
- Leaflet.MarkerCluster version I'm using: 1.0.6
- Browser (with version) I'm using: Firefox 54.0 (64-bit)
- OS/Platform (with version) I'm using: Linux
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing

The file should load.

## Minimal example reproducing the issue

`<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.0.6/dist/MarkerCluster.Default.css">`

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/beg/1/edit?html,output or any other jsfiddle like site.

**Comment by danzel** [comment]
works for me
![image](https://user-images.githubusercontent.com/393086/29338098-f16d08f2-8267-11e7-91ae-6b38affabe2a.png)

Maybe unpkg bug?

**Comment by edent** [comment]
Try clearing your cache and refreshing. Broken here. Tested on two different devices with different ISPs.

![bug](https://user-images.githubusercontent.com/837136/29339168-ebf459ea-8210-11e7-8958-55b47b46cb36.png)

**Comment by danzel** [comment]
Definitely works fine here. Please raise an issue with unpkg

**Comment by jimaek** [comment]
You can also use jsDelivr if you want https://cdn.jsdelivr.net/npm/leaflet.markercluster@1.0.6/dist/MarkerCluster.Default.css

Its built for production usage and avoids such problems.

**Comment by edent** [comment]
Working again now.
