### ISSUE TITLE
Leaflet markercluster popup in div contains popup of all markers

### ISSUE THREAD

**Issue by gummitree** [Leaflet/Leaflet.markercluster#821]
Hey guys,

im using leaflet 1.2.0 http://cdn.leafletjs.com/leaflet/v1.2.0/leaflet.zip
 and Leaflet. markercluster https://github.com/Leaflet/Leaflet.markercluster

in need some help with my project and markercluster. Im getting the data by a database and all working fine. I managed to display the popup of a single marker in a div on my page and a popup of clustered markers also. But the popup contains info of all markers, not of only the markers that are clustered i hover over. 

See the example Pic, i hover over the cluster with 2 markers, but getting popup of all markers.
Please help me, cant fix this by my own. 

https://picload.org/view/rwccogdr/markerclusterpopup.png.html

JSFiddle see // ClusterMarker Popup
https://jsfiddle.net/kt9j2ron/

**Comment by danzel** [comment]
We don't fix bugs in peoples code.
