### ISSUE TITLE
spiderfy all markers

### ISSUE THREAD

**Issue by slowkazak** [Leaflet/Leaflet.markercluster#822]
Is it possible to spiderfy many clusters  on zoom  or draw spiderfied all clusters by default?
leaflet.markercluster@1.0.6

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
