### ISSUE TITLE
There is no 0.7 version in the tag

### ISSUE THREAD

**Issue by brianpchsu** [Leaflet/Leaflet.markercluster#823]
Hi, 
I tried to install 0.7 version but I can't do that in npm or yarn. It seems like there is no 0.7 version tag!

![screen shot 2017-08-30 at 3 24 34 pm](https://user-images.githubusercontent.com/8574617/29897817-91aba438-8d97-11e7-8fdf-4021158fe811.png)

**Comment by danzel** [comment]
There is not.
There is a branch though (it's in the readme)
https://github.com/Leaflet/Leaflet.markercluster/tree/leaflet-0.7
