### ISSUE TITLE
Clustering markers.

### ISSUE THREAD

**Issue by tthyregod** [Leaflet/Leaflet.markercluster#824]
I have tried to use the marker.slideTo function instead of using setLatLng.
When 2 markers ends close to each other and makes a cluster everything works.
But when they move away from each other again (using slideTo) the cluster does not split up and the markers does not move. That part works fine when using setLatLng.

Any solution to solve it ?

**Comment by danzel** [comment]
Take a look at the implementation of slideTo and see what it does differently.
You probably want to remove the marker from the cluster, then slide it, then add it again.
