### ISSUE TITLE
use library with canvas points

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet.markercluster#825]
Sorry I have this question,
Is it possible to use markerclustergroups with Canvas points instead of markers ?
if not is it long process to make it accept canvas points ?

**Comment by danzel** [comment]
Canvas points?

**Comment by IvanSanchez** [comment]
I'm gonna guess the OP means `L.CircleMarkers` rendered in a `L.Canvas` renderer.

**Comment by Zahma** [comment]
Canvas circles and lines. In fact i'm looking to merge use "Canvas FlowMap Layer" with "Markerclustergroups" to aggregate Flows, origins, and destinations.

**Comment by danzel** [comment]
Only point data:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L90
This should be CircleMarker and Marker.
