### ISSUE TITLE
Server side cluster generation

### ISSUE THREAD

**Issue by stefanocudini** [Leaflet/Leaflet.markercluster#826]
Anyone know an application of this plugin server side in nodejs?

I would like to create a geojson that represents the clusters generated with the childCount among its properties.

many tnks
Stefano

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by stefanocudini** [comment]
ok @IvanSanchez,
maybe you're right
but I thought if perhaps the basic algorithm would be generic it could also work in NodeJs environment (like so many javascript libraries born for browsers and modified to run on server side)

tnk
Stefano
