### ISSUE TITLE
spiderfy on startup?

### ISSUE THREAD

**Issue by tenznhok** [Leaflet/Leaflet.markercluster#830]
is there a way that show all markers spiderfy on startup without showing all clusters first?

**Comment by danzel** [comment]
No sorry. We only support spiderying one cluster at a time also

**Comment by tenznhok** [comment]
You have 

      cluster.on('clusterclick', function(a){
            a.layer.spiderfy();
        })

the spiderfy() only works when clicking on the cluster. Is there any option that if I click on a button to spiderfy that cluster instead of clicking onto that cluster?
