### ISSUE TITLE
Workflow for dynamically, periodically adding and removing markers?

### ISSUE THREAD

**Issue by ScottBeeson** [Leaflet/Leaflet.markercluster#833]
I was hoping someone could simply walk me through the logic of how dynamic markers would work.

The readme simply says to create a cluster group and add markers to it.  I'm polling for new markers every few seconds.  Would I keep adding new markers to the existing cluster group?  Do I just have one cluster group or would there be one per poll?  Or perhaps one per "area"?  The docs are a bit terse for me. :(

I'm not looking for code, just the overall logic.

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
