### ISSUE TITLE
Add support for Leaflet 1.1.0+

### ISSUE THREAD

**Issue by rkatka** [Leaflet/Leaflet.markercluster#835]
Leaflet version 1.1.0 added ES6 and Rollup that made all leaflet objects non-extendable.  This results in the current version of Leaflet.markercluster (1.1.0) no longer being compatible with the latest versions of Leaflet.

**Comment by danzel** [comment]
Ah dumb.
I think there is a plugin upgrade somewhere? Someone wanna find and link it please.
I'm pretty busy with other things ATM, so hoping someone else can pick this up. :pray:

**Comment by ghybs** [comment]
Hi @rkatka,

While you are absolutely right that Leaflet 1.1.0 introduced a [compatibility bug](https://github.com/Leaflet/Leaflet/issues/5650) for plugins that need to extend some base objects (like `L.Util` and `L.DomUtil`), I do not recall such extension requirements in Leaflet.markercluster?

A quick test shows no particular issue: (Leaflet 1.1.0 + Leaflet.markercluster 1.1.0)
https://plnkr.co/edit/4xjaKXfBk6AnSY0Q388w?p=preview

That being said, if you can just upgrade to Leaflet 1.2.0, the above mentioned bug [has been resolved](https://github.com/Leaflet/Leaflet/pull/5658).

**Comment by danzel** [comment]
This has been fixed since.
