### ISSUE TITLE
Dynamic updated geojson data isn't displayed

### ISSUE THREAD

**Issue by swordwolt** [Leaflet/Leaflet.markercluster#837]
- [ ] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported
## How to reproduce
- Leaflet version I'm using: 1.0.3
- Leaflet.MarkerCluster version I'm using: 1.1.0
- Browser (with version) I'm using: Tested with diffrent browser, different versions
- OS/Platform (with version) I'm using: Windows

Hi, i think there is a problem with the updating data on geojson layers. As you can see at jsfiddle, i try to update the geojson layer after the marker cluster group is initialized (add more data to it). The problem is, the additional data isn't displayed after I refresh the marker cluster group.

## What behaviour I'm expecting and which behaviour I'm seeing
I expact the map to display 12 markers instead of 6 at the end.

## Minimal example reproducing the issue
- [x] this example is as simple as possible
- [x] this example does not rely on any third party code
https://jsfiddle.net/66wjx03p/

**Comment by danzel** [comment]
That is not what refreshMarkers is for, check the docs.
