### ISSUE TITLE
zoomtoBounds method drastically increases map zoom

### ISSUE THREAD

**Issue by rudra0713** [Leaflet/Leaflet.markercluster#839]
Hi, in my current view, i have two distinct markers and two clusters each with four members. Max zoom is 25 and current zoom is 15. Every time, I click a cluster of 4 markers, suddenly the zoom level extends to 21. Why is this happening ? OSMtiles often tend to take a higher loading time when zoom level is greater than 20. What I want is to keep the zoom level below 20 when a cluster is clicked.

I printed the bottomcluster._zoom (line : 847 in Markerclustergroup.js) and it gives me a value of 20 ? From where is it getting such a high value ?

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by danzel** [comment]
When you click a cluster, the default implementation is to zoom to the bounds of that cluster, so if your makers are close together, it can zoom down quite a bit.
Look at the code that references `zoomToBoundsOnClick` and replace with your own implementation

**Comment by rudra0713** [comment]
Thank you very much for your quick response. Actually, I am not trying to
report any bug or adding a new feature rather I am trying to modify one.
Right now, when we are breaking clusters sequentially, clicking a cluster
of 2 child apparently shows the individual markers. However, what I want is
to show all the children markers when a cluster has less or equal four
children and it has been clicked. Additionally, I never want to exceed the
zoom level above 20. Can you please help me in any way ?

This question is not specific to leaflet. I know  this is not an  ideal
place to ask a question and if you ask, I will create a new issue. I just
think the question is quite simple and I am missing something simple.

Thanks
