### ISSUE TITLE
Problem loading leaflet.markercluster in a js file in a project node

### ISSUE THREAD

**Issue by jemega** [Leaflet/Leaflet.markercluster#840]
Hi, I'm trying to use the library in a project importing the markercluster (line: import './libs/leaflet.markercluster-src';) in a node project on a js file, but when I build the project it does not create the mapping source of markercluster and if I copy the leaflet.markercluster file in dist/libs and run the project the result is the next error: 
Plugin component error Error: (SystemJS) L is not defined
	ReferenceError: L is not defined

Can you help me to resolve this issue?

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
