### ISSUE TITLE
Leaflet clusterclick

### ISSUE THREAD

**Issue by verediongzon** [Leaflet/Leaflet.markercluster#842]
Hi there, Does this module has clusterclick event, if yes how can I use it? If not do you have any recommendation on doing our making it? I want to achieve getting the center point of the clustered coordinates.

I referred this here.
https://github.com/Leaflet/Leaflet.markercluster#events

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
