### ISSUE TITLE
Question to get current marker 'id' 

### ISSUE THREAD

**Issue by NiekRood** [Leaflet/Leaflet.markercluster#843]
- [ ] I'm reporting a bug, not asking for help
- [ ] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

----
I have a question regarding markercluster with leaflet-gpx.

I am using Leaflet.markercluster for displaying many routes.  What I am trying to achieve is that if a user 'mouse-over' a  marker the GPX track is shown on the map.

My code for displaying the clustering is:
```javascript
    var markers = L.markerClusterGroup();
    for (var i = 0; i < markers_var.length; i++) {
        var a = markers_var[i];
        var title = a[3];
        var gpxfile= a[2];
  ` 
        var marker = L.marker(new L.LatLng(a[0], a[1]), {
        
            title: title
        });
      
        marker.bindPopup(title);
        markers.addLayer(marker);
  

        marker.on('mouseover', function (e)
{
*********
I think the solution has to go here

*******
  });

'''
IS there a way to get the current  var gpxfile on  the  'mouseover' marker?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
