### ISSUE TITLE
TypeError: L.markerClusterGroup is not a function

### ISSUE THREAD

**Issue by jvgranados** [Leaflet/Leaflet.markercluster#845]
## How to reproduce
Hi, I'm trying to use the library but I get the error on the next line:
`var markers = L.markerClusterGroup();`

Any idea how i could be resolved?

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
