### ISSUE TITLE
How to order the markers ?

### ISSUE THREAD

**Issue by kirantpatil** [Leaflet/Leaflet.markercluster#847]
Hi, How to order the markers, even though I added them serially it is not getting displayed in order.

## How to reproduce

- Leaflet version I'm using: 1.2.0
- Leaflet.MarkerCluster version I'm using: 1,2.0
- Browser (with version) I'm using: Firefox 57.0.1
- OS/Platform (with version) I'm using: 

## What behaviour I'm expecting and which behaviour I'm seeing
The markers are not arranged like 1,2,4,5,6,7 but 1,2,7,6,5,4. Please find the below screenshot.
![screenshot-2017-12-6 containermon](https://user-images.githubusercontent.com/1178055/33662899-a5832a58-dab3-11e7-8566-19ae54fcfb48.png)

## Minimal example reproducing the issue
```

 var markers = L.markerClusterGroup({maxClusterRadius: 41.5}).addTo(map);

                   var m1 =  L.marker(cont_ll_1, {
                        zIndexOffset: 100,
                        icon: new L.AwesomeNumberMarkers({
                      number: position2,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + device.name).openTooltip();

                     var m2 =  L.marker(cont_ll_2, {
                        zIndexOffset: 200,
                    icon: new L.AwesomeNumberMarkers({
                      number: position1,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + name1).openTooltip();

                     var m3 =  L.marker(cont_ll_4, {
                        zIndexOffset: 300,
                    icon: new L.AwesomeNumberMarkers({
                      number: position4,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + name4).openTooltip();

                     var m4 =  L.marker(cont_ll_5, {
                        zIndexOffset: 400,
                    icon: new L.AwesomeNumberMarkers({
                      number: position5,
                      markerColor: "blue"
                  })}).addTo(markers).bindTooltip("name:" + name5).openTooltip();
```

**Comment by danzel** [comment]
Markers in leaflet are never guaranteed to be ordered.
You'll need to probably override `spiderfy()` in 
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js
to sort the childMarkers result before spiderfying them.
