### ISSUE TITLE
How to get the number of clusters and its markers ?

### ISSUE THREAD

**Issue by kirantpatil** [Leaflet/Leaflet.markercluster#848]
Hi,

I would like to know the number of clusters and its markers as soon as I open the map without zoom-in

## How to reproduce

    Leaflet version I'm using: 1.2.0
    Leaflet.MarkerCluster version I'm using: 1,2.0
    Browser (with version) I'm using: Firefox 57.0.1
    OS/Platform (with version) I'm using:

## What behaviour I'm expecting and which behaviour I'm seeing

Ex: For below image I would like to get, 1 cluster with 6 markers (marker1, marker2, marker4, marker5, marker6, marker7) and each marker details (name, latlng, ...)

![screenshot-2017-12-6 containermon](https://user-images.githubusercontent.com/1178055/33712351-20b57636-db6d-11e7-9c3d-37eee681c351.png)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
