### ISSUE TITLE
markers are showing wrong lat data after subsequent clicks

### ISSUE THREAD

**Issue by kirantpatil** [Leaflet/Leaflet.markercluster#849]
## How to reproduce

Leaflet version I'm using: 1.2.0
Leaflet.MarkerCluster version I'm using: 1,2.0
Browser (with version) I'm using: Firefox 57.0.1
OS/Platform (with version) I'm using:

Step 1. Create map 
Step 2. Add marker with latlng to marker cluster
Step 3. Add code shown in the below to display lat details in console.log

## What behaviour I'm expecting and which behaviour I'm seeing

![screenshot from 2017-12-07 18 14 46](https://user-images.githubusercontent.com/1178055/33716027-98eb39b2-db7a-11e7-9fb6-128242624a75.png)

Next time clicking on cluster shows below output

![screenshot from 2017-12-07 18 16 28](https://user-images.githubusercontent.com/1178055/33716081-cc282222-db7a-11e7-81ae-07482f4826ca.png)

## Minimal example reproducing the issue

markers.on('clusterclick', function (a) {
        // a.layer is actually a cluster
        console.log('cluster ' + a.layer.getAllChildMarkers().length);

        var markers = a.layer.getAllChildMarkers();
        var i = 0;
    for( var i = 0; i<markers.length; i++ ) {
       console.log('marker ' + markers[i].options.icon.options.number + '\n');
       console.log('marker ' + markers[i]._latlng.lat+ '\n');
    }
});

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js#L158
