### ISSUE TITLE
Error with addLayer method.

### ISSUE THREAD

**Issue by AlekseySorokin** [Leaflet/Leaflet.markercluster#852]
Hi. I need someone's help.
I can't fix a problem with the addition of markers by the coordinates that I get from the server.
Error appears when I try to add marker with method `addLayer` of the `DG.markerClusterGroup`. 
`Uncaught TypeError: Cannot read property '_zoom' of undefined`.

From the console I can see that the error occurs at the reference to the property `__parent` of markers. 
(https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L123)

In the code is something like
```
	let marker = DG.marker(cordinates, { id: id, icon: icon , type: 'pin' });
	clusters.addLayer(marker);	
```

The fact that the page is loaded with two cards and one of them occurs the problem.

How do you think what could be the problem??

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
