### ISSUE TITLE
[FAQ] method to get the list of cluster of radius 2m and associated markers

### ISSUE THREAD

**Issue by kirantpatil** [Leaflet/Leaflet.markercluster#854]
Hi,

Sorry, this is not a bug, would like to know if there is any method to get the list of clusters of radius 2m and associated markers.

From my understanding I don't think there is a built in method/function to do it in markercluster. 

But I am hoping to get any kind of help/pointer to solve it.

Thanks.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
