### ISSUE TITLE
show all clusters of maxClusterRadius without zooming in ?

### ISSUE THREAD

**Issue by kirantpatil** [Leaflet/Leaflet.markercluster#855]
Hi,

Sorry, for urgent help I am posting it in issue.

How to show all clusters of maxClusterRadius without zooming in ?

I would like to view all 3 clusters having maxClusterRadius to be shown on map without zooming in.

Please help me.

### Map before zooming in shows one cluster with 12 markers as below
![screenshot-2017-12-15-3-36 containermon](https://user-images.githubusercontent.com/1178055/34037402-adcd3648-e1ae-11e7-8f8e-e8cfbfb1283a.png)

### Map after zooming in show 3 clusters having 7, 3 and 2 markers respectively
![screenshot-2017-12-15-3-41 containermon](https://user-images.githubusercontent.com/1178055/34037409-b20eeb0c-e1ae-11e7-8715-40e2d24c3311.png)

Thanks,
Kiran.

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
