### ISSUE TITLE
zoomToShowLayer(layer, callback) to get the marker cluster

### ISSUE THREAD

**Issue by kirantpatil** [Leaflet/Leaflet.markercluster#856]
Hi,

I am using zoomToShowLayer to zoom to the marker and I would like to get the cluster of that marker after zooming in to the layer.

I used below code but getting type error(TypeError: layer1 is undefined)
```

         layer1 = markers.zoomToShowLayer(marker_f);
          var count = layer1.getAllChildMarkers().length;
          alert("Marker count: " + count );
```

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
