### ISSUE TITLE
zoomToShowLayer(layer, callback) issue

### ISSUE THREAD

**Issue by kirantpatil** [Leaflet/Leaflet.markercluster#857]
As per the document zoomToShowLayer : Zooms to show the given marker (spiderfying if required), calls the callback when the marker is visible on the map.

I have added timeout function in the callback function.

Now the map is not showing till the timeout function is getting executed, but I expected map to open and zoom and then call the callback. 

----

## How to reproduce

Leaflet version I'm using: 1.2.0
Leaflet.MarkerCluster version I'm using: 1,2.0
Browser (with version) I'm using: Firefox 57.0.1
OS/Platform (with version) I'm using: Ubuntu 16.04

## Minimal example reproducing the issue

```
markers.zoomToShowLayer(marker, find_m(marker));

function find_m(marker) {
      setTimeout(otherStuff, 2000);
      function otherStuff(marker) {
     ...
     ...    
 }
}
```

**Comment by danzel** [comment]
Please create a working reproduction: http://leafletjs.com/edit.html

**Comment by kirantpatil** [comment]
Thanks @danzel , Finally, I know how to create a working reproduction code.

I have updated the code and you need to input container name from Container0 to Container12 and type enter button on keyboard.

Now it waits for  2 seconds in callback and then Zoom into the layer and marker.

**Comment by kirantpatil** [comment]
Here is updated code: https://plnkr.co/edit/T28jpQnAoP0zcctaeuAx?p=preview

**Comment by danzel** [comment]
Sorry we aren't here to debug your app, only to find bugs in leaflet.markercluster.
Please create a completely minimal reproduction of the bug in leaflet.markercluster and we can take a look.

**Comment by kirantpatil** [comment]
To make it clear and I stripped most of the code of my app.

I have added console.log in code to verify exactly after 2 seconds the map zooms to marker.

You need to open browser console and on the app type Container0 and hit enter, it will wait 2 seconds to zoom into the Container0 marker.

This is the best I could do so that you see the bug on the map and timestamp on the console as well.

**Comment by kirantpatil** [comment]
I removed the minZoom and maxZoom as below and the bug still persists, where it is waiting(2 seconds) for callback function to return and then map Zoom in to the marker.

`var map = L.map('leaflet');`

**Comment by kirantpatil** [comment]
I resolved it by moving `markers.zoomToShowLayer(marker, find_m(marker));` out of for loop and now map zoom in to marker without delay and setTimeout function fires after that.

@danzel, thanks for your kind cooperation.
