### ISSUE TITLE
Property 'markerClusterGroup' does not exist on type 'typeof node_modules/@types/leaflet/index"'

### ISSUE THREAD

**Issue by shopsoy** [Leaflet/Leaflet.markercluster#858]
Im using leaflet with angular 4 (angular-cli)

When using only Leaflet I cna display the mao and the markers, but when using Leaflet.markercluster Im always getting the errror:
 _error TS2339: Property 'markerClusterGroup' does not exist on type 'typeof "/opt/map_dashboard/portal-src/node_modules/@types/leaflet/index"'._

To include Leaflet and Leaflet.markercluster this is what I did:

```
npm install leaflet --save
npm install leaflet.markercluster --save
```
Then in the **.angular-cli.json** in the scripts section:

```
"scripts": [
	    "../node_modules/jquery/dist/jquery.min.js",
		...
		"../node_modules/leaflet/dist/leaflet.js",
		"../node_modules/leaflet.markercluster/dist/leaflet.markercluster.js"
	  ]
```

Then in my component:
```
...
import * as L from 'leaflet';
...
```

Its possible to call all functions fom Leaflet but when I call teh ones belonging form Leaflet.markercluster such:

`var markerCluster = L.**markerClusterGroup**();`

It will always returning the error 
`Property 'markerClusterGroup' does not exist on type 'typeof node_modules/@types/leaflet/index"'`

Can someone help on how to integrate with angular4 project.

Thanks in advance

**Comment by danzel** [comment]
You probably need `@types/leaflet.markercluster`.

**Comment by shopsoy** [comment]
Hi,

Just found a solution and no need for the types.

Then in the .angular-cli.json in the scripts section:
No need to import in the scripts section so it will be like this:
```
"scripts": [
	    "../node_modules/jquery/dist/jquery.min.js",
		...
		"../node_modules/leaflet/dist/leaflet.js"
	  ]
```
Then in my component before class WE just need to declare the L variable as global and here import the leaflet.markercluster:


```
declare var L: any;
import 'leaflet.markercluster';
```
