### ISSUE TITLE
How do i know if i am at max zoom?

### ISSUE THREAD

**Issue by billymedia** [Leaflet/Leaflet.markercluster#859]
I have a requirement where i need to list all points in a table rather than allow the map to spider out all the points. I am aware of onclusterclick and know how to disable the spidering (spiderfyOnMaxZoom), but how do i know if i am at the max zoom level to know to populate my table? i dont want to be populating on every cluster click, only when they reach the max zoom level.

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
