### ISSUE TITLE
anchor undefined error, clusters don't render

### ISSUE THREAD

**Issue by Azmisov** [Leaflet/Leaflet.markercluster#861]
Here is the test case:
https://jsfiddle.net/pswbd2ec/
`TypeError: anchor is undefined` is thrown in console

The error only happens for some data, oddly enough. I just happened to come across the error with these marker coordinates.

I am able to fix the issue by manually supplying a `tooltipAnchor` for the clusters. For example, adding `cluster.options.tooltipAnchor = L.point(0,0);` in the icon create function. I wasn't sure if this is a bug with leaflet core or markercluster. I presume the markercluster class implementation is failing to set that option somewhere?

**Comment by danzel** [comment]
Hm, looks like we need to update our default icon to include some new options for compatibility with leaflet 1.something.

`//Cludge for Icon, we pretend to be an icon for performance`
I think this will be it lol...

**Comment by danzel** [comment]
The markercluster unit tests don't work on leaflet >= 1.1.0, so I'm gonna need to fix them. Looks like MCG is some amount of broken in general since 1.1.0.

**Comment by danzel** [comment]
Should be fixed in 1.3.0
