### ISSUE TITLE
Tests don't work with leaflet 1.1.0+

### ISSUE THREAD

**Issue by danzel** [Leaflet/Leaflet.markercluster#863]
I've started fixing it in here:
https://github.com/Leaflet/Leaflet.markercluster/tree/fixing-for-leaflet-110

Looks like the remaining ones are probably related to sinon, the fake time stuff doesn't seem to work any more for some reason.
I'm probably not going to have time to look at this any time soon, so please pick up if you want them fixed :) Otherwise we'll be testing against 1.0.3 forever.

**Comment by skipjack** [comment]
I take it this is the reason for the frozen peer dep:

``` json
"leaflet": "~1.0.3"
```

which yields:

``` bash
npm WARN leaflet.markercluster@1.3.0 requires a peer of leaflet@~1.0.3 but none was installed.
```

when using this package with a newer version of leaflet.

From a consumer standpoint, I'm not seeing any issue with this package behavior-wise with `leaflet@1.3.1` although I understand it might be something minor.

> Looks like the remaining ones are probably related to sinon, the fake time stuff doesn't seem to work any more for some reason. I'm probably not going to have time to look at this any time soon, so please pick up if you want them fixed :) Otherwise we'll be testing against 1.0.3 forever.

I may be able to take a stab at this or at least investigate a little more... can you elaborate more on the "fake time stuff" and point to where/how it's used in this package? Was this an unintentional breaking change by `leaflet` or is this package using a `leaflet` internal that's subject to change within majors?

**Comment by danzel** [comment]
We use `sinon.useFakeTimers()` which AFAIK overrides `setTimeout` / `setInterval`, allowing us to trigger them rather than needing to wait the time.
I think leaflet doesn't use these for animation timing any more, it just uses the transitionend events.
Haven't dug too much in to it, but that's probably it.
Not sure how to make this work, need to do some research in to it.

**Comment by danzel** [comment]
AFAIK everything works, I haven't tested super lots though.

**Comment by azrin1972** [comment]
@danzel, I'm trying to use this plugin in Thingsboard and I got the same warning. 

```
npm WARN leaflet.markercluster@1.3.0 requires a peer of leaflet@~1.0.3 but none was installed.
```

I did an import as follows:

```
import 'leaflet/dist/leaflet.css';
import 'leaflet.markercluster/dist/MarkerCluster.css';
import 'leaflet.markercluster/dist/MarkerCluster.Default.css';
import * as L from 'leaflet';
import 'leaflet-providers';
import 'leaflet.markercluster';
```

and later calling as follows:

```
this.map = L.map($containerElement[0]).setView([0, 0], this.defaultZoomLevel || 8);
this.clusters = markerclusterGroup();
```

but unfortunately I got 

```
Error: s.markerClusterGroup is not a function. (In 's.markerClusterGroup()', 's.markerClusterGroup' is undefined)
```

in the javascript console.

Not sure what's missing. Any advise?

**Comment by himerus** [comment]
Yeah, this needs to be addressed. Since this was changed to ~1.0.3 in https://github.com/Leaflet/Leaflet.markercluster/commit/0f8b3d102e91857f9247679d02837b4d8c1610c7, there have been 8 new versions of leaflet.markercluster, and 4 new releases to Leaflet proper.

I'm not capable of investigating any possible regressions when using the latest Leaflet, but in my development environment, they seem to be working fairly well together.

**Comment by pwalker** [comment]
I've found in practice that what I use generally works with the version mismatch, but the test suite fails when using leaflet~1.3.1:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) addLayer adding a single marker appears when added to the group before the group is added to the map FAILED
	undefined is not an object (evaluating 'el._leaflet_pos')
	getPosition@node_modules/leaflet/dist/leaflet-src.js:2765:11
	_getMapPanePos@node_modules/leaflet/dist/leaflet-src.js:4378:21
	_getTopLeftPoint@node_modules/leaflet/dist/leaflet-src.js:4390:50
	getPixelBounds@node_modules/leaflet/dist/leaflet-src.js:3827:43
	getBounds@node_modules/leaflet/dist/leaflet-src.js:3758:35
	_getExpandedVisibleBounds@src/index.js:1087:53
	onAdd@src/index.js:613:60
	_layerAdd@node_modules/leaflet/dist/leaflet-src.js:6487:13
	whenReady@node_modules/leaflet/dist/leaflet-src.js:4367:17
	addLayer@node_modules/leaflet/dist/leaflet-src.js:6549:17
	spec/suites/AddLayer.SingleSpec.js:71:15
PhantomJS 2.1.1 (Mac OS X 0.0.0) addLayer adding a single marker "after each" hook FAILED
	undefined is not an object (evaluating 'el.classList')
	hasClass@node_modules/leaflet/dist/leaflet-src.js:2630:8
	onRemove@src/index.js:638:25
	removeLayer@node_modules/leaflet/dist/leaflet-src.js:6562:18
	spec/suites/AddLayer.SingleSpec.js:31:19
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 7 of 174 (2 FAILED) (0.053 secs / NaN secs)
```

@danzel AddLayer.SingleSpec.js doesn't look like its using `sinon.useFakeTimers()` so maybe its something else?

**Comment by danzel** [comment]
This works when running under phantom now, still some errors when running under the browser tester in chrome.

**Comment by rnbwspctrm** [comment]
I am also attempting to use Leaflet 1.3.1 and am getting the following error:
`L.markerClusterGroup is not a function`

It sounds like others are able to use this without errors. As no one responded to the comment above by @azrin1972, I am confused by what I should do to fix this. I am using the example given in the README.

**Comment by HarelM** [comment]
@danzel Any chance to publish a version to npm with this fix?

**Comment by raulhuelamo** [comment]
Or maybe just a 1.3.1-RC release in the repo, so we can npm install from the github repository? As the JS dist files are not delivered in master branch, it would be very useful

**Comment by danzel** [comment]
Ah sorry forgot about this.
Will look to publish a new version in the next week when I have some time.

**Comment by danzel** [comment]
Finally 1.4.0 is released
