### ISSUE TITLE
1.3 minified version missing

### ISSUE THREAD

**Issue by fabysdev** [Leaflet/Leaflet.markercluster#864]
Hi! It seems the 1.3 version is missing the minified version "leaflet.markercluster.js"  
https://github.com/Leaflet/Leaflet.markercluster/tree/v1.3.0/dist

**Comment by ghybs** [comment]
Hi,

Just in case you need it right now, it is available on npm and unpkg CDN:
https://unpkg.com/leaflet.markercluster@1.3.0/dist/
https://unpkg.com/leaflet.markercluster@1.3.0/dist/leaflet.markercluster.js

**Comment by danzel** [comment]
Thanks, must have messed something up in the build process, will fix shortly

**Comment by danzel** [comment]
Fixed

**Comment by talimarcus** [comment]
@danzel this was fixed as of yesterday, but it looks like the change was reverted. I no longer see "leaflet.markercluster.js" in the dist/ folder, though it was definitely there just yesterday. Any idea what's going on?

**Comment by danzel** [comment]
It is only there in tags
https://github.com/Leaflet/Leaflet.markercluster/tree/v1.3.0/dist

**Comment by joshsylvester** [comment]
@danzel would it be possible to re-open this issue, and re-publish leaflet with the contents of https://github.com/Leaflet/Leaflet.markercluster/tree/v1.3.0/dist which should have been in the release anyways? It appears that the release of v1.3.0 did not get all the files that it should have (as per the tag), which is causing a bower.install of `leaflet.markercluster` to not install the proper files in the `dist/` folder.  If you look at the dist file included in the github release, the files are there - they are just not coming through during an install.

note, i am working on the same issue as @talimarcus and merely requesting that it be resolved properly.
