### ISSUE TITLE
Single Marker and Marker Cluster overlap

### ISSUE THREAD

**Issue by ionm** [Leaflet/Leaflet.markercluster#865]
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

I have just started playing around with Leaflet and Leaflet.markercluster. Trying the most basic example, I have noticed that both the Single Markers and the Marker Clusters show up at the same time, instead of only having one or the other. In this case, only clicking on the cluster and spiderfy-ing it makes the Single Markers disappear, and everything behave as expected. 

Do you have any suggestions for how to fix this? 

    <!DOCTYPE html>
    <html>
    <head>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js" integrity="sha512-WXoSHqw/t26DszhdMhOXOkI7qCiv5QWXhH9R7CgvgZMHz1ImlkVQ3uNsiQKu5wwbbxtPzFXd1hK4tzno2VqhpA==" crossorigin=""></script>
    

    <link rel="stylesheet" href="https://leaflet.github.io/Leaflet.markercluster/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://leaflet.github.io/Leaflet.markercluster/dist/MarkerCluster.Default.css" />
    <script src="https://leaflet.github.io/Leaflet.markercluster/dist/leaflet.markercluster-src.js" ></script>

    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        #map {
            width: 1000px;
            height: 600px;
        }
    </style>
    </head>
    <body>

    <div id='map'></div>

    <script>

     var tiles = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				maxZoom: 18,
				attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Points &copy 2012 LINZ'
			}),
			latlng = L.latLng(-37.82, 175.24);

    var map = L.map('map', {center: latlng, zoom: 13, layers: [tiles]});
    
    var markers = L.markerClusterGroup({maxClusterRadius:200});
    markers.addLayer(L.marker([-37.82, 175.24]).addTo(map));
    markers.addLayer(L.marker([-37.8201, 175.2405]).addTo(map));
    markers.addLayer(L.marker([-37.80, 175.20]).addTo(map));
  
    map.addLayer(markers);

    </script>
    </body>
    </html>

**Comment by ghybs** [comment]
Hi @ionm,

Simply do not add the individual markers to the map by yourself and let MCG handle them.

```javascript
// Not:
markers.addLayer(L.marker([-37.82, 175.24]).addTo(map));

// Instead:
markers.addLayer(L.marker([-37.82, 175.24]));
```

Live demo: https://plnkr.co/edit/8kWahhaERKaYMXgduqHL?p=preview

**Comment by ionm** [comment]
That's great, thank you!
