### ISSUE TITLE
How can I display the popup bound to a marker that is not being shown?

### ISSUE THREAD

**Issue by carlos-mg89** [Leaflet/Leaflet.markercluster#867]
I'm struggling with finding a way of showing the popup of my clustered markers when they aren't shown (the cluster is being shown).

I have gathered the markers in an array, and I can definitely access them. If the marker is being shown, and I fire the .openPopup() function, it gets displayed.

Along with that, it will be awesome if the zoom would get to an appropriate level where the marker would be shown. Like when I click over one of the grouped markers icon.

Thanks in advance!

**Comment by ghybs** [comment]
https://github.com/Leaflet/Leaflet.markercluster/issues/660

**Comment by carlos-mg89** [comment]
Thank you @ghybs , it really worked perfectly! I tried to look, but definitely not enough, since the title of the closed issue was quite self explicative.
