### ISSUE TITLE
when the icon exceeds 100 px, markers still collide

### ISSUE THREAD

**Issue by vvavepacket** [Leaflet/Leaflet.markercluster#870]
## How to reproduce

- Leaflet version I'm using: 1.1.1
- Leaflet.MarkerCluster version I'm using: 1.3.0
- Browser (with version) I'm using: Chrome

- step 1
Create a divicon object

```
var icon1 = L.divIcon({
                        className: 'my-div-icon',
                        html: '<img class="my-div-image" height="150" width="150" src="'+data[i].img+'"/>'+
                              '<div style="color:black;font-weight:bold;width: 500px;">'+data[i].name+'</div>'+
                              '<div style="color:black;font-weight:bold;width: 500px;">Eat-all-you-can-buffet @ P299</div>'
                    })
```

- step 2
Create the marker object
```
var icon1 = L.divIcon({
                        className: 'my-div-icon',
                        html: '<img class="my-div-image" height="150" width="150" src="'+data[i].img+'"/>'+
                              '<div style="color:black;font-weight:bold;width: 500px;">'+data[i].name+'</div>'+
                              '<div style="color:black;font-weight:bold;width: 500px;">Eat-all-you-can-buffet @ P299</div>'
                    })
```

- step 2
add the markerclustergroup to map
` markerClusterGroup.addLayer(label2);`

## What behaviour I'm expecting and which behaviour I'm seeing

There should be no collision. Here, we set the marker icon to have a width of 150 px and height of 150 px. Here we should see that the 2 markers should not show at the same time because they overlap each other.

Not working with 150px by 150px

![image](https://user-images.githubusercontent.com/8295642/35731366-4b420eb2-07e3-11e8-8305-3c98749961b0.png)
![image](https://user-images.githubusercontent.com/8295642/35731376-57806106-07e3-11e8-8101-5ceead83be6a.png)
![image](https://user-images.githubusercontent.com/8295642/35731410-69998c0a-07e3-11e8-8248-294f0d7de0c7.png)

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster#all-options
You need to use some of these
