### ISSUE TITLE
Marker position problem

### ISSUE THREAD

**Issue by assaad** [Leaflet/Leaflet.markercluster#872]
![capture d ecran 2018-02-13 a 10 34 56](https://user-images.githubusercontent.com/2571295/36142865-99c8d204-10a9-11e8-8322-cff6c47d94cb.png)

Hello i think i have a problem with the marker icon position. The top left corner is aligned with the GPS i provided, where i prefer the bottom right corner, or the center to be aligned with the position i provided. 
Any idea on how to change the anchor of the marker icon? 
Many thanks!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by assaad** [comment]
I am not sure if it's a bug, and i couldn't find the configuration to control the marker anchoring. Many thanks!
