### ISSUE TITLE
Plugins expects global "L"

### ISSUE THREAD

**Issue by pke** [Leaflet/Leaflet.markercluster#876]
It seems this plugin makes the assumption that `L` is still exported globally.
However using leaflet the ES6 way with direct imports like 
`import { map } from "leaflet/src/map/Map"`

does not expose a `L` global anymore. So trying to include this plugins `MarkerClusterGroup` fails cause of this definition.

`export var MarkerClusterGroup = L.MarkerClusterGroup = L.FeatureGroup.extend({`

The correct way would be to write this like this:

```es6
import { FeatureGroup } from "leaflet/src/layer/FeatureGroup"
export var MarkerClusterGroup = FeatureGroup.extend({
```

**Comment by pke** [comment]
Double post

**Comment by gabssnake** [comment]
The other one: https://github.com/Leaflet/Leaflet.markercluster/issues/874
