### ISSUE TITLE
MarkerCluster custom css add/remove dynamically doesn't update dom.

### ISSUE THREAD

**Issue by kprasad99** [Leaflet/Leaflet.markercluster#877]
My usecase is that, one of the marker needs attention, since its inside marker cluster, users need to spiderify each clusters to find out marker in question. In order to hightlight the marker cluster, I planned to add flicker css on cluster. However marker is not flickering. On further debug using inspect element, I found that css is not getting added to the dom. Below is the code snippet for adding css.  

``` js
 function flickerMarker(m: Marker){
     const mIcon = m.options.icon;
     mIcon.options.className = 'animate-flicker';
     mIcon.setIcon(mIcon);
}
```
The same above code works for markers directly. But does not work for marker cluster.

## How to reproduce
- Leaflet version I'm using: 1.3.1
- Leaflet.MarkerCluster version I'm using: 1.3.0
- Browser (with version) I'm using: Chrome(65.0.3325.51)
- OS/Platform (with version) I'm using:  Windows.

**Comment by danzel** [comment]
MarkerCluster's are special in that they are an icon object (with all sorts of nasty hacks).

https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.js
Search for icon.

You might need to call `_updateIcon` on them maybe?

**Comment by kprasad99** [comment]
Tried calling _updateIcon with no effect.

**Comment by danzel** [comment]
You'll probably need to do more than just that.
Go check out this chunk of code, icons on markerclusters are a big hack.
Maybe use a custom iconCreateFunction too.
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.js#L82-L96

Closing this as not supported.
