### ISSUE TITLE
How to create a grid of clusters?

### ISSUE THREAD

**Issue by AndreyFatyanov** [Leaflet/Leaflet.markercluster#881]
Hi! I try to find a way to make a grid of the clusters. Like this:
![](https://cloud.githubusercontent.com/assets/167831/26082455/eeaccbba-3984-11e7-9529-7895f43507b3.gif)

Is it possible with Leaflet.markercluster? What should i use for it?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by AndreyFatyanov** [comment]
Ok! Thx! Will go stackoverflow
