### ISSUE TITLE
yarn install warning "has unmet peer dependency"

### ISSUE THREAD

**Issue by mits87** [Leaflet/Leaflet.markercluster#882]
Hi, 

I installed your library to my project and always when I'm using yarn (yarn add, yarn upgrade etc.) I got the warning: 

> warning "vue2-leaflet-markercluster > leaflet.markercluster@1.3.0" has unmet peer dependency "leaflet@~1.0.3".

Have you got any solution of this?
Thx.

**Comment by danzel** [comment]
#863
