### ISSUE TITLE
npm warning when using 1.3.0

### ISSUE THREAD

**Issue by HarelM** [Leaflet/Leaflet.markercluster#883]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce
- Leaflet version I'm using: 1.3.0
- Leaflet.MarkerCluster version I'm using: 1.3.0
- OS/Platform (with version) I'm using: Windows 10
`npm install` with `package.json` that contains `leaflet = "1.3.0"` and `leaflet.markercluster "1.3.0"`
results in:
`npm WARN leaflet.markercluster@1.3.0 requires a peer of leaflet@~1.0.3 but none was installed.`
example package.json can be found here: https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/package.json

## What behaviour I'm expecting and which behaviour I'm seeing
No warning.

**Comment by danzel** [comment]
#863
