### ISSUE TITLE
LatLng popup and marker pop up issue

### ISSUE THREAD

**Issue by ohhdanielson** [Leaflet/Leaflet.markercluster#885]
Hi all, 

First off, sorry if this post isn't the best, I am quite new to not only GitHub, but also to coding in general... so please bear with me. 

I am working on a little project which shows a number of point features within my local borough. I previously just had a simple Leaflet map with the code:

var popup = L.popup();

function onMapClick(e) {
    popup
        .setLatLng(e.latlng)
        .setContent("You clicked the map at " + e.latlng.toString())
        .openOn(map);
}
map.on('click', onMapClick);

To show the latitude and longitude at that point. I then connected to a database (using php), stored the results into an array and plotted them onto the map and had a popup showing the location of a point.  All that worked great, but I was really keen to use clustering on these points, so I used the markercluster to do this. Here is the code for that section:

	
dog_bins = new Array();
	
$.getJSON("fetchData.php", function(results)	{ 
		
for (var i = 0; i < results.length; i++ )	{
			
dog_bins.push ({
unqid: results[i].unqidid, 
location: results[i].location, 
latitude: results[i].latitude, 
longitude: results[i].longitude
}); 
}
		
plotbins();
});
}
	
function plotbins() {
 
var markers = L.markerClusterGroup();
   
for (var i = 0; i < dog_bins.length; i++) {
var markerLocation =
new L.LatLng(dog_bins[i].latitude, dog_bins[i].longitude);
var marker = new L.Marker (markerLocation, {icon:dogbinicon});
markers.addLayer(marker);
	  
map.addLayer(markers);
markers.bindPopup(dog_bins[i].location);	  	  
}
} 

This is when the problem with the LatLng popup and marker popup info started. It seems like using markcluster almost overwrites the other two functions? 
If I use map.addLayer(marker) then it adds each point individually as before, and clicking on the map gives LatLng pop up and clicking a point give me the location details, but as soon as I change the code to map.addLayer(markers), so it uses the clustering, the LatLng pop up and location info stops working... but I get my clusters. 

So I think this is an issue with the marker clustering and not so much my code? Unless perhaps the ordering of my code need amending (I know my code could be tidier, but it works)?

I have tried to search for similar issues, but don't think I can quite find this problem, and some which sound similar I have looked at but I can't work out how to adjust my code and get it working. 

Thanks again
Dan

**Comment by danzel** [comment]
We don't provide help for apps here sorry.
At a guess, you are calling `map.addLayer(markers)` multiple times, not sure if that would cause issues.
