### ISSUE TITLE
Empty popup on clustergroup icon with mouseover

### ISSUE THREAD

**Issue by wuk986** [Leaflet/Leaflet.markercluster#888]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.3.1
- Leaflet.MarkerCluster version I'm using: 1.3.0
- Browser (with version) I'm using: Firefox 59.0.2, Chrome 65
- OS/Platform (with version) I'm using: Windows 10 Pro
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing

I have noticed that, when I open a popup on a clustergroup with the `clustermouseover` the popup is sometimes empty.

See the screenshots:
[popup with content](https://imgur.com/XgTeQ42)
[popup without content](https://imgur.com/clfk8Mr)

I figured out, that this is happen the most time, when I enter the cluster icon from the top.
`showCoverageOnHover: true,` and it is not necessary if `showCoverageOnHover: false,`

the code for opening the popup looks like this:

  vehicleClusterMarkers.on('clustermouseover', function(a) {
				
	var vehicleClusterPopup = "";

	$.each(a.layer.getAllChildMarkers(), function(index, value) {
	vehicleClusterPopup += value._popup._content;
	//console.log(vehicleClusterPopup);
	});`

	var clusterPopup = L.popup({closeButton: false})
			.setLatLng(a.layer.getLatLng())
			.setContent('<div id="vehicleClusterPopupContent" class="vehiclePopup"></div>')
			.openOn(map);

    $('#vehicleClusterPopupContent').html(vehicleClusterPopup).mouseleave(function() { map.closePopup(); });
				  
      }).on('clustermouseout', function(a){
          // map.closePopup();
      }).on('clusterclick', function(a){
	 map.closePopup();
      });

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by danzel** [comment]
can you make a standalone reproduction?

**Comment by wuk986** [comment]
a standalone is a little bit difficult because the data of the popup came from external and are not for public viewing.

but I figuered out, that the empty popup is the result of the `$.each` loop.
the first time I enter the cluster with the mouse the popup content is shown correctly and after I move out and reenter the cluster the popup content show up for a second an then the popup is emtpy.

when I close the popup by clicking on the map and then enter the cluster the content is shown correctly.

**Comment by wuk986** [comment]
I have done some tests an I figured out, that the `$.each` is not the reason.

I think there is a time problem created by my own, but now I have an solution, that worked for me:

    var timeoutId = null;

    vehicleClusterMarkers.on('clustermouseover', function(a) {

        var vehicleClusterPopup = "";

        var clusterPopup = L.popup({closeButton: false})
                                .setLatLng(a.layer.getLatLng())
                                .setContent('<div id="vehicleClusterPopupContent" class="vehicle-popup"></div>')

        $.each(a.layer.getAllChildMarkers(), function(index, value) {
        vehicleClusterPopup += value._popup._content;
        });

        timeoutId = window.setTimeout(function() {

            clusterPopup.openOn(map);

            setTimeout(function() {
                $('#vehicleClusterPopupContent').html(vehicleClusterPopup).mouseleave(function() {map.closePopup();});
            }, 200); // this timeout is necessary to inject the `vehicleClusterPopup` otherwise the popup is empty

        }, 500);
    }).on('clustermouseout', function(a){
        //map.closePopup();
        window.clearTimeout(timeoutId)
        }).on('clusterclick', function(a){
            map.closePopup();
        });

thanks for you support!
