### ISSUE TITLE
Display cluster count based on marker property

### ISSUE THREAD

**Issue by daas-ankur-shukla** [Leaflet/Leaflet.markercluster#889]
- [ ] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

- Leaflet version I'm using: 1.3.1
- Leaflet.MarkerCluster version I'm using: 1.3.0
- Browser (with version) I'm using: Chrome Version 65.0.3325.181
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting
In my application I have added some options to the markers. One of them being enabled. I want to update this option based on some filters in order to display some markers as enabled and some as disabled. 
**Is there a way to update the cluster count based on the number of markers which are enabled?**

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers

**Comment by daas-ankur-shukla** [comment]
thanks a ton for your comment @danzel. i had missed that point in the repository readme. thanks

**Comment by daas-ankur-shukla** [comment]
how can i pass a custom count while maintaining the default css style?

**Comment by danzel** [comment]
Look in the code for the default icon method and copy it and modify it
