### ISSUE TITLE
The name of clustering algorithme used  for markercluster

### ISSUE THREAD

**Issue by HADDADENICAR** [Leaflet/Leaflet.markercluster#896]
I'm doing researches for my final year project . I use folium with markerCluster for clustering inside the map, I need to  know ,if it's possible, the name of the algorithme you used to create  that markerCluster, thanks
--

**Comment by ghybs** [comment]
Hi,

If you have visual impairment, please increase the font size _at your browser level_ (Ctrl + "+"), but keep the rest as default for other people to see.

Mind the [etiquette](https://en.wikipedia.org/wiki/Etiquette_in_technology#Netiquette):

> […] avoid typing in all caps or grossly enlarging script for emphasis, which is considered to be the equivalent of shouting or yelling.

About your request, have a (re)search in this repo issues, it should be there already.

**Comment by danzel** [comment]
It uses a greedy clustering algorithm.
Check the code in MarkerClusterGroup `_add{something}` iirc.
