### ISSUE TITLE
 The leaflet.MarkerCluster will not work when I add the maxZoom attribute to the Map object.

### ISSUE THREAD

**Issue by gee1k** [Leaflet/Leaflet.markercluster#897]
- [X] I'm reporting a bug, not asking for help
- [X] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: `1.0.3`
- Leaflet.MarkerCluster version I'm using: `1.3.0`
- Browser (with version) I'm using: `Chrome v65.0.3325.181`
- OS/Platform (with version) I'm using: `Windows 10`

## What behaviour I'm expecting and which behaviour I'm seeing

In using the example you provided. The leaflet.MarkerCluster will not work when I add the maxZoom attribute to the Map object. There will only be one cluster point, and the scaling map will not expand.

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

demo: [https://plnkr.co/edit/vRA47A3071W1QBqR5Oa1?p=preview](https://plnkr.co/edit/vRA47A3071W1QBqR5Oa1?p=preview)

**Comment by danzel** [comment]
You have this set:
`disableClusteringAtZoom: 17`

**Comment by gee1k** [comment]
see: [https://plnkr.co/edit/vRA47A3071W1QBqR5Oa1?p=preview](https://plnkr.co/edit/vRA47A3071W1QBqR5Oa1?p=preview)

**Comment by gee1k** [comment]
see: [https://jsfiddle.net/gee1k/t1bokLa8/](https://jsfiddle.net/gee1k/t1bokLa8/)
