### ISSUE TITLE
the problem when click on map after spiderify its again go to unspiderify mode

### ISSUE THREAD

**Issue by HMKola** [Leaflet/Leaflet.markercluster#898]
1. Check in your example if we click on clustering icon its come in non clustering mode. 
2. but if we click on map only it will again come to clustering icon. (its should be base on zoom functionality not on map click event) let me know what fix you suggest for this.

**Comment by danzel** [comment]
Sorry I don't understand your question here.
Please link to an example and provide exact steps to reproduce.
