### ISSUE TITLE
Dragging a marker from a spiderfied cluster gives problems with spiderfying other clusters during drag

### ISSUE THREAD

**Issue by DerGuteWolf** [Leaflet/Leaflet.markercluster#907]
- [X] I'm reporting a bug, not asking for help
- [X] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported
But similar to #808
----

## How to reproduce

- Leaflet version I'm using: 1.3.3
- Leaflet.MarkerCluster version I'm using: 1.3.0
- Browser (with version) I'm using: Chrome 67.0.3396.99, Edge 42.17134.1.0, Firefox ESR 52.9.0
- OS/Platform (with version) I'm using: Win10
Start dragging a marker and drag over several clusters, clusters are spiderfied and unspiderfied properly. Works fine unless you start with a marker from a spiderfied cluster, then the dragged marker vanished when dragged over the first cluster, drag has visually ended but dragend event was not fired.
Original aim is to support drag&drop of markers of one type onto markers of annother type, while markers are displayed clustered, esp. there could be several markers at exactly the same location, so you might have to start with a spiderfied cluster, zooming in would not help (in order to make the example fiddle simplier, I have set maxZoom, however problems also appears without maxZoom).

## What behaviour I'm expecting and which behaviour I'm seeing
Marker should continue to be draggable, dragged marker should not get clustered.
IMHO we need a mechanism to exclude a dragged marker from clustering, this would also solve #808 . Howewer I can't call mcg.removeLayer(this)/map.addLayer(this) on dragstart because this stops the drag immediatly.

## Minimal example reproducing the issue
See fiddle https://jsfiddle.net/thy3c540/
- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

**Comment by danzel** [comment]
Yeah this won't work, when you spiderfy the hovered cluster that causes the one that you dragged the marker from to unspiderfy, so we move the dragged marker back in.
Happy for a PR to support a flag on markers to have them in the layer but cluster them, if it's not too ugly in the codebase.

**Comment by DerGuteWolf** [comment]
IMHO a simple addition of
```
if (this._markers[j].__dragStart)
  continue;
```
at the second loop in getAllChildMarkers shoud be enough if also the _moveChild call in _childMarkerDragEnd is done after the delete statement.

What do you think?

**Comment by danzel** [comment]
If you change the behaviour of `getAllChildMarkers`, that'll change our `eachLayer` behaviour:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L469
and getLayers and other methods that rely on eachLayer.
Sorry, gonna be harder than that I think.

**Comment by DerGuteWolf** [comment]
ok, perhaps adding another parameter to getAllChildMarkers named "ignoreDraggedMarker" and
```
if (ignoreDraggedMarker && this._markers[j].__dragStart)
  continue;
```
and setting this parameter only for the calls in the relevant spiderfying methods?

**Comment by danzel** [comment]
Yeah that might work

**Comment by DerGuteWolf** [comment]
ok, I tried these changes in (forked & branched)  https://github.com/DerGuteWolf/Leaflet.markercluster/tree/DragFix , tests run fine, I updated the fiddle to https://jsfiddle.net/thy3c540/1/ to use this, which seems to work now.
Should I create a pull request?

**Comment by danzel** [comment]
Make a PR so I can take proper look thanks.

**Comment by DerGuteWolf** [comment]
And what do you think? Will you use the PR?

**Comment by twadzins** [comment]
Our team is eagerly waiting for this drag fix too.
