### ISSUE TITLE
spiderfied event not firing

### ISSUE THREAD

**Issue by topgun743** [Leaflet/Leaflet.markercluster#908]
I am using following code to create a markerClusterGroup and then trying to bind to its spiderfied event,

    let markerClusterGroup = L.markerClusterGroup({
                            showCoverageOnHover: false,
                            chunkedLoading: true,
                            zoomToBoundsOnClick: true,
                            iconCreateFunction: (cluster) => {
                                return L.divIcon({
                                    html: '<span style="background-color:yellow">' +
                                        cluster.getChildCount() + '<span>',
                                    className: 'cluster-icon',
                                    iconSize: L.point(120, 120)
                                });
                            }
                        });

                        markerClusterGroup.on('clusterspiderfied', (cluster, cMarkers) => {
                            console.log('spiderfied'); //This statement not executing
	                        console.log('Cluster markers', cMarkers); //This statement not executing
                        });

The event 'clusterspiderfied' is not firing at all. 
So I wanted to ask if anything I am missing or doing wrong. Please help.
Thanks.

- Leaflet version I'm using: 1.2.0
- Leaflet.MarkerCluster version I'm using: 1.3.0
- Browser (with version) I'm using: Firefox 61.0
- OS/Platform (with version) I'm using: Windows 10

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet.markercluster#additional-markerclustergroup-events
that isn't the event name
