### ISSUE TITLE
This plugin can not use in mapbox-gl which will render map to canvas

### ISSUE THREAD

**Issue by q869939686** [Leaflet/Leaflet.markercluster#910]
This plugin can not use in mapbox-gl which will render map to canvas

As well I can not find L.mapbox in the class 'Leaflet'
![image](https://user-images.githubusercontent.com/29123332/44341803-988cbd00-a4bb-11e8-9959-d017c4ae5606.png)

![image](https://user-images.githubusercontent.com/29123332/44341783-8579ed00-a4bb-11e8-98e3-312c9016b355.png)

**Comment by IvanSanchez** [comment]
Leaflet is not MapboxGL. Plugins for Leaflet will not work on MapbogGL, and viceversa.

There's nothing that can be done about this (short of rewriting everything).
