### ISSUE TITLE
Markers inside a MarkerClusterGroup are fully re-rendered on the actual DOM when host Map re-renders

### ISSUE THREAD

**Issue by cherouvim** [Leaflet/Leaflet.markercluster#911]
Deps used:
```
    "leaflet": "1.3.4",
    "leaflet.markercluster": "1.3.0",
    "react": "16.4.2",
    "react-dom": "16.4.2",
    "react-leaflet": "1.9.1",
    "react-leaflet-markercluster": "1.1.8",
```

Reproduce:
- code: https://codesandbox.io/s/1j1wo6pv3
- demo: https://1j1wo6pv3.codesandbox.io/
- details: Open up the demo and see the 4 cat markers. The upper 2 are orphan, directly hosted on the `Map`, and the lower 2 are wrapped inside a `MarkerClusterGroup`. I've setup a timer which will force an `App` re-render every 3 seconds by updating the `App` state. Open up dev tools and inspect the cat markers. You'll notice that the upper 2 cat markers are not touched/altered when the `App` render takes place, but the lower 2, which are wrapped in the `MarkerClusterGroup`, always get fully re-rendered.

Nothing has changed on the `MarkerClusterGroup` and the `Marker`s within, so this behavior is problematic in many ways.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
