### ISSUE TITLE
Cluster Algorithm

### ISSUE THREAD

**Issue by MarcoMandujano** [Leaflet/Leaflet.markercluster#913]
### Hi.
First of all I want to tell you that the plugin is amazing. I only have one question, What is the exact algorithm you used? or, What is the exact technique you used?
I have already reviewed the different answers to similar questions and I have seen that you say that you used "greedy clustering algorithm", but I understand that there are different algorithms that use the greedy technique.

It would be very helpful if you could provide me with an article or site where they explain or talk about the process you used to generate the clusters.

Thanks.

**Comment by danzel** [comment]
You'll have to read the code, it's not from a website.
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L956

**Comment by HADDADENICAR** [comment]
@MarcoMandujano take a look at [this article](https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97)
