### ISSUE TITLE
Disable spiderfy method after zoomToShowLayer

### ISSUE THREAD

**Issue by nik-el** [Leaflet/Leaflet.markercluster#916]
Hello! I have a lot of markers in same coordinates (> 1000) and I need to search for markers from input. I use `zoomToShowLayer` method, but then the page freezes for a long time to display `spiderfy`. 
I tried this code to turn off `spiderfy`:

```
markers.zoomToShowLayer(target,() => {
  target.__parent.unspiderfy();
})
```
But for a while anyway the plugin tries to `spiderfy`.
How can i full disable `spiderfy`?

thanks!

**Comment by danzel** [comment]
Copy/paste the zoomToShowLayer code out to your app and modify it to not spiderfy.
Or submit a PR to allow it to not spiderfy at the end. :+1:
