### ISSUE TITLE
Handling topojson point layer loaded via omnivore

### ISSUE THREAD

**Issue by dshakya** [Leaflet/Leaflet.markercluster#918]
- [ ] I'm reporting a bug, not asking for help
- [ ] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using:1.3.0
- Leaflet.MarkerCluster version I'm using:1.4.1
- Browser (with version) I'm using: Chrome 69)
- OS/Platform (with version) I'm using: Window 7 and WordPress 4.8
- step 1: Enqued scripts and css files to be loaded on page load
- step 2: Created a layer for Topojson Point file using Omnivore
- step 3: Added the layer to Cluster group and added to map

```
var mySitesLayer = L.geoJson(null, {

    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, SitesMarkerOptions);
    },
});
var siteUrl = '/wp-content/uploads/Maps/Data/sites.topo.json';
var sur_layer = omnivore.topojson(siteUrl, null, mySitesLayer);

var markers = L.markerClusterGroup();
markers.addLayer(sur_layer);
mymap.addLayer(markers);
```

## What behaviour I'm expecting and which behaviour I'm seeing
The point are loaded and clustered

The clustered layer is not loaded. I can load the layer using the Leaflet addlayer and it shows up but cannot be clustered.

**The clustering works with FeatureCollection type but not with Topology Type.**

Any help will be appreciated.

**Comment by ghybs** [comment]
Hi,

[leaflet-omnivore](https://github.com/mapbox/leaflet-omnivore) plugin loads your data asynchronously.
See https://stackoverflow.com/questions/35897147/clustering-markers-from-csv-with-leaflet-and-omnivore/35898047#35898047

**Comment by dshakya** [comment]
Hi @ghybs,
Thanks for the response. It now works beautifully. Cheers!
