### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mickeyjohn** [Leaflet/Leaflet.markercluster#919]
- [x] I've searched through the issues to make sure it's not yet reported
----
## How to reproduce
- Download the source package from master branch
- Install jake npm install -g jake then run npm install

## What behaviour I'm expecting and which behaviour I'm seeing
npm install --trace then failed with errors:
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> ..
> > leaflet.markercluster@1.4.1 prepublish 
> > jake
> 
>         Check passed.
> 
> jake aborted.
> ode_modules/uglify-js/bin/uglifyjs:175:30)
>     at Module._compile (module.js:652:30)
> (See full trace by running task with --trace)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! leaflet.markercluster@1.4.1 prepublish: `jake`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the leaflet.markercluster@1.4.1 prepublish script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Please any one help. Thanks a lot.

**Comment by ghybs** [comment]
Hi,

wow looks like a hidden bug in the build process…

It seems that jake executes the `build` and `uglify` tasks, but at least the former is asynchronous, so the latter starts while there may still be no file ready to minify.
After a few tests, this behaviour seems consistent: the minification is always applied on the **previous** version of the built (src) file!

So when there is no built source file yet, it fails, as shown in your log.
But after that, it works, but you may end up with a minified file that does not correspond to the new src file!

Most probably the publisher already built explicitly the src file before publishing, then published without modification.
At that point, npm runs the `prepublish` scripts, which re-minifies the src file.
Therefore it is highly probable that the published files on npm do not suffer discrepancy between the src and the minified files.

For archive, npm [automatically runs](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare) the `prepublish` script as well right after the `install`, hence why you get the top warnings, then the error.

**Comment by ghybs** [comment]
Note: therefore simply running the task again should work before it is fixed, since you will have the built src file now.

Make sure to run it twice after each modification, to ensure the minification is applied on the newly built src file.

BTW also make sure to use the local jake version (`npm run prepublish`, or `npx jake` if you have npm >= 5.2.0)
