### ISSUE TITLE
too much recursion when trying to fit bounds

### ISSUE THREAD

**Issue by youradds** [Leaflet/Leaflet.markercluster#924]
Hi,

I'm using "Leaflet v1.3.4" and "leaflet.markercluste v1.4.1"

I'm trying to work out why I get this error:

too much recursion[Learn More] leaflet.js:5:1

The code is at its simplest:

        window.VARS.markerCluster = L.markerClusterGroup();

        data.markers.forEach(function(item, i){

                window.VARS.markerCluster.addLayer(
                        L.marker([item.latitude, item.longitude])
                        .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
                        .on("click", function(marker) {
                            console.dir(marker);
                        })
                );
        });

        // add the clusters to map
        window.VARS.Map_Modal.addLayer(window.VARS.markerCluster);
        
        // fit to map
       // HERE IS WHERE THE ERROR HAPPENS
        window.VARS.Map_Modal.fitBounds(window.VARS.markerCluster.getBounds());

The weird thing is that it DOES pull out to the correct bounds, but I see this error in the console. Am I doing something wrong?

Thanks

Andy

**Comment by danzel** [comment]
Yeah you are doing something wrong, just not sure what 😹 

IIRC you can cause this if your map doesn't have a size set (0,0 size).
Otherwise make a complete minimal jsfiddle to reproduce.

**Comment by youradds** [comment]
Thanks @danzel. Mmm it does seem to work ok in a test case!

https://jsfiddle.net/youradds/3ugk7L9y/26/

If I run the code in FF I get the error about "too much recursion". In Chrome I get a more helpful error:

```
Uncaught RangeError: Maximum call stack size exceeded
    at T.extend (leaflet.js?bust=1539329226068:5)
    at new T (leaflet.js?bust=1539329226068:5)
    at z (leaflet.js?bust=1539329226068:5)
    at T.extend (leaflet.js?bust=1539329226068:5)
    at new T (leaflet.js?bust=1539329226068:5)
    at z (leaflet.js?bust=1539329226068:5)
    at T.extend (leaflet.js?bust=1539329226068:5)
    at new T (leaflet.js?bust=1539329226068:5)
    at z (leaflet.js?bust=1539329226068:5)
    at T.extend (leaflet.js?bust=1539329226068:5)
```


I'm not sure what that means though? (and its weird the EXACT same data and map works in jsfiddle but not on the site). Shoot me an email on andy.newby@gmail.com if you wanna see it in the "real world" on the server. Its a dev server so is behind an IP block (so I can't just put a link up here)

Thanks

Andy

**Comment by danzel** [comment]
Sorry, don’t wanna debug your app. If you can reproduce on jsfiddle though
please let us know.

**Comment by youradds** [comment]
No problem - you don't ask you don't get =) haha. I'll keep playing to see if I can get it to happen in a basic test case . When you said:

`IIRC you can cause this if your map doesn't have a size set (0,0 size).`

Do you have an example of what you mean?

**Comment by youradds** [comment]
Interestingly I think I just stumbled on something. I was trying to work out why the leaflet getBounds() was giving wrong values. It was showing the map location when it was init'd .. ie based on:

       window.VARS.Map_Modal = L.map('google_map_modal_inner', {
                      center: [window.VARS.lat,window.VARS.lng],
                      zoom: 10, // 
                      maxZoom: 20,
                      zoomControl: false
                    });

Setting it to this gets rid of that problem:


       window.VARS.Map_Modal = L.map('google_map_modal_inner', {
                      center: [window.VARS.lat,window.VARS.lng],
                      zoom: 2, // set to a higher zoom level, otherwise it messes up the getBounds later on
                      maxZoom: 20,
                      zoomControl: false
                    });
