### ISSUE TITLE
Show infowindow of top of spiderified marker (and hide the marker)

### ISSUE THREAD

**Issue by chthomos** [Leaflet/Leaflet.markercluster#931]
How can I get the position of a marker after its cluster has been collapsed?

For example, let's say tha there's a cluster with two markers. Clicking the cluster collapses and the two markers are shown as usual. I would like to be able to click on the marker and then show an infowindow. 

How can I get the coordinates to show the infowindow on? 
(Also, how can I hide the marker and re-show it when the infowindow closes?)

Thnx for the help

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
