### ISSUE TITLE
Limit zoom step on cluster click

### ISSUE THREAD

**Issue by warudin** [Leaflet/Leaflet.markercluster#933]
I'm looking for a way to limit the amount of zoom steps that are being skipped, when clicking a cluster. 

Currently, I have a map that starts at zoom-level 8, but when clicking on a cluster the view goes straight to zoom-level 11. In this case that difference is too big and I would like to limit that to only 1 or 2 steps. How can this be achieved?

Currently, this is my solution, but I was wondering if there's a better one.

```
var markers = L.markerClusterGroup({
	zoomToBoundsOnClick: false
});

markers.on('clusterclick', function (e) {
	var currentZoom = map.getZoom();
	var clusterPosition = e.latlng;

	map.setView(clusterPosition, currentZoom + 1);
});
```

**Comment by danzel** [comment]
Sounds fine.
