### ISSUE TITLE
Is it Possible to zoom by one level, instead of zoomToGroupBoundary?

### ISSUE THREAD

**Issue by mikebronner** [Leaflet/Leaflet.markercluster#937]
I have received feedback from some users that the zoom to boundary is disorienting when there are many markers. Is there a way to zoom by a single level, instead of zoom to group boundary?

**Comment by danzel** [comment]
Disabled zoomToBoundsOnClick and replace with your own implementation.

**Comment by mikebronner** [comment]
@danzel Thanks ... can you point me to documentation on how to create my own implementation?

**Comment by danzel** [comment]
Check out the original implementation in the code
