### ISSUE TITLE
Update Leaflet to 1.4.0

### ISSUE THREAD

**Issue by alexedev** [Leaflet/Leaflet.markercluster#938]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.4.0
- Leaflet.MarkerCluster version I'm using: 1.4.1
- Browser (with version) I'm using: does not matter
- OS/Platform (with version) I'm using: macOS Mojave 10.14
- `yarn add leaflet` (installs 1.4.0)
- `yarn add leaflet.markercluster` (expects leaflet 1.3.1)

## What behaviour I'm expecting and which behaviour I'm seeing
Seeing
`warning " > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".`
Expecting peer dep to be of version 1.4.0

**Comment by snjna** [comment]
@alexedev Has this been resolved. I have updated leaflet to 1.6.0 and facing the same issue. Any workarounds? Fixing this is really critical for my application.

**Comment by thetispro** [comment]
Same here with leaflet 1.6 installed

`'leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none is installed. You must install peer dependencies yourself.`

**Comment by tinyfly** [comment]
Last commit of any kind on the master branch was Mar 3, 2019. Considering that, I don't expect to see any updates.

**Comment by ykzeng** [comment]
the above-mentioned problem should be resolved by PR #976 which has been merged for a while
