### ISSUE TITLE
Do you have any idea how to implement Freezable with react-leaflet-markercluster?

### ISSUE THREAD

**Issue by mirzacuric** [Leaflet/Leaflet.markercluster#939]
I want to use https://github.com/ghybs/Leaflet.MarkerCluster.Freezable/releases/download/v1.0.0/leaflet.markercluster.freezable.js sub-plugin in React.
Basically, when I click on cluster show all markers below that one and have 1 zoom level.

Is there anyone who can help me out with this one?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
