### ISSUE TITLE
Enter Key on clusters no longer triggers click with Leaflet version 1.4.

### ISSUE THREAD

**Issue by mikepinto81** [Leaflet/Leaflet.markercluster#947]
- [X ] I'm reporting a bug, not asking for help
- [X ] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.4
- Leaflet.MarkerCluster version I'm using: Latest (as of 4/5/2019)
- Browser (with version) I'm using:firefox, chrome, safari
- OS/Platform (with version) I'm using:windows and iOS
- step 1
Use TAB to highlight cluster. Hit Enter and nothing happens. This works when using leaflet 1.0.3. If I switch the leaflet source to that version it starts working again. But when using Leaflet 1.4 it stops working. The enter key works fine for Markers, just the clusters for some reason stop working with it.
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing
Hitting enter triggers the click event.
## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by danzel** [comment]
#940
