### ISSUE TITLE
MarkerCluster is not showing the no.of markers(features) in cluster accurately and also, some markers (features) ,especially if they are single, are not accounted on map.

### ISSUE THREAD

**Issue by RayGone** [Leaflet/Leaflet.markercluster#949]
I have few thousands of data to show on map. Users can use filters on some attribute. Thus it changes the no.of features on layer. What i've done is delete old layer and add the layer with the filtered data on map every time a user applies a filter.. sometimes, it happens that there is only one feature on layer and clustering simply avoids to show that. Sometimes, when a single feature is so far from others such that clustering can't be done, marker cluster simply avoids those singled features on layer too..

**Comment by RayGone** [comment]
I have few thousands of data to show on map. Users can use filters on some attribute. Thus it changes the no.of features on layer. What i've done is delete old layer and add the layer with the filtered data on map every time a user applies a filter.. sometimes, it happens that there is only one feature on layer and clustering simply avoids to show that. Sometimes, when a single feature is so far from others such that clustering can't be done, marker cluster simply avoids those singled features on layer too..

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by danzel** [comment]
Need reproduction.

**Comment by RayGone** [comment]
@danzel I don't know why you closed this thread. I am sorry I didn't realize that you guys have responded.  I will get to it (code) and I hope you guys will respond to me. @IvanSanchez

**Comment by RayGone** [comment]
https://codepen.io/Raygone/pen/QRQLYE?editors=1000
This is a codepen link that shows the problem i'm facing.

the geojson i used in this example is this: (which you can find in code too, but for clarity)
    var geojsonFeature = {
            "type" : "FeatureCollection",
	          "features" :[
              {
                "type": "Feature",
                "properties": {
                    "name": "Coors Field",
                    "amenity": "Baseball Stadium",
                    "popupContent": "This is where the Rockies play!"
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [-104.99404, 39.75621]
                }
              },
              {
                "type": "Feature",
                "properties": {
                    "name": "Coors Field",
                    "amenity": "Baseball Stadium",
                    "popupContent": "This is where the Rockies play!"
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [105.99404, 39.75621]
                }
              },
              
              {
                "type": "Feature",
                "properties": {
                    "name": "Coors Field",
                    "amenity": "Baseball Stadium",
                    "popupContent": "This is where the Rockies play!"
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [106.99404, 39.75621]
                }
              }
            ]
          };
You can see, the above geojson has 3 features, one in america and two in asia. But somehow cluster only cares to show 2 featuers that in asia because they were near but it doesn't show the one that is in america.

**Comment by ghybs** [comment]
Hi,

Leaflet.markercluster struggles with non integer map min/max zoom options unfortunately.

Setting map minZoom option to an integer value fixes the issue in your CodePen.

**Comment by RayGone** [comment]
> Hi,
> 
> Leaflet.markercluster struggles with non integer map min/max zoom options unfortunately.
> 
> Setting map minZoom option to an integer value fixes the issue in your CodePen.

Thank you very much @ghybs . It worked. I still don't understand how min/max zoom option and number of marker on map by marker cluster are related. Such a simple thing can lead to such a disaster.
