### ISSUE TITLE
ClusterGroup doesn't update correctly

### ISSUE THREAD

**Issue by AmazingBite** [Leaflet/Leaflet.markercluster#950]
Hi,

I'm using the last version of leaflet (1.4.0) and marker cluster (1.4.1).
I want to use the same cluster group with two maps.
For exemple, when my first map is initialized, I have this : 
      (50)
and when I zoom :
(10)     (30) (10)

When I initialize my second map, I want this again, because I'm using the same cluster  :
      (50)
But I have this :
(10)(50)(30) (10)
I have to zoom in and to fit the same zoom and position than the one on my first map to make the cluster work normally again.

Here some parts of my code
The first map
```
map = new L.Map('map', {
	attributionControl: false,
	center: bounds.getCenter(),
	minZoom: 2,
	maxZoom: 20,
	zoom: 2,
	layers: [osm],
	maxBounds: bounds,
	maxBoundsViscosity: 1
});
markers = L.markerClusterGroup({
	maxClusterRadius: 40,
	iconCreateFunction: function (cluster) {
		var childCount = cluster.getChildCount();
		var c = ' marker-cluster-stw';
		return new L.DivIcon({
			html: '<div><span>' + childCount + '</span></div>',
			className: 'marker-cluster' + c,
			iconSize: new L.Point(40, 40)
		});
	},
	spiderfyOnMaxZoom: false,
	showCoverageOnHover: false,
	zoomToBoundsOnClick: true
});
for (...){
	oneMarker = L.marker([latitude, lngitude], {
		icon: iconLabel
	}).on('click', onClick);
	markers.addLayer(oneMarker);
}
map.addLayer(markers);
```
And the second map
```
map2 = new L.Map('map2', {
        attributionControl: false,
        center: bounds.getCenter(),
        minZoom: 2,
        maxZoom: 20,
        layers: [osm],
        maxBoundsViscosity: 1
    });
map_add_marina.addLayer(markers);
markers.refreshClusters();
```

**Comment by IvanSanchez** [comment]
In general, Leaflet doesn't play well when the same layer is added to two (or more) maps at once.

Create two copies of your cluster, and add each of them to each map.
