### ISSUE TITLE
Continuation of #907

### ISSUE THREAD

**Issue by DerGuteWolf** [Leaflet/Leaflet.markercluster#967]
- [X] I'm reporting a bug, not asking for help
- [X] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----
Unfortunatly my fix #909 for #907 was not complete, the recursive call in getAllChildMarkers needs to receive the new ignoreDraggedMarker Parameter.

## How to reproduce

- Leaflet version I'm using: 1.5.1
- Leaflet.MarkerCluster version I'm using: 1.4.1
- Leaflet.MarkerCluster.Freezable version I'm using: 1.0.0
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Windows

## What behaviour I'm expecting and which behaviour I'm seeing

run Fiddle, click on one of the bigger clusters (which will be a "multi-level" cluster thanks to the freeze), drag one marker from this cluster over another cluster:
Expected: Dragged marker still visible at mouse cursor
Seeing: Dragger marker disappears

## Minimal example reproducing the issue
https://jsfiddle.net/7b4xzprd/1/
- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

**Comment by ykzeng** [comment]
@DerGuteWolf thanks for the issue and fix. but could u help me reproduce this issue? I tried in fiddle [https://jsfiddle.net/7b4xzprd/1/](https://jsfiddle.net/7b4xzprd/1/) and the dragger marker did disappear, but when I try on local as well as on [https://jsfiddle.net/7b4xzprd/show](https://jsfiddle.net/7b4xzprd/show) it seems the dragger marker is working as expected.

**Comment by DerGuteWolf** [comment]
Hi @ykzeng ,

thanks for caring for the repo and merging my fix.

In your fiddle your are not freezing the cluster situation with
```javascript
mcg.freezeAtZoom(11);
```
(this uses https://github.com/ghybs/Leaflet.MarkerCluster.Freezable).

The problem arises when the clusters are frozen and there is a cluster which when unfreezed and clicked on would result in clusters and not individual markers (ie a "multi-level" cluster).

Regards,
  Wolfgang

**Comment by ykzeng** [comment]
@DerGuteWolf hi Wolfgang, thanks for the comment. I was just able to reproduce the issue with freezing function and the fix works good. I will catch up on some other fixes and PRs and expect to have a new version soon with this fix.

And thanks for your nice words, I appreciate your contributions to the repo and look forward to working on your future PRs :)

Regards,
Vincent
