### ISSUE TITLE
Laeflet.markercluster@latest not compatible with leaflet@latest, react@latest

### ISSUE THREAD

**Issue by snjna** [Leaflet/Leaflet.markercluster#975]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet : 1.6.0
- Leaflet.MarkerCluster version I'm using: 1.4.1
- Browser (with version) I'm using: all
- OS/Platform (with version) I'm using: MacOS

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

React-leaflet 2.6.0 has the following dependencies:

 "leaflet": "^1.6.0", [Latest version]
 "react": "^16.8.0", [Latest version]
 "react-dom": "^16.8.0" [Latest version]

However, leaflet.markercluster@latest (1.4.1) has peer dependency of "leaflet": "~1.3.1". [older version]  The peer dependency should be '^1.3.1' so that it works with leaflet 1.6.0

**Comment by Falkyouall** [comment]
Hi, i don't understand why this tiny bit of information is not getting updated to newer leaflet versions. It breaks my Pipelines if i don't install my dependencies with force.
