### ISSUE TITLE
Looking for maintainer(s)

### ISSUE THREAD

**Issue by danzel** [Leaflet/Leaflet.markercluster#979]
Hi All.
As you've probably noticed, I don't care about this project any more, but people still use it, so it should probably be maintained!

I'm looking for someone(s) to pick up and carry it on, otherwise it'll just be dead.
CC @ghybs @mourner @IvanSanchez 
You are all suitable and/or I'm sure you can figure out who would be.
I think mourner can probably add you to the repository if needed, or ding me and I can do it.

Thanks and good luck :)

**Comment by snjna** [comment]
Hi @danzel , I would like to volunteer. Is there any selection criteria?

**Comment by danzel** [comment]
Not looking to hand over to a new account with no development history sorry.

**Comment by quite** [comment]
No other takers? Recent frequent contributors? @ghybs @kontrollanten @DerGuteWolf

**Comment by nekromoff** [comment]
Hi @danzel, since I have been using your plugin in my [project](https://github.com/nekromoff/bicycle-master-plan) and I would like to upgrade to leaflet 1.6.0, I would be willing to take over and accept the pull requests hanging.

**Comment by ykzeng** [comment]
Hi @danzel Not sure if you all are still looking, I can join with @nekromoff and help contribute with my spare time. My current work project uses a lot of leaflet but those are not on Github.

**Comment by ramirez** [comment]
Hi @danzel are you still looking for maintainers?

**Comment by quite** [comment]
It feels like @danzel really doesn't care about the project. I wonder if there could be some fork already where maintenance has been picked up?

**Comment by marco6** [comment]
It would be nice is @danzel would at least answer. We are using this plugin as well and I can see from npm that it has 80k downloads weekly, which makes this fairly popular. Maybe @mourner can help here, given it is part of the leaflet project?

**Comment by zoltan-sule** [comment]
@quite @nekromoff @ykzeng @ramirez did you find a fork which is updated or you use this one?

**Comment by qrosmeli** [comment]
Hi @danzel I don't really have the time to help in this project but people had volunteer. Is there's any chance to speed up this process?

**Comment by gknapp** [comment]
Request @danzel pass this project over for maintainence so some PRs can be accepted. Looks like a few handles have been suggested.

**Comment by nekromoff** [comment]
Maybe forking would be easier at this point?

**Comment by marco6** [comment]
This project has 868 forks already (and only 14 PR).  How would a new fork differentiate from others? IMHO it would be better to just update the original NPM package, otherwise, all the projects and libraries that depend on this package must be rebuilt...

**Comment by nekromoff** [comment]
Alright, try to contact the author. He does not seem to be responding.

**Comment by kontrollanten** [comment]
> This project has 868 forks already (and only 14 PR). How would a new fork differentiate from others? IMHO it would be better to just update the original NPM package, otherwise, all the projects and libraries that depend on this package must be rebuilt...

By publishing a npm package called `leaflet-marker-cluster` it could differentiate from the other 868 forks. Of course it would be better to update the original npm package, but that has been tried since 23th January without any luck.

**Comment by quite** [comment]
Does @mourner have control over this repo?

**Comment by mourner** [comment]
A little swamped at the moment but let me get back to this next week and see if I could pass the maintenance to the right person. Sorry for the silence, everyone! This has been a difficult year.

**Comment by mourner** [comment]
OK got all the rights in place, ready to clean up and transfer everything soon! @nekromoff @ykzeng are you still free to help out bringing the project up to date? If so, could you send me your e-mails & NPM account names to agafonkin@gmail.com?

**Comment by sjml** [comment]
I hate being the one to bump a thread, but has there been any movement on this? Would it at least be possible to document the most recent version of Leaflet that markercluster will install with?

**Comment by nekromoff** [comment]
I am using it with the current Leaflet 1.7.1 and it works.

**Comment by sjml** [comment]
Trying to install it into my project, I get this: 
```
npm ERR! Could not resolve dependency:
npm ERR! peer leaflet@"~1.3.1" from leaflet.markercluster@1.4.1
```

**Comment by nekromoff** [comment]
I link it directly, not using NPM.

**Comment by sjml** [comment]
Good to know it's functional, and that a simple dependency bump is all that's needed. I was just wondering if the npm publishing had been successfully transferred so that bump can be done, since it looked like @mourner was optimistic about getting it done a few months ago.

**Comment by NormandoHall** [comment]
No news ? :(

**Comment by bre7** [comment]
@sjml https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

package.json
```json
{
  "resolutions": {
    "leaflet": "1.7.1"
  }
}

**Comment by sjml** [comment]
> @sjml https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-why-would-you-want-to-do-this
> 
> package.json
> 
> ```json
> {
>   "resolutions": {
>     "leaflet": "1.7.1"
>   }
> }
> ```

Yeah, I know there are workarounds (I don't use yarn, but have vendored Leaflet.markercluster for the time being). Just wondering if there were still plans to update this so people could install it easily with npm.

**Comment by ykzeng** [comment]
hello guys, sorry for the delays, I finally got with @mourner and now start catching up on everything, hopefully bringing the npm issue resolved ASAP. will post here if any updates

**Comment by NormandoHall** [comment]
@ykzeng  Thanks for merge the PR to update deps. When you think there is ready from npm package?

**Comment by ykzeng** [comment]
> @ykzeng Thanks for merge the PR to update deps. When you think it is ready from npm package?

np, just doing my best to catch up everything on my own. just pushed a new version to npm, it worked well with latest leaflet 1.7.x on my side, could u try getting the latest version and see if your issue is addressed too?

**Comment by ykzeng** [comment]
all, while I am still getting myself familiarized with the repo and publish cycle, I will hopefully start looking thru every meaningful issue and PRs fairly soon. However, I may not have the time and energy to get over every detail. so If you knew any long-held nice features/bug fixes/other PRs that are meaningful to improve markercluster, do not hesitate to refresh the conversations in the community (issues, discussions, all are welcome), or email me directly. I know the project unfortunately has been stale for a while, but I will do my best to pick up the momentum. Let's keep markercluster growing and improving together :)

**Comment by NormandoHall** [comment]
> > @ykzeng Thanks for merge the PR to update deps. When you think it is ready from npm package?
> 
> np, just doing my best to catch up everything on my own. just pushed a new version to npm, it worked well with latest leaflet 1.7.x on my side, could u try getting the latest version and see if your issue is addressed too? @NormandoHall

Thank you so much @ykzeng to fix this long time issue. Runs like a charm!
