### ISSUE TITLE
Loading MarkerClusters while the bounding boxs changes position and display

### ISSUE THREAD

**Issue by MarcRibasGonzalez** [Leaflet/Leaflet.markercluster#985]
Hi, im using leaflet markerClusters and javascript to develop a map where i want to generate clusters according to the screen bounds. I have a service that returns me a list of points depending on screen bounds, with lat and lng properties.
`function loadPoints(zoomActual){
    for (var prop in capesDinamiques) {  
      if(map.getZoom()>3){  
        if(capesDinamiques[prop][0]){

        removeAreaLayer(prop); //clean the other markercluster

        baseLayers[prop] =afegirCapaServeiWeb(capesDinamiques[prop][1]
        +zoomActual._southWest.lng+'&x2='
        +zoomActual._northEast.lng+'&y1='
        +zoomActual._southWest.lat+'&y2='
        +zoomActual._northEast.lat+''); //service that return a list of points

        addAreaLayer(prop);//crating the new marker clusters according to the bounding box

            }   
        }
    }
}

    map.on('moveend', function() {
        var zoomActual = map.getBounds();
        cargarMegaCapes(zoomActual);

    });`

Services example (JSON):
`e {_layers: {…}, _initHooksCalled: true}
_layers:
10054: e
options: {icon: e, title: "", alt: "", clickable: true, draggable: false, …}
_latlng: o.LatLng {lat: 41.5437192894942, lng: 2.44910020452627}
_initHooksCalled: true
properties: undefined
feature: {properties: {…}}
_leaflet_id: 10054
_leaflet_events: {click_idx: {…}, click_idx_len: 1, dblclick_idx: {…}, dblclick_idx_len: 1, mouseover_idx: {…}, …}
__proto__: o.Class
10056: e
options: {icon: e, title: "", alt: "", clickable: true, draggable: false, …}
_latlng: o.LatLng {lat: 41.541313548773, lng: 2.44995964811972}
_initHooksCalled: true
properties: undefined
feature: {properties: {…}}
_leaflet_id: 10056
_leaflet_events: {click_idx: {…}, click_idx_len: 1, dblclick_idx: {…}, dblclick_idx_len: 1, mouseover_idx: {…}, …}
__proto__: o.Class`

Methods i use to add and remove layers and clusters:

```
function addAreaLayer(prop) {
        console.log("AFEGINT CLUSTERS "+ prop);

        active_area_list[prop]=baseLayers[prop];
        markers.addLayer(baseLayers[prop]);

        map.addLayer(markers);
        refreshActive();

};

function removeAreaLayer(prop) {
    if(map.hasLayer(baseLayers[prop])||active_area_list.hasOwnProperty(prop)){
        console.log("ELIMINANT CLUSTERS");

        delete active_area_list[prop];
        markers.removeLayer(baseLayers[prop]);

        map.removeLayer(markers);
        refreshActive();
    }
};

```

The markers doesn't show on the map, but if i activate the layer on map, the loaded clusters shows on map, but not dinamically by changing the bounds. Can you help me with an example or what you think is may be the solution?

Thanks very much

Website where im working as an example of the problem:  
 https://serveisweb.mataro.cat/visorSIG/images/RecursosVisor/SSIT/minisite/leaflet/MARC/visor/?perfil=patrimoni_arquitectonic

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
