### ISSUE TITLE
hello everyone, i am new to leaflet and working on leaflet-draw toolbar, i want to change marker/boxes created at the coordinate points. Actually i even don't know the exact name of this property.

### ISSUE THREAD

**Issue by FatimaAsif11** [Leaflet/Leaflet.markercluster#989]
- [ ] I'm reporting a bug, not asking for help
- [ ] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using:
- Leaflet.MarkerCluster version I'm using:
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by FatimaAsif11** [comment]
![polylines](https://user-images.githubusercontent.com/63395818/78877207-56541e80-7a05-11ea-887f-cf4c8a64cec0.PNG)

as this image shows boxes and i want to change them into circles.

**Comment by davincikab** [comment]
this is custom leaflet icon use the inspect tool on your browser to access its style.

**Comment by FatimaAsif11** [comment]
U can change them by applying css properties,
in leaflet.css on line 561
leaflet-div-icon

**Comment by Falke-Design** [comment]
Can closed with this answer: https://stackoverflow.com/a/63939495/8283938

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
