### ISSUE TITLE
Duplicate markers in clusters when zoomed in

### ISSUE THREAD

**Issue by JoshNewham1** [Leaflet/Leaflet.markercluster#990]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet 1.6.0
- Leaflet.MarkerCluster 1.4.1
- Browser: Google Chrome 81
- OS/Platform: Windows 10
- Large dataset (>1000 markers)

## The behaviour I'm expecting and what I'm seeing
I have quite a large dataset (1078 markers and circles in total) and the clusters/groups are of the proper size when zoomed out to around zoom level 10. The problem lies when I zoom into an area and the groups recalculate and split out. It seems that duplicate markers are introduced at this point as the spider view of most clusters shows multiple duplicate markers and circles. Then, when zoomed in further to the point that the clusters disappear, the correct placement and number of circles/markers is restored.

I originally thought this was a problem with the dynamic JSX components I was adding to the MarkerClusterGroup (as this bug was originally found in React, using react-leaflet and react-leaflet-markercluster). However, I have recreated the issue in plain JavaScript and the problem persists.

I think the problem might lie with the size of my dataset and the density of the points messing with the clustering and spiderfy calculations?
## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

[Original example](https://codesandbox.io/s/react-leaflet-5yo3t) with React.
Example in [plain JavaScript](https://codesandbox.io/s/leaflet-markercluster-bug-m9hej?file=/src/index.js) (probably what will be more useful here).

## Images illustrating the problem
![1](https://user-images.githubusercontent.com/25721451/79682529-faff0900-821a-11ea-818f-f285948fe396.JPG)  ![2](https://user-images.githubusercontent.com/25721451/79682528-fa667280-821a-11ea-93d1-39f4c1dff19e.JPG)

![3](https://user-images.githubusercontent.com/25721451/79682530-fb979f80-821a-11ea-9f4a-c2ff16ca6541.JPG)  ![4](https://user-images.githubusercontent.com/25721451/79682531-fb979f80-821a-11ea-9951-105ba53fda6d.JPG)

**Comment by ghybs** [comment]
Hi,

Looks to me as expected behaviour, given the fact that you have duplicate locations in your data.

Once zoomed in enough, you see the actual position of these places, hence duplicates exactly stack, and you may not notice it.

But when clustered or spiderfied, Leaflet.markercluster will count each place separately, even if all their data is identical: hence the "extra" counts and "ghosts" in spider.

For example I see 2x "Surrey Square Park" and 4x "Burgess Park" in your db.json file, all with exact same data. Therefore when clustered, they count as 6 items.

**Comment by JoshNewham1** [comment]
Hi @ghybs,

You're absolutely right, I can't believe that I didn't see that my data was being duplicated. I have now added a unique index to my DB to stop this from happening.

Thanks everyone else and I'm sorry for wasting anyone's time, just never crossed my mind to check the actual data,
Josh
