### ISSUE TITLE
[Question] markerClusterGroup into another markerClusterGroup

### ISSUE THREAD

**Issue by Inglebard** [Leaflet/Leaflet.markercluster#996]
Hi,

I would like to know, if it is possible to add markerClusterGroup into another markerClusterGroup. I tried but without success.

Why ? Because I would like to separate markerClusterGroup for multiple zones. (Foreach postal code of each country of each continent).

Or maybe there is another way to achieve this ?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
